// Code generated by MockGen. DO NOT EDIT.
// Source: samsaradev.io/infra/dataplatform/databricks (interfaces: API)

// Package mock_databricks is a generated GoMock package.
package mock_databricks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"

	databricks "samsaradev.io/infra/dataplatform/databricks"
)

// MockAPI is a mock of API interface.
type MockAPI struct {
	ctrl     *gomock.Controller
	recorder *MockAPIMockRecorder
}

// MockAPIMockRecorder is the mock recorder for MockAPI.
type MockAPIMockRecorder struct {
	mock *MockAPI
}

// NewMockAPI creates a new mock instance.
func NewMockAPI(ctrl *gomock.Controller) *MockAPI {
	mock := &MockAPI{ctrl: ctrl}
	mock.recorder = &MockAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAPI) EXPECT() *MockAPIMockRecorder {
	return m.recorder
}

// AddInstanceProfile mocks base method.
func (m *MockAPI) AddInstanceProfile(arg0 context.Context, arg1 *databricks.AddInstanceProfileInput) (*databricks.AddInstanceProfileOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddInstanceProfile", arg0, arg1)
	ret0, _ := ret[0].(*databricks.AddInstanceProfileOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddInstanceProfile indicates an expected call of AddInstanceProfile.
func (mr *MockAPIMockRecorder) AddInstanceProfile(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddInstanceProfile", reflect.TypeOf((*MockAPI)(nil).AddInstanceProfile), arg0, arg1)
}

// BaseURL mocks base method.
func (m *MockAPI) BaseURL() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BaseURL")
	ret0, _ := ret[0].(string)
	return ret0
}

// BaseURL indicates an expected call of BaseURL.
func (mr *MockAPIMockRecorder) BaseURL() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BaseURL", reflect.TypeOf((*MockAPI)(nil).BaseURL))
}

// CancelAllJobRuns mocks base method.
func (m *MockAPI) CancelAllJobRuns(arg0 context.Context, arg1 *databricks.CancelAllJobRunsInput) (*databricks.CancelAllJobRunsOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelAllJobRuns", arg0, arg1)
	ret0, _ := ret[0].(*databricks.CancelAllJobRunsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CancelAllJobRuns indicates an expected call of CancelAllJobRuns.
func (mr *MockAPIMockRecorder) CancelAllJobRuns(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelAllJobRuns", reflect.TypeOf((*MockAPI)(nil).CancelAllJobRuns), arg0, arg1)
}

// CancelCommand mocks base method.
func (m *MockAPI) CancelCommand(arg0 context.Context, arg1 *databricks.CancelCommandInput) (*databricks.CancelCommandOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelCommand", arg0, arg1)
	ret0, _ := ret[0].(*databricks.CancelCommandOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CancelCommand indicates an expected call of CancelCommand.
func (mr *MockAPIMockRecorder) CancelCommand(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelCommand", reflect.TypeOf((*MockAPI)(nil).CancelCommand), arg0, arg1)
}

// CancelStatement mocks base method.
func (m *MockAPI) CancelStatement(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelStatement", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CancelStatement indicates an expected call of CancelStatement.
func (mr *MockAPIMockRecorder) CancelStatement(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelStatement", reflect.TypeOf((*MockAPI)(nil).CancelStatement), arg0, arg1)
}

// ChangeCredentialPermissions mocks base method.
func (m *MockAPI) ChangeCredentialPermissions(arg0 context.Context, arg1 *databricks.PatchCredentialPermissionsInput) (*databricks.PrivilegeAssignments, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangeCredentialPermissions", arg0, arg1)
	ret0, _ := ret[0].(*databricks.PrivilegeAssignments)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ChangeCredentialPermissions indicates an expected call of ChangeCredentialPermissions.
func (mr *MockAPIMockRecorder) ChangeCredentialPermissions(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangeCredentialPermissions", reflect.TypeOf((*MockAPI)(nil).ChangeCredentialPermissions), arg0, arg1)
}

// ClusterLibraryStatuses mocks base method.
func (m *MockAPI) ClusterLibraryStatuses(arg0 context.Context, arg1 *databricks.ClusterLibraryStatusesInput) (*databricks.ClusterLibraryStatusesOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClusterLibraryStatuses", arg0, arg1)
	ret0, _ := ret[0].(*databricks.ClusterLibraryStatusesOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClusterLibraryStatuses indicates an expected call of ClusterLibraryStatuses.
func (mr *MockAPIMockRecorder) ClusterLibraryStatuses(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClusterLibraryStatuses", reflect.TypeOf((*MockAPI)(nil).ClusterLibraryStatuses), arg0, arg1)
}

// CreateCloudCredential mocks base method.
func (m *MockAPI) CreateCloudCredential(arg0 context.Context, arg1 *databricks.CreateCredentialInput) (*databricks.CloudCredential, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCloudCredential", arg0, arg1)
	ret0, _ := ret[0].(*databricks.CloudCredential)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCloudCredential indicates an expected call of CreateCloudCredential.
func (mr *MockAPIMockRecorder) CreateCloudCredential(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCloudCredential", reflect.TypeOf((*MockAPI)(nil).CreateCloudCredential), arg0, arg1)
}

// CreateCluster mocks base method.
func (m *MockAPI) CreateCluster(arg0 context.Context, arg1 *databricks.CreateClusterInput) (*databricks.CreateClusterOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCluster", arg0, arg1)
	ret0, _ := ret[0].(*databricks.CreateClusterOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCluster indicates an expected call of CreateCluster.
func (mr *MockAPIMockRecorder) CreateCluster(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCluster", reflect.TypeOf((*MockAPI)(nil).CreateCluster), arg0, arg1)
}

// CreateClusterPolicy mocks base method.
func (m *MockAPI) CreateClusterPolicy(arg0 context.Context, arg1 *databricks.CreateClusterPolicyInput) (*databricks.CreateClusterPolicyOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateClusterPolicy", arg0, arg1)
	ret0, _ := ret[0].(*databricks.CreateClusterPolicyOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateClusterPolicy indicates an expected call of CreateClusterPolicy.
func (mr *MockAPIMockRecorder) CreateClusterPolicy(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateClusterPolicy", reflect.TypeOf((*MockAPI)(nil).CreateClusterPolicy), arg0, arg1)
}

// CreateExecutionContext mocks base method.
func (m *MockAPI) CreateExecutionContext(arg0 context.Context, arg1 *databricks.CreateExecutionContextInput) (*databricks.CreateExecutionContextOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateExecutionContext", arg0, arg1)
	ret0, _ := ret[0].(*databricks.CreateExecutionContextOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateExecutionContext indicates an expected call of CreateExecutionContext.
func (mr *MockAPIMockRecorder) CreateExecutionContext(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateExecutionContext", reflect.TypeOf((*MockAPI)(nil).CreateExecutionContext), arg0, arg1)
}

// CreateGroup mocks base method.
func (m *MockAPI) CreateGroup(arg0 context.Context, arg1 *databricks.CreateGroupInput) (*databricks.CreateGroupOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateGroup", arg0, arg1)
	ret0, _ := ret[0].(*databricks.CreateGroupOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateGroup indicates an expected call of CreateGroup.
func (mr *MockAPIMockRecorder) CreateGroup(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateGroup", reflect.TypeOf((*MockAPI)(nil).CreateGroup), arg0, arg1)
}

// CreateIPAccessList mocks base method.
func (m *MockAPI) CreateIPAccessList(arg0 context.Context, arg1 *databricks.CreateIPAccessListInput) (*databricks.CreateIPAccessListOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateIPAccessList", arg0, arg1)
	ret0, _ := ret[0].(*databricks.CreateIPAccessListOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateIPAccessList indicates an expected call of CreateIPAccessList.
func (mr *MockAPIMockRecorder) CreateIPAccessList(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateIPAccessList", reflect.TypeOf((*MockAPI)(nil).CreateIPAccessList), arg0, arg1)
}

// CreateInstancePool mocks base method.
func (m *MockAPI) CreateInstancePool(arg0 context.Context, arg1 *databricks.CreateInstancePoolInput) (*databricks.CreateInstancePoolOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateInstancePool", arg0, arg1)
	ret0, _ := ret[0].(*databricks.CreateInstancePoolOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateInstancePool indicates an expected call of CreateInstancePool.
func (mr *MockAPIMockRecorder) CreateInstancePool(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateInstancePool", reflect.TypeOf((*MockAPI)(nil).CreateInstancePool), arg0, arg1)
}

// CreateJob mocks base method.
func (m *MockAPI) CreateJob(arg0 context.Context, arg1 *databricks.CreateJobInput) (*databricks.CreateJobOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateJob", arg0, arg1)
	ret0, _ := ret[0].(*databricks.CreateJobOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateJob indicates an expected call of CreateJob.
func (mr *MockAPIMockRecorder) CreateJob(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateJob", reflect.TypeOf((*MockAPI)(nil).CreateJob), arg0, arg1)
}

// CreateSQLVisualization mocks base method.
func (m *MockAPI) CreateSQLVisualization(arg0 context.Context, arg1 *databricks.Visualization) (*databricks.Visualization, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSQLVisualization", arg0, arg1)
	ret0, _ := ret[0].(*databricks.Visualization)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSQLVisualization indicates an expected call of CreateSQLVisualization.
func (mr *MockAPIMockRecorder) CreateSQLVisualization(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSQLVisualization", reflect.TypeOf((*MockAPI)(nil).CreateSQLVisualization), arg0, arg1)
}

// CreateSQLWidget mocks base method.
func (m *MockAPI) CreateSQLWidget(arg0 context.Context, arg1 *databricks.Widget) (*databricks.Widget, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSQLWidget", arg0, arg1)
	ret0, _ := ret[0].(*databricks.Widget)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSQLWidget indicates an expected call of CreateSQLWidget.
func (mr *MockAPIMockRecorder) CreateSQLWidget(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSQLWidget", reflect.TypeOf((*MockAPI)(nil).CreateSQLWidget), arg0, arg1)
}

// CreateSqlDashboard mocks base method.
func (m *MockAPI) CreateSqlDashboard(arg0 context.Context, arg1 *databricks.SqlDashboard) (*databricks.SqlDashboard, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSqlDashboard", arg0, arg1)
	ret0, _ := ret[0].(*databricks.SqlDashboard)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSqlDashboard indicates an expected call of CreateSqlDashboard.
func (mr *MockAPIMockRecorder) CreateSqlDashboard(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSqlDashboard", reflect.TypeOf((*MockAPI)(nil).CreateSqlDashboard), arg0, arg1)
}

// CreateSqlDashboardSchedule mocks base method.
func (m *MockAPI) CreateSqlDashboardSchedule(arg0 context.Context, arg1 *databricks.CreateSqlDashboardScheduleInput) (*databricks.SqlDashboardSchedule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSqlDashboardSchedule", arg0, arg1)
	ret0, _ := ret[0].(*databricks.SqlDashboardSchedule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSqlDashboardSchedule indicates an expected call of CreateSqlDashboardSchedule.
func (mr *MockAPIMockRecorder) CreateSqlDashboardSchedule(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSqlDashboardSchedule", reflect.TypeOf((*MockAPI)(nil).CreateSqlDashboardSchedule), arg0, arg1)
}

// CreateSqlEndpoint mocks base method.
func (m *MockAPI) CreateSqlEndpoint(arg0 context.Context, arg1 *databricks.CreateSqlEndpointInput) (*databricks.CreateSqlEndpointOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSqlEndpoint", arg0, arg1)
	ret0, _ := ret[0].(*databricks.CreateSqlEndpointOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSqlEndpoint indicates an expected call of CreateSqlEndpoint.
func (mr *MockAPIMockRecorder) CreateSqlEndpoint(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSqlEndpoint", reflect.TypeOf((*MockAPI)(nil).CreateSqlEndpoint), arg0, arg1)
}

// CreateSqlQuery mocks base method.
func (m *MockAPI) CreateSqlQuery(arg0 context.Context, arg1 *databricks.Query) (*databricks.Query, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSqlQuery", arg0, arg1)
	ret0, _ := ret[0].(*databricks.Query)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSqlQuery indicates an expected call of CreateSqlQuery.
func (mr *MockAPIMockRecorder) CreateSqlQuery(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSqlQuery", reflect.TypeOf((*MockAPI)(nil).CreateSqlQuery), arg0, arg1)
}

// CreateToken mocks base method.
func (m *MockAPI) CreateToken(arg0 context.Context, arg1 *databricks.CreateTokenInput) (*databricks.CreateTokenOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateToken", arg0, arg1)
	ret0, _ := ret[0].(*databricks.CreateTokenOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateToken indicates an expected call of CreateToken.
func (mr *MockAPIMockRecorder) CreateToken(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateToken", reflect.TypeOf((*MockAPI)(nil).CreateToken), arg0, arg1)
}

// CreateUser mocks base method.
func (m *MockAPI) CreateUser(arg0 context.Context, arg1 *databricks.CreateUserInput) (*databricks.CreateUserOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", arg0, arg1)
	ret0, _ := ret[0].(*databricks.CreateUserOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockAPIMockRecorder) CreateUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockAPI)(nil).CreateUser), arg0, arg1)
}

// DeleteCloudCredential mocks base method.
func (m *MockAPI) DeleteCloudCredential(arg0 context.Context, arg1 *databricks.DeleteCredentialInput) (*databricks.DeleteCredentialOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCloudCredential", arg0, arg1)
	ret0, _ := ret[0].(*databricks.DeleteCredentialOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteCloudCredential indicates an expected call of DeleteCloudCredential.
func (mr *MockAPIMockRecorder) DeleteCloudCredential(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCloudCredential", reflect.TypeOf((*MockAPI)(nil).DeleteCloudCredential), arg0, arg1)
}

// DeleteClusterPolicy mocks base method.
func (m *MockAPI) DeleteClusterPolicy(arg0 context.Context, arg1 *databricks.DeleteClusterPolicyInput) (*databricks.DeleteClusterPolicyOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteClusterPolicy", arg0, arg1)
	ret0, _ := ret[0].(*databricks.DeleteClusterPolicyOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteClusterPolicy indicates an expected call of DeleteClusterPolicy.
func (mr *MockAPIMockRecorder) DeleteClusterPolicy(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteClusterPolicy", reflect.TypeOf((*MockAPI)(nil).DeleteClusterPolicy), arg0, arg1)
}

// DeleteGroup mocks base method.
func (m *MockAPI) DeleteGroup(arg0 context.Context, arg1 *databricks.DeleteGroupInput) (*databricks.DeleteGroupOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteGroup", arg0, arg1)
	ret0, _ := ret[0].(*databricks.DeleteGroupOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteGroup indicates an expected call of DeleteGroup.
func (mr *MockAPIMockRecorder) DeleteGroup(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteGroup", reflect.TypeOf((*MockAPI)(nil).DeleteGroup), arg0, arg1)
}

// DeleteIPAccessList mocks base method.
func (m *MockAPI) DeleteIPAccessList(arg0 context.Context, arg1 *databricks.DeleteIPAccessListInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteIPAccessList", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteIPAccessList indicates an expected call of DeleteIPAccessList.
func (mr *MockAPIMockRecorder) DeleteIPAccessList(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteIPAccessList", reflect.TypeOf((*MockAPI)(nil).DeleteIPAccessList), arg0, arg1)
}

// DeleteInstancePool mocks base method.
func (m *MockAPI) DeleteInstancePool(arg0 context.Context, arg1 *databricks.DeleteInstancePoolInput) (*databricks.DeleteInstancePoolOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteInstancePool", arg0, arg1)
	ret0, _ := ret[0].(*databricks.DeleteInstancePoolOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteInstancePool indicates an expected call of DeleteInstancePool.
func (mr *MockAPIMockRecorder) DeleteInstancePool(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteInstancePool", reflect.TypeOf((*MockAPI)(nil).DeleteInstancePool), arg0, arg1)
}

// DeleteJob mocks base method.
func (m *MockAPI) DeleteJob(arg0 context.Context, arg1 *databricks.DeleteJobInput) (*databricks.DeleteJobOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteJob", arg0, arg1)
	ret0, _ := ret[0].(*databricks.DeleteJobOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteJob indicates an expected call of DeleteJob.
func (mr *MockAPIMockRecorder) DeleteJob(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteJob", reflect.TypeOf((*MockAPI)(nil).DeleteJob), arg0, arg1)
}

// DeleteSQLVisualization mocks base method.
func (m *MockAPI) DeleteSQLVisualization(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSQLVisualization", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSQLVisualization indicates an expected call of DeleteSQLVisualization.
func (mr *MockAPIMockRecorder) DeleteSQLVisualization(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSQLVisualization", reflect.TypeOf((*MockAPI)(nil).DeleteSQLVisualization), arg0, arg1)
}

// DeleteSQLWidget mocks base method.
func (m *MockAPI) DeleteSQLWidget(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSQLWidget", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSQLWidget indicates an expected call of DeleteSQLWidget.
func (mr *MockAPIMockRecorder) DeleteSQLWidget(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSQLWidget", reflect.TypeOf((*MockAPI)(nil).DeleteSQLWidget), arg0, arg1)
}

// DeleteSqlDashboard mocks base method.
func (m *MockAPI) DeleteSqlDashboard(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSqlDashboard", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSqlDashboard indicates an expected call of DeleteSqlDashboard.
func (mr *MockAPIMockRecorder) DeleteSqlDashboard(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSqlDashboard", reflect.TypeOf((*MockAPI)(nil).DeleteSqlDashboard), arg0, arg1)
}

// DeleteSqlDashboardSchedule mocks base method.
func (m *MockAPI) DeleteSqlDashboardSchedule(arg0 context.Context, arg1 *databricks.DeleteSqlDashboardScheduleInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSqlDashboardSchedule", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSqlDashboardSchedule indicates an expected call of DeleteSqlDashboardSchedule.
func (mr *MockAPIMockRecorder) DeleteSqlDashboardSchedule(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSqlDashboardSchedule", reflect.TypeOf((*MockAPI)(nil).DeleteSqlDashboardSchedule), arg0, arg1)
}

// DeleteSqlEndpoint mocks base method.
func (m *MockAPI) DeleteSqlEndpoint(arg0 context.Context, arg1 *databricks.DeleteSqlEndpointInput) (*databricks.DeleteSqlEndpointOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSqlEndpoint", arg0, arg1)
	ret0, _ := ret[0].(*databricks.DeleteSqlEndpointOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteSqlEndpoint indicates an expected call of DeleteSqlEndpoint.
func (mr *MockAPIMockRecorder) DeleteSqlEndpoint(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSqlEndpoint", reflect.TypeOf((*MockAPI)(nil).DeleteSqlEndpoint), arg0, arg1)
}

// DeleteSqlQuery mocks base method.
func (m *MockAPI) DeleteSqlQuery(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSqlQuery", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSqlQuery indicates an expected call of DeleteSqlQuery.
func (mr *MockAPIMockRecorder) DeleteSqlQuery(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSqlQuery", reflect.TypeOf((*MockAPI)(nil).DeleteSqlQuery), arg0, arg1)
}

// DeleteToken mocks base method.
func (m *MockAPI) DeleteToken(arg0 context.Context, arg1 *databricks.DeleteTokenInput) (*databricks.DeleteTokenOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteToken", arg0, arg1)
	ret0, _ := ret[0].(*databricks.DeleteTokenOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteToken indicates an expected call of DeleteToken.
func (mr *MockAPIMockRecorder) DeleteToken(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteToken", reflect.TypeOf((*MockAPI)(nil).DeleteToken), arg0, arg1)
}

// DeleteUser mocks base method.
func (m *MockAPI) DeleteUser(arg0 context.Context, arg1 *databricks.DeleteUserInput) (*databricks.DeleteUserOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUser", arg0, arg1)
	ret0, _ := ret[0].(*databricks.DeleteUserOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteUser indicates an expected call of DeleteUser.
func (mr *MockAPIMockRecorder) DeleteUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUser", reflect.TypeOf((*MockAPI)(nil).DeleteUser), arg0, arg1)
}

// DestroyExecutionContext mocks base method.
func (m *MockAPI) DestroyExecutionContext(arg0 context.Context, arg1 *databricks.DestroyExecutionContextInput) (*databricks.DestroyExecutionContextOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DestroyExecutionContext", arg0, arg1)
	ret0, _ := ret[0].(*databricks.DestroyExecutionContextOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DestroyExecutionContext indicates an expected call of DestroyExecutionContext.
func (mr *MockAPIMockRecorder) DestroyExecutionContext(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DestroyExecutionContext", reflect.TypeOf((*MockAPI)(nil).DestroyExecutionContext), arg0, arg1)
}

// EditCluster mocks base method.
func (m *MockAPI) EditCluster(arg0 context.Context, arg1 *databricks.EditClusterInput) (*databricks.EditClusterOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EditCluster", arg0, arg1)
	ret0, _ := ret[0].(*databricks.EditClusterOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EditCluster indicates an expected call of EditCluster.
func (mr *MockAPIMockRecorder) EditCluster(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EditCluster", reflect.TypeOf((*MockAPI)(nil).EditCluster), arg0, arg1)
}

// EditClusterPolicy mocks base method.
func (m *MockAPI) EditClusterPolicy(arg0 context.Context, arg1 *databricks.EditClusterPolicyInput) (*databricks.EditClusterPolicyOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EditClusterPolicy", arg0, arg1)
	ret0, _ := ret[0].(*databricks.EditClusterPolicyOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EditClusterPolicy indicates an expected call of EditClusterPolicy.
func (mr *MockAPIMockRecorder) EditClusterPolicy(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EditClusterPolicy", reflect.TypeOf((*MockAPI)(nil).EditClusterPolicy), arg0, arg1)
}

// EditGlobalSqlEndpointsConfig mocks base method.
func (m *MockAPI) EditGlobalSqlEndpointsConfig(arg0 context.Context, arg1 *databricks.EditGlobalSqlEndpointsConfigInput) (*databricks.EditGlobalSqlEndpointsConfigOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EditGlobalSqlEndpointsConfig", arg0, arg1)
	ret0, _ := ret[0].(*databricks.EditGlobalSqlEndpointsConfigOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EditGlobalSqlEndpointsConfig indicates an expected call of EditGlobalSqlEndpointsConfig.
func (mr *MockAPIMockRecorder) EditGlobalSqlEndpointsConfig(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EditGlobalSqlEndpointsConfig", reflect.TypeOf((*MockAPI)(nil).EditGlobalSqlEndpointsConfig), arg0, arg1)
}

// EditIPAccessList mocks base method.
func (m *MockAPI) EditIPAccessList(arg0 context.Context, arg1 *databricks.EditIPAccessListInput) (*databricks.EditIPAccessListOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EditIPAccessList", arg0, arg1)
	ret0, _ := ret[0].(*databricks.EditIPAccessListOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EditIPAccessList indicates an expected call of EditIPAccessList.
func (mr *MockAPIMockRecorder) EditIPAccessList(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EditIPAccessList", reflect.TypeOf((*MockAPI)(nil).EditIPAccessList), arg0, arg1)
}

// EditInstancePool mocks base method.
func (m *MockAPI) EditInstancePool(arg0 context.Context, arg1 *databricks.EditInstancePoolInput) (*databricks.EditInstancePoolOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EditInstancePool", arg0, arg1)
	ret0, _ := ret[0].(*databricks.EditInstancePoolOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EditInstancePool indicates an expected call of EditInstancePool.
func (mr *MockAPIMockRecorder) EditInstancePool(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EditInstancePool", reflect.TypeOf((*MockAPI)(nil).EditInstancePool), arg0, arg1)
}

// EditInstanceProfile mocks base method.
func (m *MockAPI) EditInstanceProfile(arg0 context.Context, arg1 *databricks.EditInstanceProfileInput) (*databricks.EditInstanceProfileOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EditInstanceProfile", arg0, arg1)
	ret0, _ := ret[0].(*databricks.EditInstanceProfileOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EditInstanceProfile indicates an expected call of EditInstanceProfile.
func (mr *MockAPIMockRecorder) EditInstanceProfile(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EditInstanceProfile", reflect.TypeOf((*MockAPI)(nil).EditInstanceProfile), arg0, arg1)
}

// EditSQLVisualization mocks base method.
func (m *MockAPI) EditSQLVisualization(arg0 context.Context, arg1 string, arg2 *databricks.Visualization) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EditSQLVisualization", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// EditSQLVisualization indicates an expected call of EditSQLVisualization.
func (mr *MockAPIMockRecorder) EditSQLVisualization(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EditSQLVisualization", reflect.TypeOf((*MockAPI)(nil).EditSQLVisualization), arg0, arg1, arg2)
}

// EditSQLWidget mocks base method.
func (m *MockAPI) EditSQLWidget(arg0 context.Context, arg1 string, arg2 *databricks.Widget) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EditSQLWidget", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// EditSQLWidget indicates an expected call of EditSQLWidget.
func (mr *MockAPIMockRecorder) EditSQLWidget(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EditSQLWidget", reflect.TypeOf((*MockAPI)(nil).EditSQLWidget), arg0, arg1, arg2)
}

// EditSqlDashboard mocks base method.
func (m *MockAPI) EditSqlDashboard(arg0 context.Context, arg1 string, arg2 *databricks.SqlDashboard) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EditSqlDashboard", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// EditSqlDashboard indicates an expected call of EditSqlDashboard.
func (mr *MockAPIMockRecorder) EditSqlDashboard(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EditSqlDashboard", reflect.TypeOf((*MockAPI)(nil).EditSqlDashboard), arg0, arg1, arg2)
}

// EditSqlDashboardSchedule mocks base method.
func (m *MockAPI) EditSqlDashboardSchedule(arg0 context.Context, arg1 *databricks.EditSqlDashboardScheduleInput) (*databricks.SqlDashboardSchedule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EditSqlDashboardSchedule", arg0, arg1)
	ret0, _ := ret[0].(*databricks.SqlDashboardSchedule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EditSqlDashboardSchedule indicates an expected call of EditSqlDashboardSchedule.
func (mr *MockAPIMockRecorder) EditSqlDashboardSchedule(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EditSqlDashboardSchedule", reflect.TypeOf((*MockAPI)(nil).EditSqlDashboardSchedule), arg0, arg1)
}

// EditSqlEndpoint mocks base method.
func (m *MockAPI) EditSqlEndpoint(arg0 context.Context, arg1 *databricks.EditSqlEndpointInput) (*databricks.EditSqlEndpointOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EditSqlEndpoint", arg0, arg1)
	ret0, _ := ret[0].(*databricks.EditSqlEndpointOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EditSqlEndpoint indicates an expected call of EditSqlEndpoint.
func (mr *MockAPIMockRecorder) EditSqlEndpoint(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EditSqlEndpoint", reflect.TypeOf((*MockAPI)(nil).EditSqlEndpoint), arg0, arg1)
}

// EditSqlQuery mocks base method.
func (m *MockAPI) EditSqlQuery(arg0 context.Context, arg1 string, arg2 *databricks.Query) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EditSqlQuery", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// EditSqlQuery indicates an expected call of EditSqlQuery.
func (mr *MockAPIMockRecorder) EditSqlQuery(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EditSqlQuery", reflect.TypeOf((*MockAPI)(nil).EditSqlQuery), arg0, arg1, arg2)
}

// EditWorkspaceConf mocks base method.
func (m *MockAPI) EditWorkspaceConf(arg0 context.Context, arg1 *databricks.EditWorkspaceConfInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EditWorkspaceConf", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// EditWorkspaceConf indicates an expected call of EditWorkspaceConf.
func (mr *MockAPIMockRecorder) EditWorkspaceConf(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EditWorkspaceConf", reflect.TypeOf((*MockAPI)(nil).EditWorkspaceConf), arg0, arg1)
}

// ExecuteCommand mocks base method.
func (m *MockAPI) ExecuteCommand(arg0 context.Context, arg1 *databricks.ExecuteCommandInput) (*databricks.ExecuteCommandOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteCommand", arg0, arg1)
	ret0, _ := ret[0].(*databricks.ExecuteCommandOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecuteCommand indicates an expected call of ExecuteCommand.
func (mr *MockAPIMockRecorder) ExecuteCommand(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteCommand", reflect.TypeOf((*MockAPI)(nil).ExecuteCommand), arg0, arg1)
}

// ExecuteStatement mocks base method.
func (m *MockAPI) ExecuteStatement(arg0 context.Context, arg1 *databricks.ExecuteStatementInput) (*databricks.ExecuteStatementOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteStatement", arg0, arg1)
	ret0, _ := ret[0].(*databricks.ExecuteStatementOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecuteStatement indicates an expected call of ExecuteStatement.
func (mr *MockAPIMockRecorder) ExecuteStatement(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteStatement", reflect.TypeOf((*MockAPI)(nil).ExecuteStatement), arg0, arg1)
}

// GetAllIPAccessLists mocks base method.
func (m *MockAPI) GetAllIPAccessLists(arg0 context.Context) (*databricks.GetAllIPAccessListsOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllIPAccessLists", arg0)
	ret0, _ := ret[0].(*databricks.GetAllIPAccessListsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllIPAccessLists indicates an expected call of GetAllIPAccessLists.
func (mr *MockAPIMockRecorder) GetAllIPAccessLists(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllIPAccessLists", reflect.TypeOf((*MockAPI)(nil).GetAllIPAccessLists), arg0)
}

// GetCloudCredential mocks base method.
func (m *MockAPI) GetCloudCredential(arg0 context.Context, arg1 *databricks.GetCredentialInput) (*databricks.GetCredentialOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCloudCredential", arg0, arg1)
	ret0, _ := ret[0].(*databricks.GetCredentialOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCloudCredential indicates an expected call of GetCloudCredential.
func (mr *MockAPIMockRecorder) GetCloudCredential(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCloudCredential", reflect.TypeOf((*MockAPI)(nil).GetCloudCredential), arg0, arg1)
}

// GetCluster mocks base method.
func (m *MockAPI) GetCluster(arg0 context.Context, arg1 *databricks.GetClusterInput) (*databricks.GetClusterOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCluster", arg0, arg1)
	ret0, _ := ret[0].(*databricks.GetClusterOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCluster indicates an expected call of GetCluster.
func (mr *MockAPIMockRecorder) GetCluster(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCluster", reflect.TypeOf((*MockAPI)(nil).GetCluster), arg0, arg1)
}

// GetClusterPolicy mocks base method.
func (m *MockAPI) GetClusterPolicy(arg0 context.Context, arg1 *databricks.GetClusterPolicyInput) (*databricks.GetClusterPolicyOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClusterPolicy", arg0, arg1)
	ret0, _ := ret[0].(*databricks.GetClusterPolicyOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetClusterPolicy indicates an expected call of GetClusterPolicy.
func (mr *MockAPIMockRecorder) GetClusterPolicy(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClusterPolicy", reflect.TypeOf((*MockAPI)(nil).GetClusterPolicy), arg0, arg1)
}

// GetCommandStatus mocks base method.
func (m *MockAPI) GetCommandStatus(arg0 context.Context, arg1 *databricks.GetCommandStatusInput) (*databricks.GetCommandStatusOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCommandStatus", arg0, arg1)
	ret0, _ := ret[0].(*databricks.GetCommandStatusOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCommandStatus indicates an expected call of GetCommandStatus.
func (mr *MockAPIMockRecorder) GetCommandStatus(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCommandStatus", reflect.TypeOf((*MockAPI)(nil).GetCommandStatus), arg0, arg1)
}

// GetGlobalSqlEndpointsConfig mocks base method.
func (m *MockAPI) GetGlobalSqlEndpointsConfig(arg0 context.Context, arg1 *databricks.GetGlobalSqlEndpointsConfigInput) (*databricks.GetGlobalSqlEndpointsConfigOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGlobalSqlEndpointsConfig", arg0, arg1)
	ret0, _ := ret[0].(*databricks.GetGlobalSqlEndpointsConfigOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGlobalSqlEndpointsConfig indicates an expected call of GetGlobalSqlEndpointsConfig.
func (mr *MockAPIMockRecorder) GetGlobalSqlEndpointsConfig(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGlobalSqlEndpointsConfig", reflect.TypeOf((*MockAPI)(nil).GetGlobalSqlEndpointsConfig), arg0, arg1)
}

// GetGroup mocks base method.
func (m *MockAPI) GetGroup(arg0 context.Context, arg1 *databricks.GetGroupInput) (*databricks.GetGroupOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGroup", arg0, arg1)
	ret0, _ := ret[0].(*databricks.GetGroupOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGroup indicates an expected call of GetGroup.
func (mr *MockAPIMockRecorder) GetGroup(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGroup", reflect.TypeOf((*MockAPI)(nil).GetGroup), arg0, arg1)
}

// GetGroups mocks base method.
func (m *MockAPI) GetGroups(arg0 context.Context, arg1 *databricks.GetGroupsInput) (*databricks.GetGroupsOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGroups", arg0, arg1)
	ret0, _ := ret[0].(*databricks.GetGroupsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGroups indicates an expected call of GetGroups.
func (mr *MockAPIMockRecorder) GetGroups(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGroups", reflect.TypeOf((*MockAPI)(nil).GetGroups), arg0, arg1)
}

// GetIPAccessList mocks base method.
func (m *MockAPI) GetIPAccessList(arg0 context.Context, arg1 *databricks.GetIPAccessListInput) (*databricks.GetIPAccessListOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIPAccessList", arg0, arg1)
	ret0, _ := ret[0].(*databricks.GetIPAccessListOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIPAccessList indicates an expected call of GetIPAccessList.
func (mr *MockAPIMockRecorder) GetIPAccessList(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIPAccessList", reflect.TypeOf((*MockAPI)(nil).GetIPAccessList), arg0, arg1)
}

// GetInstancePool mocks base method.
func (m *MockAPI) GetInstancePool(arg0 context.Context, arg1 *databricks.GetInstancePoolInput) (*databricks.GetInstancePoolOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInstancePool", arg0, arg1)
	ret0, _ := ret[0].(*databricks.GetInstancePoolOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInstancePool indicates an expected call of GetInstancePool.
func (mr *MockAPIMockRecorder) GetInstancePool(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInstancePool", reflect.TypeOf((*MockAPI)(nil).GetInstancePool), arg0, arg1)
}

// GetJob mocks base method.
func (m *MockAPI) GetJob(arg0 context.Context, arg1 *databricks.GetJobInput) (*databricks.GetJobOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJob", arg0, arg1)
	ret0, _ := ret[0].(*databricks.GetJobOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetJob indicates an expected call of GetJob.
func (mr *MockAPIMockRecorder) GetJob(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJob", reflect.TypeOf((*MockAPI)(nil).GetJob), arg0, arg1)
}

// GetPermissions mocks base method.
func (m *MockAPI) GetPermissions(arg0 context.Context, arg1 *databricks.GetPermissionsInput) (*databricks.GetPermissionsOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPermissions", arg0, arg1)
	ret0, _ := ret[0].(*databricks.GetPermissionsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPermissions indicates an expected call of GetPermissions.
func (mr *MockAPIMockRecorder) GetPermissions(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPermissions", reflect.TypeOf((*MockAPI)(nil).GetPermissions), arg0, arg1)
}

// GetResultChunk mocks base method.
func (m *MockAPI) GetResultChunk(arg0 context.Context, arg1 string, arg2 int64) (*databricks.ResultChunk, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetResultChunk", arg0, arg1, arg2)
	ret0, _ := ret[0].(*databricks.ResultChunk)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetResultChunk indicates an expected call of GetResultChunk.
func (mr *MockAPIMockRecorder) GetResultChunk(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetResultChunk", reflect.TypeOf((*MockAPI)(nil).GetResultChunk), arg0, arg1, arg2)
}

// GetRun mocks base method.
func (m *MockAPI) GetRun(arg0 context.Context, arg1 *databricks.GetRunInput) (*databricks.GetRunOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRun", arg0, arg1)
	ret0, _ := ret[0].(*databricks.GetRunOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRun indicates an expected call of GetRun.
func (mr *MockAPIMockRecorder) GetRun(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRun", reflect.TypeOf((*MockAPI)(nil).GetRun), arg0, arg1)
}

// GetRunOutput mocks base method.
func (m *MockAPI) GetRunOutput(arg0 context.Context, arg1 *databricks.GetRunOutputInput) (*databricks.GetRunOutputOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRunOutput", arg0, arg1)
	ret0, _ := ret[0].(*databricks.GetRunOutputOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRunOutput indicates an expected call of GetRunOutput.
func (mr *MockAPIMockRecorder) GetRunOutput(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRunOutput", reflect.TypeOf((*MockAPI)(nil).GetRunOutput), arg0, arg1)
}

// GetSQLVisualization mocks base method.
func (m *MockAPI) GetSQLVisualization(arg0 context.Context, arg1, arg2 string) (*databricks.Visualization, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSQLVisualization", arg0, arg1, arg2)
	ret0, _ := ret[0].(*databricks.Visualization)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSQLVisualization indicates an expected call of GetSQLVisualization.
func (mr *MockAPIMockRecorder) GetSQLVisualization(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSQLVisualization", reflect.TypeOf((*MockAPI)(nil).GetSQLVisualization), arg0, arg1, arg2)
}

// GetSQLWidget mocks base method.
func (m *MockAPI) GetSQLWidget(arg0 context.Context, arg1, arg2 string) (*databricks.Widget, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSQLWidget", arg0, arg1, arg2)
	ret0, _ := ret[0].(*databricks.Widget)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSQLWidget indicates an expected call of GetSQLWidget.
func (mr *MockAPIMockRecorder) GetSQLWidget(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSQLWidget", reflect.TypeOf((*MockAPI)(nil).GetSQLWidget), arg0, arg1, arg2)
}

// GetSqlDashboard mocks base method.
func (m *MockAPI) GetSqlDashboard(arg0 context.Context, arg1 string) (*databricks.SqlDashboard, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSqlDashboard", arg0, arg1)
	ret0, _ := ret[0].(*databricks.SqlDashboard)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSqlDashboard indicates an expected call of GetSqlDashboard.
func (mr *MockAPIMockRecorder) GetSqlDashboard(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSqlDashboard", reflect.TypeOf((*MockAPI)(nil).GetSqlDashboard), arg0, arg1)
}

// GetSqlDashboardSchedule mocks base method.
func (m *MockAPI) GetSqlDashboardSchedule(arg0 context.Context, arg1 *databricks.GetSqlDashboardScheduleInput) (*databricks.SqlDashboardSchedule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSqlDashboardSchedule", arg0, arg1)
	ret0, _ := ret[0].(*databricks.SqlDashboardSchedule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSqlDashboardSchedule indicates an expected call of GetSqlDashboardSchedule.
func (mr *MockAPIMockRecorder) GetSqlDashboardSchedule(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSqlDashboardSchedule", reflect.TypeOf((*MockAPI)(nil).GetSqlDashboardSchedule), arg0, arg1)
}

// GetSqlEndpoint mocks base method.
func (m *MockAPI) GetSqlEndpoint(arg0 context.Context, arg1 *databricks.GetSqlEndpointInput) (*databricks.GetSqlEndpointOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSqlEndpoint", arg0, arg1)
	ret0, _ := ret[0].(*databricks.GetSqlEndpointOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSqlEndpoint indicates an expected call of GetSqlEndpoint.
func (mr *MockAPIMockRecorder) GetSqlEndpoint(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSqlEndpoint", reflect.TypeOf((*MockAPI)(nil).GetSqlEndpoint), arg0, arg1)
}

// GetSqlQuery mocks base method.
func (m *MockAPI) GetSqlQuery(arg0 context.Context, arg1 string) (*databricks.Query, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSqlQuery", arg0, arg1)
	ret0, _ := ret[0].(*databricks.Query)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSqlQuery indicates an expected call of GetSqlQuery.
func (mr *MockAPIMockRecorder) GetSqlQuery(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSqlQuery", reflect.TypeOf((*MockAPI)(nil).GetSqlQuery), arg0, arg1)
}

// GetStatement mocks base method.
func (m *MockAPI) GetStatement(arg0 context.Context, arg1 string) (*databricks.ExecuteStatementOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStatement", arg0, arg1)
	ret0, _ := ret[0].(*databricks.ExecuteStatementOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStatement indicates an expected call of GetStatement.
func (mr *MockAPIMockRecorder) GetStatement(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStatement", reflect.TypeOf((*MockAPI)(nil).GetStatement), arg0, arg1)
}

// GetUser mocks base method.
func (m *MockAPI) GetUser(arg0 context.Context, arg1 *databricks.GetUserInput) (*databricks.GetUserOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", arg0, arg1)
	ret0, _ := ret[0].(*databricks.GetUserOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser.
func (mr *MockAPIMockRecorder) GetUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockAPI)(nil).GetUser), arg0, arg1)
}

// GetUsers mocks base method.
func (m *MockAPI) GetUsers(arg0 context.Context, arg1 *databricks.GetUsersInput) (*databricks.GetUsersOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsers", arg0, arg1)
	ret0, _ := ret[0].(*databricks.GetUsersOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsers indicates an expected call of GetUsers.
func (mr *MockAPIMockRecorder) GetUsers(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsers", reflect.TypeOf((*MockAPI)(nil).GetUsers), arg0, arg1)
}

// GetWorkspaceConf mocks base method.
func (m *MockAPI) GetWorkspaceConf(arg0 context.Context) (*databricks.GetWorkspaceConfOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkspaceConf", arg0)
	ret0, _ := ret[0].(*databricks.GetWorkspaceConfOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkspaceConf indicates an expected call of GetWorkspaceConf.
func (mr *MockAPIMockRecorder) GetWorkspaceConf(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkspaceConf", reflect.TypeOf((*MockAPI)(nil).GetWorkspaceConf), arg0)
}

// InstallLibraries mocks base method.
func (m *MockAPI) InstallLibraries(arg0 context.Context, arg1 *databricks.InstallLibrariesInput) (*databricks.InstallLibrariesOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InstallLibraries", arg0, arg1)
	ret0, _ := ret[0].(*databricks.InstallLibrariesOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InstallLibraries indicates an expected call of InstallLibraries.
func (mr *MockAPIMockRecorder) InstallLibraries(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InstallLibraries", reflect.TypeOf((*MockAPI)(nil).InstallLibraries), arg0, arg1)
}

// ListCloudCredentials mocks base method.
func (m *MockAPI) ListCloudCredentials(arg0 context.Context) (*databricks.ListCredentialsOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCloudCredentials", arg0)
	ret0, _ := ret[0].(*databricks.ListCredentialsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCloudCredentials indicates an expected call of ListCloudCredentials.
func (mr *MockAPIMockRecorder) ListCloudCredentials(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCloudCredentials", reflect.TypeOf((*MockAPI)(nil).ListCloudCredentials), arg0)
}

// ListClusterPolicies mocks base method.
func (m *MockAPI) ListClusterPolicies(arg0 context.Context, arg1 *databricks.ListClusterPoliciesInput) (*databricks.ListClusterPoliciesOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListClusterPolicies", arg0, arg1)
	ret0, _ := ret[0].(*databricks.ListClusterPoliciesOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListClusterPolicies indicates an expected call of ListClusterPolicies.
func (mr *MockAPIMockRecorder) ListClusterPolicies(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListClusterPolicies", reflect.TypeOf((*MockAPI)(nil).ListClusterPolicies), arg0, arg1)
}

// ListClusters mocks base method.
func (m *MockAPI) ListClusters(arg0 context.Context, arg1 *databricks.ListClustersInput) (*databricks.ListClustersOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListClusters", arg0, arg1)
	ret0, _ := ret[0].(*databricks.ListClustersOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListClusters indicates an expected call of ListClusters.
func (mr *MockAPIMockRecorder) ListClusters(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListClusters", reflect.TypeOf((*MockAPI)(nil).ListClusters), arg0, arg1)
}

// ListClustersV2 mocks base method.
func (m *MockAPI) ListClustersV2(arg0 context.Context, arg1 *databricks.ListClustersInputV2) (*databricks.ListClustersOutputV2, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListClustersV2", arg0, arg1)
	ret0, _ := ret[0].(*databricks.ListClustersOutputV2)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListClustersV2 indicates an expected call of ListClustersV2.
func (mr *MockAPIMockRecorder) ListClustersV2(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListClustersV2", reflect.TypeOf((*MockAPI)(nil).ListClustersV2), arg0, arg1)
}

// ListCredentialPermissions mocks base method.
func (m *MockAPI) ListCredentialPermissions(arg0 context.Context, arg1 *databricks.ListCredentialPermissionsInput) (*databricks.PrivilegeAssignments, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCredentialPermissions", arg0, arg1)
	ret0, _ := ret[0].(*databricks.PrivilegeAssignments)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCredentialPermissions indicates an expected call of ListCredentialPermissions.
func (mr *MockAPIMockRecorder) ListCredentialPermissions(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCredentialPermissions", reflect.TypeOf((*MockAPI)(nil).ListCredentialPermissions), arg0, arg1)
}

// ListInstancePools mocks base method.
func (m *MockAPI) ListInstancePools(arg0 context.Context) (*databricks.ListInstancePoolsOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListInstancePools", arg0)
	ret0, _ := ret[0].(*databricks.ListInstancePoolsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListInstancePools indicates an expected call of ListInstancePools.
func (mr *MockAPIMockRecorder) ListInstancePools(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListInstancePools", reflect.TypeOf((*MockAPI)(nil).ListInstancePools), arg0)
}

// ListInstanceProfiles mocks base method.
func (m *MockAPI) ListInstanceProfiles(arg0 context.Context, arg1 *databricks.ListInstanceProfilesInput) (*databricks.ListInstanceProfilesOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListInstanceProfiles", arg0, arg1)
	ret0, _ := ret[0].(*databricks.ListInstanceProfilesOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListInstanceProfiles indicates an expected call of ListInstanceProfiles.
func (mr *MockAPIMockRecorder) ListInstanceProfiles(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListInstanceProfiles", reflect.TypeOf((*MockAPI)(nil).ListInstanceProfiles), arg0, arg1)
}

// ListJobs mocks base method.
func (m *MockAPI) ListJobs(arg0 context.Context, arg1 *databricks.ListJobsInput) (*databricks.ListJobsOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListJobs", arg0, arg1)
	ret0, _ := ret[0].(*databricks.ListJobsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListJobs indicates an expected call of ListJobs.
func (mr *MockAPIMockRecorder) ListJobs(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListJobs", reflect.TypeOf((*MockAPI)(nil).ListJobs), arg0, arg1)
}

// ListRuns mocks base method.
func (m *MockAPI) ListRuns(arg0 context.Context, arg1 *databricks.ListRunsInput) (*databricks.ListRunsOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRuns", arg0, arg1)
	ret0, _ := ret[0].(*databricks.ListRunsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRuns indicates an expected call of ListRuns.
func (mr *MockAPIMockRecorder) ListRuns(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRuns", reflect.TypeOf((*MockAPI)(nil).ListRuns), arg0, arg1)
}

// ListSqlQueryHistory mocks base method.
func (m *MockAPI) ListSqlQueryHistory(arg0 context.Context, arg1 *databricks.ListSqlQueryHistoryInput) (*databricks.ListSqlQueryHistoryOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSqlQueryHistory", arg0, arg1)
	ret0, _ := ret[0].(*databricks.ListSqlQueryHistoryOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSqlQueryHistory indicates an expected call of ListSqlQueryHistory.
func (mr *MockAPIMockRecorder) ListSqlQueryHistory(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSqlQueryHistory", reflect.TypeOf((*MockAPI)(nil).ListSqlQueryHistory), arg0, arg1)
}

// ListTokens mocks base method.
func (m *MockAPI) ListTokens(arg0 context.Context, arg1 *databricks.ListTokensInput) (*databricks.ListTokensOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTokens", arg0, arg1)
	ret0, _ := ret[0].(*databricks.ListTokensOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTokens indicates an expected call of ListTokens.
func (mr *MockAPIMockRecorder) ListTokens(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTokens", reflect.TypeOf((*MockAPI)(nil).ListTokens), arg0, arg1)
}

// Me mocks base method.
func (m *MockAPI) Me(arg0 context.Context, arg1 *databricks.MeInput) (*databricks.GetUserOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Me", arg0, arg1)
	ret0, _ := ret[0].(*databricks.GetUserOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Me indicates an expected call of Me.
func (mr *MockAPIMockRecorder) Me(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Me", reflect.TypeOf((*MockAPI)(nil).Me), arg0, arg1)
}

// PatchGroup mocks base method.
func (m *MockAPI) PatchGroup(arg0 context.Context, arg1 *databricks.PatchGroupInput) (*databricks.PatchGroupOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PatchGroup", arg0, arg1)
	ret0, _ := ret[0].(*databricks.PatchGroupOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PatchGroup indicates an expected call of PatchGroup.
func (mr *MockAPIMockRecorder) PatchGroup(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PatchGroup", reflect.TypeOf((*MockAPI)(nil).PatchGroup), arg0, arg1)
}

// PatchPermissions mocks base method.
func (m *MockAPI) PatchPermissions(arg0 context.Context, arg1 *databricks.PatchPermissionsInput) (*databricks.PatchPermissionsOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PatchPermissions", arg0, arg1)
	ret0, _ := ret[0].(*databricks.PatchPermissionsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PatchPermissions indicates an expected call of PatchPermissions.
func (mr *MockAPIMockRecorder) PatchPermissions(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PatchPermissions", reflect.TypeOf((*MockAPI)(nil).PatchPermissions), arg0, arg1)
}

// PatchUser mocks base method.
func (m *MockAPI) PatchUser(arg0 context.Context, arg1 *databricks.PatchUserInput) (*databricks.PatchUserOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PatchUser", arg0, arg1)
	ret0, _ := ret[0].(*databricks.PatchUserOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PatchUser indicates an expected call of PatchUser.
func (mr *MockAPIMockRecorder) PatchUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PatchUser", reflect.TypeOf((*MockAPI)(nil).PatchUser), arg0, arg1)
}

// PermanentlyDeleteCluster mocks base method.
func (m *MockAPI) PermanentlyDeleteCluster(arg0 context.Context, arg1 *databricks.PermanentlyDeleteClusterInput) (*databricks.PermanentlyDeleteClusterOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PermanentlyDeleteCluster", arg0, arg1)
	ret0, _ := ret[0].(*databricks.PermanentlyDeleteClusterOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PermanentlyDeleteCluster indicates an expected call of PermanentlyDeleteCluster.
func (mr *MockAPIMockRecorder) PermanentlyDeleteCluster(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PermanentlyDeleteCluster", reflect.TypeOf((*MockAPI)(nil).PermanentlyDeleteCluster), arg0, arg1)
}

// PinCluster mocks base method.
func (m *MockAPI) PinCluster(arg0 context.Context, arg1 *databricks.PinClusterInput) (*databricks.PinClusterOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PinCluster", arg0, arg1)
	ret0, _ := ret[0].(*databricks.PinClusterOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PinCluster indicates an expected call of PinCluster.
func (mr *MockAPIMockRecorder) PinCluster(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PinCluster", reflect.TypeOf((*MockAPI)(nil).PinCluster), arg0, arg1)
}

// PutPermissions mocks base method.
func (m *MockAPI) PutPermissions(arg0 context.Context, arg1 *databricks.PutPermissionsInput) (*databricks.PutPermissionsOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutPermissions", arg0, arg1)
	ret0, _ := ret[0].(*databricks.PutPermissionsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PutPermissions indicates an expected call of PutPermissions.
func (mr *MockAPIMockRecorder) PutPermissions(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutPermissions", reflect.TypeOf((*MockAPI)(nil).PutPermissions), arg0, arg1)
}

// RemoveInstanceProfile mocks base method.
func (m *MockAPI) RemoveInstanceProfile(arg0 context.Context, arg1 *databricks.RemoveInstanceProfileInput) (*databricks.RemoveInstanceProfileOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveInstanceProfile", arg0, arg1)
	ret0, _ := ret[0].(*databricks.RemoveInstanceProfileOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveInstanceProfile indicates an expected call of RemoveInstanceProfile.
func (mr *MockAPIMockRecorder) RemoveInstanceProfile(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveInstanceProfile", reflect.TypeOf((*MockAPI)(nil).RemoveInstanceProfile), arg0, arg1)
}

// RepairRun mocks base method.
func (m *MockAPI) RepairRun(arg0 context.Context, arg1 *databricks.RepairRunInput) (*databricks.RepairRunOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RepairRun", arg0, arg1)
	ret0, _ := ret[0].(*databricks.RepairRunOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RepairRun indicates an expected call of RepairRun.
func (mr *MockAPIMockRecorder) RepairRun(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RepairRun", reflect.TypeOf((*MockAPI)(nil).RepairRun), arg0, arg1)
}

// ResetJob mocks base method.
func (m *MockAPI) ResetJob(arg0 context.Context, arg1 *databricks.ResetJobInput) (*databricks.ResetJobOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetJob", arg0, arg1)
	ret0, _ := ret[0].(*databricks.ResetJobOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResetJob indicates an expected call of ResetJob.
func (mr *MockAPIMockRecorder) ResetJob(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetJob", reflect.TypeOf((*MockAPI)(nil).ResetJob), arg0, arg1)
}

// ResizeCluster mocks base method.
func (m *MockAPI) ResizeCluster(arg0 context.Context, arg1 *databricks.ResizeClusterInput) (*databricks.ResizeClusterOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResizeCluster", arg0, arg1)
	ret0, _ := ret[0].(*databricks.ResizeClusterOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResizeCluster indicates an expected call of ResizeCluster.
func (mr *MockAPIMockRecorder) ResizeCluster(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResizeCluster", reflect.TypeOf((*MockAPI)(nil).ResizeCluster), arg0, arg1)
}

// RunNow mocks base method.
func (m *MockAPI) RunNow(arg0 context.Context, arg1 *databricks.RunNowInput) (*databricks.RunNowOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunNow", arg0, arg1)
	ret0, _ := ret[0].(*databricks.RunNowOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RunNow indicates an expected call of RunNow.
func (mr *MockAPIMockRecorder) RunNow(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunNow", reflect.TypeOf((*MockAPI)(nil).RunNow), arg0, arg1)
}

// StartCluster mocks base method.
func (m *MockAPI) StartCluster(arg0 context.Context, arg1 *databricks.StartClusterInput) (*databricks.StartClusterOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartCluster", arg0, arg1)
	ret0, _ := ret[0].(*databricks.StartClusterOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StartCluster indicates an expected call of StartCluster.
func (mr *MockAPIMockRecorder) StartCluster(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartCluster", reflect.TypeOf((*MockAPI)(nil).StartCluster), arg0, arg1)
}

// SubmitRun mocks base method.
func (m *MockAPI) SubmitRun(arg0 context.Context, arg1 *databricks.SubmitRunInput) (*databricks.SubmitRunOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubmitRun", arg0, arg1)
	ret0, _ := ret[0].(*databricks.SubmitRunOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubmitRun indicates an expected call of SubmitRun.
func (mr *MockAPIMockRecorder) SubmitRun(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubmitRun", reflect.TypeOf((*MockAPI)(nil).SubmitRun), arg0, arg1)
}

// TerminateCluster mocks base method.
func (m *MockAPI) TerminateCluster(arg0 context.Context, arg1 *databricks.TerminateClusterInput) (*databricks.TerminateClusterOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TerminateCluster", arg0, arg1)
	ret0, _ := ret[0].(*databricks.TerminateClusterOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TerminateCluster indicates an expected call of TerminateCluster.
func (mr *MockAPIMockRecorder) TerminateCluster(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TerminateCluster", reflect.TypeOf((*MockAPI)(nil).TerminateCluster), arg0, arg1)
}

// UninstallLibraries mocks base method.
func (m *MockAPI) UninstallLibraries(arg0 context.Context, arg1 *databricks.UninstallLibrariesInput) (*databricks.UninstallLibrariesOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UninstallLibraries", arg0, arg1)
	ret0, _ := ret[0].(*databricks.UninstallLibrariesOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UninstallLibraries indicates an expected call of UninstallLibraries.
func (mr *MockAPIMockRecorder) UninstallLibraries(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UninstallLibraries", reflect.TypeOf((*MockAPI)(nil).UninstallLibraries), arg0, arg1)
}

// UnpinCluster mocks base method.
func (m *MockAPI) UnpinCluster(arg0 context.Context, arg1 *databricks.UnpinClusterInput) (*databricks.UnpinClusterOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnpinCluster", arg0, arg1)
	ret0, _ := ret[0].(*databricks.UnpinClusterOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UnpinCluster indicates an expected call of UnpinCluster.
func (mr *MockAPIMockRecorder) UnpinCluster(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnpinCluster", reflect.TypeOf((*MockAPI)(nil).UnpinCluster), arg0, arg1)
}

// UpdateJob mocks base method.
func (m *MockAPI) UpdateJob(arg0 context.Context, arg1 *databricks.UpdateJobInput) (*databricks.UpdateJobOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateJob", arg0, arg1)
	ret0, _ := ret[0].(*databricks.UpdateJobOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateJob indicates an expected call of UpdateJob.
func (mr *MockAPIMockRecorder) UpdateJob(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateJob", reflect.TypeOf((*MockAPI)(nil).UpdateJob), arg0, arg1)
}

// WorkspaceDelete mocks base method.
func (m *MockAPI) WorkspaceDelete(arg0 context.Context, arg1 *databricks.WorkspaceDeleteInput) (*databricks.WorkspaceDeleteOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WorkspaceDelete", arg0, arg1)
	ret0, _ := ret[0].(*databricks.WorkspaceDeleteOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WorkspaceDelete indicates an expected call of WorkspaceDelete.
func (mr *MockAPIMockRecorder) WorkspaceDelete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WorkspaceDelete", reflect.TypeOf((*MockAPI)(nil).WorkspaceDelete), arg0, arg1)
}

// WorkspaceExport mocks base method.
func (m *MockAPI) WorkspaceExport(arg0 context.Context, arg1 *databricks.WorkspaceExportInput) (*databricks.WorkspaceExportOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WorkspaceExport", arg0, arg1)
	ret0, _ := ret[0].(*databricks.WorkspaceExportOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WorkspaceExport indicates an expected call of WorkspaceExport.
func (mr *MockAPIMockRecorder) WorkspaceExport(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WorkspaceExport", reflect.TypeOf((*MockAPI)(nil).WorkspaceExport), arg0, arg1)
}

// WorkspaceGetStatus mocks base method.
func (m *MockAPI) WorkspaceGetStatus(arg0 context.Context, arg1 *databricks.WorkspaceGetStatusInput) (*databricks.WorkspaceGetStatusOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WorkspaceGetStatus", arg0, arg1)
	ret0, _ := ret[0].(*databricks.WorkspaceGetStatusOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WorkspaceGetStatus indicates an expected call of WorkspaceGetStatus.
func (mr *MockAPIMockRecorder) WorkspaceGetStatus(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WorkspaceGetStatus", reflect.TypeOf((*MockAPI)(nil).WorkspaceGetStatus), arg0, arg1)
}

// WorkspaceImport mocks base method.
func (m *MockAPI) WorkspaceImport(arg0 context.Context, arg1 *databricks.WorkspaceImportInput) (*databricks.WorkspaceImportOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WorkspaceImport", arg0, arg1)
	ret0, _ := ret[0].(*databricks.WorkspaceImportOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WorkspaceImport indicates an expected call of WorkspaceImport.
func (mr *MockAPIMockRecorder) WorkspaceImport(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WorkspaceImport", reflect.TypeOf((*MockAPI)(nil).WorkspaceImport), arg0, arg1)
}

// WorkspaceList mocks base method.
func (m *MockAPI) WorkspaceList(arg0 context.Context, arg1 *databricks.WorkspaceListInput) (*databricks.WorkspaceListOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WorkspaceList", arg0, arg1)
	ret0, _ := ret[0].(*databricks.WorkspaceListOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WorkspaceList indicates an expected call of WorkspaceList.
func (mr *MockAPIMockRecorder) WorkspaceList(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WorkspaceList", reflect.TypeOf((*MockAPI)(nil).WorkspaceList), arg0, arg1)
}

// WorkspaceMkdirs mocks base method.
func (m *MockAPI) WorkspaceMkdirs(arg0 context.Context, arg1 *databricks.WorkspaceMkdirsInput) (*databricks.WorkspaceMkdirsOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WorkspaceMkdirs", arg0, arg1)
	ret0, _ := ret[0].(*databricks.WorkspaceMkdirsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WorkspaceMkdirs indicates an expected call of WorkspaceMkdirs.
func (mr *MockAPIMockRecorder) WorkspaceMkdirs(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WorkspaceMkdirs", reflect.TypeOf((*MockAPI)(nil).WorkspaceMkdirs), arg0, arg1)
}
