`_timestamp` TIMESTAMP,
`_filename` STRING,
`_rowid` STRING,
`_op` STRING,
`org_id` BIGINT,
`uuid` STRING,
`subscriber_id` STRING,
`notification_type` INT,
`is_active` BYTE,
`details` STRUCT<`org_id`: BIGINT>,
`_raw_details` STRING,
`last_notification_sent_at` TIMESTAMP,
`created_at` TIMESTAMP,
`updated_at` TIMESTAMP,
`partition` STRING
