`_timestamp` TIMESTAMP,
`_filename` STRING,
`_rowid` STRING,
`_op` STRING,
`org_id` BIGINT,
`operator_id` BIGINT,
`org_timezone_day` DATE,
`subintervals_list` STRING,
`total_distance_meters` DECIMAL(12, 2),
`total_engage_duration_ms` INT,
`total_idle_duration_ms` INT,
`total_unproductive_idle_duration_ms` INT,
`cost_currency` STRING,
`score` DECIMAL(5, 2),
`total_efficiency_l_per_100km` DECIMAL(6, 3),
`engine_engage_efficiency_l_per_100km` DECIMAL(6, 3),
`unproductive_idling_opportunity_ml` INT,
`hard_acceleration_opportunity_min_ml` INT,
`hard_acceleration_opportunity_max_ml` INT,
`speeding_opportunity_min_ml` INT,
`speeding_opportunity_max_ml` INT,
`cruise_control_opportunity_min_ml` INT,
`cruise_control_opportunity_max_ml` INT,
`hard_acceleration_opportunity_context` STRING,
`speeding_opportunity_context` STRING,
`cruise_control_opportunity_context` STRING,
`highway_percentage` DECIMAL(5, 2),
`uphill_downhill_percentage` DECIMAL(5, 2),
`vehicle_weight_kg` DECIMAL(10, 2),
`benchmark_efficiency_l_per_100km` DECIMAL(6, 3),
`created_at` TIMESTAMP,
`updated_at` TIMESTAMP,
`engage_fuel_consumed_ml` DOUBLE,
`engage_fuel_cost_cents` BIGINT,
`engage_fuel_emissions_c_o2_grams` DOUBLE,
`productive_idling_fuel_consumed_ml` DOUBLE,
`productive_idling_fuel_cost_cents` BIGINT,
`productive_idling_fuel_emissions_c_o2_grams` DOUBLE,
`unproductive_idling_fuel_consumed_ml` DOUBLE,
`unproductive_idling_fuel_cost_cents` BIGINT,
`unproductive_idling_fuel_emissions_c_o2_grams` DOUBLE,
`device_id_count_map` STRING,
`total_benchmark_efficiency_l_per_100km` DECIMAL(6, 3),
`unproductive_idling_opportunity_cost_cents` BIGINT,
`hard_acceleration_opportunity_cost_cents` BIGINT,
`speeding_opportunity_cost_cents` BIGINT,
`cruise_control_opportunity_cost_cents` BIGINT,
`date` STRING
