`_timestamp` TIMESTAMP,
`_filename` STRING,
`_rowid` STRING,
`_op` STRING,
`uuid` STRING,
`org_id` BIGINT,
`device_id` BIGINT,
`operator_id` BIGINT,
`start_ms` BIGINT,
`duration_ms` BIGINT,
`enrichment_due_at` TIMESTAMP,
`last_enriched_at` TIMESTAMP,
`total_engage_duration_ms` BIGINT,
`total_idle_duration_ms` BIGINT,
`total_unproductive_idle_duration_ms` BIGINT,
`cost_currency` STRING,
`total_distance_meters` DOUBLE,
`subintervals_list` STRING,
`created_at` TIMESTAMP,
`updated_at` TIMESTAMP,
`deleted_at` TIMESTAMP,
`score` INT,
`total_efficiency_l_per_100km` DECIMAL(6, 3),
`engine_engage_efficiency_l_per_100km` DECIMAL(6, 3),
`unproductive_idling_opportunity_ml` BIGINT,
`hard_acceleration_opportunity_min_ml` BIGINT,
`hard_acceleration_opportunity_max_ml` BIGINT,
`speeding_opportunity_min_ml` BIGINT,
`speeding_opportunity_max_ml` BIGINT,
`cruise_control_opportunity_min_ml` BIGINT,
`cruise_control_opportunity_max_ml` BIGINT,
`fuel_price_usd_per_l` DECIMAL(5, 2),
`highway_percentage` DECIMAL(5, 2),
`uphill_downhill_percentage` DECIMAL(5, 2),
`benchmark_efficiency_l_per_100km` DECIMAL(6, 3),
`pending_fuel_distance` BYTE,
`engage_fuel_consumed_ml` DOUBLE,
`engage_fuel_cost_cents` BIGINT,
`engage_fuel_emissions_c_o2_grams` DOUBLE,
`productive_idling_fuel_consumed_ml` DOUBLE,
`productive_idling_fuel_cost_cents` BIGINT,
`productive_idling_fuel_emissions_c_o2_grams` DOUBLE,
`unproductive_idling_fuel_consumed_ml` DOUBLE,
`unproductive_idling_fuel_cost_cents` BIGINT,
`unproductive_idling_fuel_emissions_c_o2_grams` DOUBLE,
`vehicle_weight_kg` DECIMAL(10, 2),
`total_benchmark_efficiency_l_per_100km` DECIMAL(6, 3),
`unproductive_idling_opportunity_cost_cents` BIGINT,
`hard_acceleration_opportunity_cost_cents` BIGINT,
`speeding_opportunity_cost_cents` BIGINT,
`cruise_control_opportunity_cost_cents` BIGINT,
`date` STRING
