`_timestamp` TIMESTAMP,
`_filename` STRING,
`_rowid` STRING,
`_op` STRING,
`uuid` STRING,
`org_id` BIGINT,
`effective_from` TIMESTAMP,
`created_at` TIMESTAMP,
`updated_at` TIMESTAMP,
`expense_config_uuid` STRING,
`category_uuid` STRING,
`name` STRING,
`description` STRING,
`allowance_in_cents` INT,
`conditions` STRING,
`international_premium_percent` DECIMAL(5, 2),
`deleted_at` TIMESTAMP,
`partition` STRING
