`_timestamp` TIMESTAMP,
`_filename` STRING,
`_rowid` STRING,
`_op` STRING,
`org_id` BIGINT,
`asset_label_uuid` STRING,
`asset_label_key_uuid` STRING,
`dynamic_dashboard_uuid` STRING,
`partition` STRING
