`_timestamp` TIMESTAMP,
`_filename` STRING,
`_rowid` STRING,
`_op` STRING,
`org_id` BIGINT,
`uuid` STRING,
`asset_job_uuid` STRING,
`start_ms` BIGINT,
`end_ms` BIGINT,
`asset_id` BIGINT,
`job_item_proto` STRUCT<
  `tag_ids`: ARRAY<BIGINT>
>,
`_raw_job_item_proto` STRING,
`created_at` TIMESTAMP,
`updated_at` TIMESTAMP,
`industrial_asset_uuid` STRING,
`assigned_ancestor_industrial_asset_uuid` STRING,
`date` STRING
