`_timestamp` TIMESTAMP,
`_filename` STRING,
`_rowid` STRING,
`_op` STRING,
`id` BIGINT,
`org_id` BIGINT,
`oem_type` BIGINT,
`auth_data` STRUCT<`encoded_string`: STRING>,
`_raw_auth_data` STRING,
`user_id` BIGINT,
`created_at` TIMESTAMP,
`updated_at` TIMESTAMP,
`name` STRING,
`partition` STRING
