`_timestamp` TIMESTAMP,
`_filename` STRING,
`_rowid` STRING,
`_op` STRING,
`org_id` BIGINT,
`uuid` STRING,
`planner_uuid` STRING,
`created_at` TIMESTAMP,
`created_by` BIGINT,
`updated_by` BIGINT,
`updated_at` TIMESTAMP,
`server_deleted_at` TIMESTAMP,
`server_deleted_by` BIGINT,
`name` STRING,
`time_of_day_start_seconds` BIGINT,
`additional_service_time_enabled` BYTE,
`additional_service_time_seconds` BIGINT,
`restriction_commercial_roads_only_enabled` BYTE,
`restriction_vehicle_weight_enabled` BYTE,
`restriction_vehicle_weight_kilograms` DOUBLE,
`restriction_vehicle_height_enabled` BYTE,
`restriction_vehicle_height_meters` DOUBLE,
`restriction_vehicle_width_enabled` BYTE,
`restriction_vehicle_width_meters` DOUBLE,
`restriction_vehicle_length_enabled` BYTE,
`restriction_vehicle_length_meters` DOUBLE,
`restriction_speed_cap_enabled` BYTE,
`restriction_speed_cap_kmph` DOUBLE,
`restriction_speed_factor_enabled` BYTE,
`restriction_speed_factor` DOUBLE,
`restriction_max_shift_time_enabled` BYTE,
`restriction_max_shift_time_seconds` BIGINT,
`restriction_min_stop_count_enabled` BYTE,
`restriction_min_stop_count` BIGINT,
`restriction_max_stop_count_enabled` BYTE,
`restriction_max_stop_count` BIGINT,
`restriction_max_distance_enabled` BYTE,
`restriction_max_distance_meters` BIGINT,
`restriction_min_distance_enabled` BYTE,
`restriction_min_distance_meters` BIGINT,
`capacity0` DOUBLE,
`capacity1` DOUBLE,
`capacity2` DOUBLE,
`capacity3` DOUBLE,
`capacity4` DOUBLE,
`protos` STRUCT<
  `driver_breaks`: ARRAY<
    STRUCT<
      `duration_seconds`: DECIMAL(20, 0),
      `window_offset_start_ms`: DECIMAL(20, 0),
      `window_offset_end_ms`: DECIMAL(20, 0),
      `type`: INT,
      `id`: BIGINT
    >
  >,
  `rest_time_config`: STRUCT<
    `enabled`: BOOLEAN,
    `duration_seconds`: DECIMAL(20, 0),
    `interval_seconds`: DECIMAL(20, 0)
  >,
  `restriction_shipped_hazardous_goods`: STRUCT<
    `enabled`: BOOLEAN,
    `explosive`: BOOLEAN,
    `gas`: BOOLEAN,
    `flammable`: BOOLEAN,
    `combustible`: BOOLEAN,
    `organic`: BOOLEAN,
    `poison`: BOOLEAN,
    `radioactive`: BOOLEAN,
    `corrosive`: BOOLEAN,
    `poisonous_inhalation`: BOOLEAN,
    `harmful_to_water`: BOOLEAN
  >,
  `provided_skill_uuids`: ARRAY<BINARY>,
  `duty_rule_config`: STRUCT<
    `enabled`: BOOLEAN,
    `min_off_time_seconds`: DECIMAL(20, 0),
    `max_driving_time_seconds`: DECIMAL(20, 0),
    `max_working_time_seconds`: DECIMAL(20, 0)
  >
>,
`_raw_protos` STRING,
`restriction_no_uturns_enabled` BYTE,
`restriction_no_difficult_turns_enabled` BYTE,
`restriction_no_toll_roads_enabled` BYTE,
`restriction_no_ferries_enabled` BYTE,
`restriction_no_highways_enabled` BYTE,
`restriction_no_controlled_access_highways_enabled` BYTE,
`cost_fixed` DOUBLE,
`cost_per_meter` DOUBLE,
`cost_per_second` DOUBLE,
`category` INT,
`partition` STRING
