`_timestamp` TIMESTAMP,
`_filename` STRING,
`_rowid` STRING,
`_op` STRING,
`org_id` BIGINT,
`uuid` STRING,
`planner_uuid` STRING,
`planner_session_uuid` STRING,
`planner_session_route_uuid` STRING,
`planner_session_route_stop_uuid` STRING,
`created_at` TIMESTAMP,
`created_by` BIGINT,
`updated_by` BIGINT,
`updated_at` TIMESTAMP,
`server_deleted_at` TIMESTAMP,
`server_deleted_by` BIGINT,
`id` STRING,
`special_instructions` STRING,
`service_window_start` TIMESTAMP,
`service_window_end` TIMESTAMP,
`additional_service_time_seconds` BIGINT,
`address` STRING,
`lat` DOUBLE,
`lng` DOUBLE,
`quantities0` DOUBLE,
`quantities1` DOUBLE,
`quantities2` DOUBLE,
`quantities3` DOUBLE,
`quantities4` DOUBLE,
`planner_location_uuid` STRING,
`location_external_id` STRING,
`error_messages_json` STRING,
`protos` STRUCT<
  `required_skill_uuids`: ARRAY<BINARY>,
  `order_position`: INT,
  `order_priority`: BIGINT,
  `customer_properties`: ARRAY<
    STRUCT<
      `uuid`: BINARY,
      `value`: STRING
    >
  >
>,
`_raw_protos` STRING,
`task_type` INT,
`sub_id` STRING,
`address_id` BIGINT,
`partition` STRING
