`_timestamp` TIMESTAMP,
`_filename` STRING,
`_rowid` STRING,
`_op` STRING,
`org_id` BIGINT,
`device_id` BIGINT,
`event_ms` BIGINT,
`has_multiple_orientations` BYTE,
`classifier_version` SHORT,
`detail_proto` STRUCT<`max_mag_accel_x`: FLOAT>,
`_raw_detail_proto` STRING,
`date` STRING
