`_timestamp` TIMESTAMP,
`_filename` STRING,
`_rowid` STRING,
`_op` STRING,
`id` BIGINT,
`org_id` BIGINT,
`group_id` BIGINT,
`vehicle_id` BIGINT,
`driver_id` BIGINT,
`log_at` TIMESTAMP,
`created_at` TIMESTAMP,
`updated_at` TIMESTAMP,
`odometer_meters` BIGINT,
`trailer_name` STRING,
`defects_need_correction` BYTE,
`driver_signed_at` TIMESTAMP,
`mechanic_signed_at` TIMESTAMP,
`inspection_type` INT,
`defects_corrected` BYTE,
`defects_ignored` BYTE,
`mechanic_notes` STRING,
`author_user_id` BIGINT,
`next_safe_dvir_driver_id` BIGINT,
`next_safe_dvir_user_id` BIGINT,
`next_safe_dvir_signed_at` TIMESTAMP,
`next_safe_dvir_id` BIGINT,
`next_driver_id` BIGINT,
`next_driver_signed_at` TIMESTAMP,
`next_driver_dvir_id` BIGINT,
`proto` STRUCT<
  `walkaround_photos`: ARRAY<
    STRUCT<
      `uuid`: STRING,
      `name`: STRING,
      `created_at_ms`: STRING,
      `org_id`: BIGINT
    >
  >,
  `height_info`: STRUCT<
    `height_meters`: FLOAT,
    `height_adjustment_reason`: INT,
    `height_adjustment_comment`: STRING
  >
>,
`_raw_proto` STRING,
`dvir_type` STRING,
`deprecated_trailer_id` BIGINT,
`vin` STRING,
`dvir_template_uuid` STRING,
`dvir_template_version` INT,
`license_plate` STRING,
`latitude` DOUBLE,
`longitude` DOUBLE,
`address` STRING,
`trailer_device_id` BIGINT,
`server_created_at` TIMESTAMP,
`date` STRING
