// Code generated by featureconfigcompiler; DO NOT EDIT.
package featureconfigs

import (
	"context"

	"samsaradev.io/infra/releasemanagement/featureconfig"
)

var Definitions = struct{
	EnableEmrSqsWorkerQueryEmrData featureconfig.TypedDefinition[bool]
}{}

func init() {
	Definitions.EnableEmrSqsWorkerQueryEmrData = featureconfig.CreateFeatureConfigDefinitionBool("enable-emr-sqs-worker-query-emr-data", false)
}

func EnableEmrSqsWorkerQueryEmrData(ctx context.Context, evaluator featureconfig.Evaluator, orgId int64, optionalArgs... featureconfig.OptionalEvaluationArgument) (bool, error) {
	var options []featureconfig.OptionalEvaluationArgument

	options = append(options, optionalArgs...)

	return featureconfig.RetrieveValue(ctx, evaluator, orgId, Definitions.EnableEmrSqsWorkerQueryEmrData, options...)
}

