// Code generated by MockGen. DO NOT EDIT.
// Source: samsaradev.io/infra/dataplatform/ksdeltalake/difftool/allserieslister (interfaces: AllSeriesListerClient)

// Package mock_allserieslister is a generated GoMock package.
package mock_allserieslister

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	grpc "google.golang.org/grpc"

	kinesisstatsproto "samsaradev.io/stats/kinesisstats/kinesisstatsproto"
)

// MockAllSeriesListerClient is a mock of AllSeriesListerClient interface.
type MockAllSeriesListerClient struct {
	ctrl     *gomock.Controller
	recorder *MockAllSeriesListerClientMockRecorder
}

// MockAllSeriesListerClientMockRecorder is the mock recorder for MockAllSeriesListerClient.
type MockAllSeriesListerClientMockRecorder struct {
	mock *MockAllSeriesListerClient
}

// NewMockAllSeriesListerClient creates a new mock instance.
func NewMockAllSeriesListerClient(ctrl *gomock.Controller) *MockAllSeriesListerClient {
	mock := &MockAllSeriesListerClient{ctrl: ctrl}
	mock.recorder = &MockAllSeriesListerClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAllSeriesListerClient) EXPECT() *MockAllSeriesListerClientMockRecorder {
	return m.recorder
}

// GetSeriesWithTimeMs mocks base method.
func (m *MockAllSeriesListerClient) GetSeriesWithTimeMs(arg0 context.Context, arg1 *kinesisstatsproto.GetSeriesRequest, arg2 ...grpc.CallOption) (*kinesisstatsproto.GetSeriesWithTimeMsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetSeriesWithTimeMs", varargs...)
	ret0, _ := ret[0].(*kinesisstatsproto.GetSeriesWithTimeMsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSeriesWithTimeMs indicates an expected call of GetSeriesWithTimeMs.
func (mr *MockAllSeriesListerClientMockRecorder) GetSeriesWithTimeMs(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSeriesWithTimeMs", reflect.TypeOf((*MockAllSeriesListerClient)(nil).GetSeriesWithTimeMs), varargs...)
}
