// Code generated by generate_db_boilerplate. DO NOT EDIT.

package main

import (
	"samsaradev.io/infra/config"
	"samsaradev.io/infra/config/databaseconfig"
	"samsaradev.io/infra/dbtools/dbconfighelpers"
)

func getDbToConfigMap(c *config.AppConfig) map[string]func() databaseconfig.DatabaseConfig {
	return map[string]func() databaseconfig.DatabaseConfig{
		"cloud": c.GetCloudDatabaseConfig,
		"stats": func() databaseconfig.DatabaseConfig {
			return dbconfighelpers.GetStatsDatabaseConfigForCurrentClusterAndApp(c)
		},
		"alerts": func() databaseconfig.DatabaseConfig {
			return dbconfighelpers.GetAlertsDatabaseConfigForCurrentClusterAndApp(c)
		},
		"deploy": func() databaseconfig.DatabaseConfig {
			return dbconfighelpers.GetDeployDatabaseConfigForCurrentClusterAndApp(c)
		},
		"encryptionkey": func() databaseconfig.DatabaseConfig {
			return dbconfighelpers.GetEncryptionkeyDatabaseConfigForCurrentClusterAndApp(c)
		},
		"evmetadata": func() databaseconfig.DatabaseConfig {
			return dbconfighelpers.GetEvmetadataDatabaseConfigForCurrentClusterAndApp(c)
		},
		"finops": func() databaseconfig.DatabaseConfig {
			return dbconfighelpers.GetFinopsDatabaseConfigForCurrentClusterAndApp(c)
		},
		"firmware": func() databaseconfig.DatabaseConfig {
			return dbconfighelpers.GetFirmwareDatabaseConfigForCurrentClusterAndApp(c)
		},
		"fuelcardintegrations": func() databaseconfig.DatabaseConfig {
			return dbconfighelpers.GetFuelcardintegrationsDatabaseConfigForCurrentClusterAndApp(c)
		},
		"internal": func() databaseconfig.DatabaseConfig {
			return dbconfighelpers.GetInternalDatabaseConfigForCurrentClusterAndApp(c)
		},
		"licenseentity": func() databaseconfig.DatabaseConfig {
			return dbconfighelpers.GetLicenseentityDatabaseConfigForCurrentClusterAndApp(c)
		},
		"locale": func() databaseconfig.DatabaseConfig {
			return dbconfighelpers.GetLocaleDatabaseConfigForCurrentClusterAndApp(c)
		},
		"metafleets": func() databaseconfig.DatabaseConfig {
			return dbconfighelpers.GetMetafleetsDatabaseConfigForCurrentClusterAndApp(c)
		},
		"oemexternal": func() databaseconfig.DatabaseConfig {
			return dbconfighelpers.GetOemexternalDatabaseConfigForCurrentClusterAndApp(c)
		},
		"products": func() databaseconfig.DatabaseConfig {
			return dbconfighelpers.GetProductsDatabaseConfigForCurrentClusterAndApp(c)
		},
		"safetyeventreview": func() databaseconfig.DatabaseConfig {
			return dbconfighelpers.GetSafetyeventreviewDatabaseConfigForCurrentClusterAndApp(c)
		},
		"sessions": func() databaseconfig.DatabaseConfig {
			return dbconfighelpers.GetSessionsDatabaseConfigForCurrentClusterAndApp(c)
		},
		"signalpromotion": func() databaseconfig.DatabaseConfig {
			return dbconfighelpers.GetSignalpromotionDatabaseConfigForCurrentClusterAndApp(c)
		},
		"sitesunsharded": func() databaseconfig.DatabaseConfig {
			return dbconfighelpers.GetSitesunshardedDatabaseConfigForCurrentClusterAndApp(c)
		},
		"speedlimits": func() databaseconfig.DatabaseConfig {
			return dbconfighelpers.GetSpeedlimitsDatabaseConfigForCurrentClusterAndApp(c)
		},
		"userpreferences": func() databaseconfig.DatabaseConfig {
			return dbconfighelpers.GetUserpreferencesDatabaseConfigForCurrentClusterAndApp(c)
		},
	}
}

func getDbToShardedConfigMap(c *config.AppConfig) map[string]func() databaseconfig.GeneratedShardedDatabaseConfig {
	return map[string]func() databaseconfig.GeneratedShardedDatabaseConfig{
		"activations": func() databaseconfig.GeneratedShardedDatabaseConfig {
			return dbconfighelpers.GetShardedActivationsConfigForCurrentClusterAndApp(c)
		},
		"agent": func() databaseconfig.GeneratedShardedDatabaseConfig {
			return dbconfighelpers.GetShardedAgentConfigForCurrentClusterAndApp(c)
		},
		"api2": func() databaseconfig.GeneratedShardedDatabaseConfig {
			return dbconfighelpers.GetShardedApi2ConfigForCurrentClusterAndApp(c)
		},
		"associations": func() databaseconfig.GeneratedShardedDatabaseConfig {
			return dbconfighelpers.GetShardedAssociationsConfigForCurrentClusterAndApp(c)
		},
		"attribute": func() databaseconfig.GeneratedShardedDatabaseConfig {
			return dbconfighelpers.GetShardedAttributeConfigForCurrentClusterAndApp(c)
		},
		"audits": func() databaseconfig.GeneratedShardedDatabaseConfig {
			return dbconfighelpers.GetShardedAuditsConfigForCurrentClusterAndApp(c)
		},
		"cmassets": func() databaseconfig.GeneratedShardedDatabaseConfig {
			return dbconfighelpers.GetShardedCmassetsConfigForCurrentClusterAndApp(c)
		},
		"coaching": func() databaseconfig.GeneratedShardedDatabaseConfig {
			return dbconfighelpers.GetShardedCoachingConfigForCurrentClusterAndApp(c)
		},
		"compliance": func() databaseconfig.GeneratedShardedDatabaseConfig {
			return dbconfighelpers.GetShardedComplianceConfigForCurrentClusterAndApp(c)
		},
		"compliancemonitor": func() databaseconfig.GeneratedShardedDatabaseConfig {
			return dbconfighelpers.GetShardedCompliancemonitorConfigForCurrentClusterAndApp(c)
		},
		"csvuploads": func() databaseconfig.GeneratedShardedDatabaseConfig {
			return dbconfighelpers.GetShardedCsvuploadsConfigForCurrentClusterAndApp(c)
		},
		"dataplatformtestinternal": func() databaseconfig.GeneratedShardedDatabaseConfig {
			return dbconfighelpers.GetShardedDataplatformtestinternalConfigForCurrentClusterAndApp(c)
		},
		"datastoragetest": func() databaseconfig.GeneratedShardedDatabaseConfig {
			return dbconfighelpers.GetShardedDatastoragetestConfigForCurrentClusterAndApp(c)
		},
		"detention": func() databaseconfig.GeneratedShardedDatabaseConfig {
			return dbconfighelpers.GetShardedDetentionConfigForCurrentClusterAndApp(c)
		},
		"developers": func() databaseconfig.GeneratedShardedDatabaseConfig {
			return dbconfighelpers.GetShardedDevelopersConfigForCurrentClusterAndApp(c)
		},
		"deviceassociations": func() databaseconfig.GeneratedShardedDatabaseConfig {
			return dbconfighelpers.GetShardedDeviceassociationsConfigForCurrentClusterAndApp(c)
		},
		"devicemetadata": func() databaseconfig.GeneratedShardedDatabaseConfig {
			return dbconfighelpers.GetShardedDevicemetadataConfigForCurrentClusterAndApp(c)
		},
		"dispatch": func() databaseconfig.GeneratedShardedDatabaseConfig {
			return dbconfighelpers.GetShardedDispatchConfigForCurrentClusterAndApp(c)
		},
		"driverassignments": func() databaseconfig.GeneratedShardedDatabaseConfig {
			return dbconfighelpers.GetShardedDriverassignmentsConfigForCurrentClusterAndApp(c)
		},
		"driverdocuments": func() databaseconfig.GeneratedShardedDatabaseConfig {
			return dbconfighelpers.GetShardedDriverDocumentsConfigForCurrentClusterAndApp(c)
		},
		"driverqualifications": func() databaseconfig.GeneratedShardedDatabaseConfig {
			return dbconfighelpers.GetShardedDriverqualificationsConfigForCurrentClusterAndApp(c)
		},
		"dvirs2": func() databaseconfig.GeneratedShardedDatabaseConfig {
			return dbconfighelpers.GetShardedDvirs2ConfigForCurrentClusterAndApp(c)
		},
		"ecodriving": func() databaseconfig.GeneratedShardedDatabaseConfig {
			return dbconfighelpers.GetShardedEcodrivingConfigForCurrentClusterAndApp(c)
		},
		"eldevents": func() databaseconfig.GeneratedShardedDatabaseConfig {
			return dbconfighelpers.GetShardedEldeventsConfigForCurrentClusterAndApp(c)
		},
		"eldhos": func() databaseconfig.GeneratedShardedDatabaseConfig {
			return dbconfighelpers.GetShardedEldhosConfigForCurrentClusterAndApp(c)
		},
		"emissionsreporting": func() databaseconfig.GeneratedShardedDatabaseConfig {
			return dbconfighelpers.GetShardedEmissionsreportingConfigForCurrentClusterAndApp(c)
		},
		"engineactivity": func() databaseconfig.GeneratedShardedDatabaseConfig {
			return dbconfighelpers.GetShardedEngineactivityConfigForCurrentClusterAndApp(c)
		},
		"eucompliance": func() databaseconfig.GeneratedShardedDatabaseConfig {
			return dbconfighelpers.GetShardedEucomplianceConfigForCurrentClusterAndApp(c)
		},
		"eurofleet": func() databaseconfig.GeneratedShardedDatabaseConfig {
			return dbconfighelpers.GetShardedEurofleetConfigForCurrentClusterAndApp(c)
		},
		"ev": func() databaseconfig.GeneratedShardedDatabaseConfig {
			return dbconfighelpers.GetShardedEvConfigForCurrentClusterAndApp(c)
		},
		"forms": func() databaseconfig.GeneratedShardedDatabaseConfig {
			return dbconfighelpers.GetShardedFormsConfigForCurrentClusterAndApp(c)
		},
		"fuel": func() databaseconfig.GeneratedShardedDatabaseConfig {
			return dbconfighelpers.GetShardedFuelConfigForCurrentClusterAndApp(c)
		},
		"fuelcards": func() databaseconfig.GeneratedShardedDatabaseConfig {
			return dbconfighelpers.GetShardedFuelcardsConfigForCurrentClusterAndApp(c)
		},
		"geoevents": func() databaseconfig.GeneratedShardedDatabaseConfig {
			return dbconfighelpers.GetShardedGeoeventsConfigForCurrentClusterAndApp(c)
		},
		"inbox": func() databaseconfig.GeneratedShardedDatabaseConfig {
			return dbconfighelpers.GetShardedInboxConfigForCurrentClusterAndApp(c)
		},
		"industrialcore": func() databaseconfig.GeneratedShardedDatabaseConfig {
			return dbconfighelpers.GetShardedIndustrialcoreConfigForCurrentClusterAndApp(c)
		},
		"industrialvision": func() databaseconfig.GeneratedShardedDatabaseConfig {
			return dbconfighelpers.GetShardedIndustrialvisionConfigForCurrentClusterAndApp(c)
		},
		"integrations": func() databaseconfig.GeneratedShardedDatabaseConfig {
			return dbconfighelpers.GetShardedIntegrationsConfigForCurrentClusterAndApp(c)
		},
		"jobschedules": func() databaseconfig.GeneratedShardedDatabaseConfig {
			return dbconfighelpers.GetShardedJobschedulesConfigForCurrentClusterAndApp(c)
		},
		"maintenance": func() databaseconfig.GeneratedShardedDatabaseConfig {
			return dbconfighelpers.GetShardedMaintenanceConfigForCurrentClusterAndApp(c)
		},
		"mapedits": func() databaseconfig.GeneratedShardedDatabaseConfig {
			return dbconfighelpers.GetShardedMapeditsConfigForCurrentClusterAndApp(c)
		},
		"mdm": func() databaseconfig.GeneratedShardedDatabaseConfig {
			return dbconfighelpers.GetShardedMdmConfigForCurrentClusterAndApp(c)
		},
		"mediacatalog": func() databaseconfig.GeneratedShardedDatabaseConfig {
			return dbconfighelpers.GetShardedMediacatalogConfigForCurrentClusterAndApp(c)
		},
		"messages": func() databaseconfig.GeneratedShardedDatabaseConfig {
			return dbconfighelpers.GetShardedMessagesConfigForCurrentClusterAndApp(c)
		},
		"mobile": func() databaseconfig.GeneratedShardedDatabaseConfig {
			return dbconfighelpers.GetShardedMobileConfigForCurrentClusterAndApp(c)
		},
		"navigation": func() databaseconfig.GeneratedShardedDatabaseConfig {
			return dbconfighelpers.GetShardedNavigationConfigForCurrentClusterAndApp(c)
		},
		"notes": func() databaseconfig.GeneratedShardedDatabaseConfig {
			return dbconfighelpers.GetShardedNotesConfigForCurrentClusterAndApp(c)
		},
		"notifications": func() databaseconfig.GeneratedShardedDatabaseConfig {
			return dbconfighelpers.GetShardedNotificationsConfigForCurrentClusterAndApp(c)
		},
		"oauth2": func() databaseconfig.GeneratedShardedDatabaseConfig {
			return dbconfighelpers.GetShardedOauth2ConfigForCurrentClusterAndApp(c)
		},
		"oem": func() databaseconfig.GeneratedShardedDatabaseConfig {
			return dbconfighelpers.GetShardedOemConfigForCurrentClusterAndApp(c)
		},
		"orders": func() databaseconfig.GeneratedShardedDatabaseConfig {
			return dbconfighelpers.GetShardedOrdersConfigForCurrentClusterAndApp(c)
		},
		"pingschedules": func() databaseconfig.GeneratedShardedDatabaseConfig {
			return dbconfighelpers.GetShardedPingschedulesConfigForCurrentClusterAndApp(c)
		},
		"predictivemaintenance": func() databaseconfig.GeneratedShardedDatabaseConfig {
			return dbconfighelpers.GetShardedPredictivemaintenanceConfigForCurrentClusterAndApp(c)
		},
		"recognition": func() databaseconfig.GeneratedShardedDatabaseConfig {
			return dbconfighelpers.GetShardedRecognitionConfigForCurrentClusterAndApp(c)
		},
		"releasemanagement": func() databaseconfig.GeneratedShardedDatabaseConfig {
			return dbconfighelpers.GetShardedReleasemanagementConfigForCurrentClusterAndApp(c)
		},
		"remotesupport": func() databaseconfig.GeneratedShardedDatabaseConfig {
			return dbconfighelpers.GetShardedRemotesupportConfigForCurrentClusterAndApp(c)
		},
		"reportconfig": func() databaseconfig.GeneratedShardedDatabaseConfig {
			return dbconfighelpers.GetShardedReportconfigConfigForCurrentClusterAndApp(c)
		},
		"reports": func() databaseconfig.GeneratedShardedDatabaseConfig {
			return dbconfighelpers.GetShardedReportsConfigForCurrentClusterAndApp(c)
		},
		"reportsv2": func() databaseconfig.GeneratedShardedDatabaseConfig {
			return dbconfighelpers.GetShardedReportsv2ConfigForCurrentClusterAndApp(c)
		},
		"retention": func() databaseconfig.GeneratedShardedDatabaseConfig {
			return dbconfighelpers.GetShardedRetentionConfigForCurrentClusterAndApp(c)
		},
		"rewards": func() databaseconfig.GeneratedShardedDatabaseConfig {
			return dbconfighelpers.GetShardedRewardsConfigForCurrentClusterAndApp(c)
		},
		"routeplanning": func() databaseconfig.GeneratedShardedDatabaseConfig {
			return dbconfighelpers.GetShardedRouteplanningConfigForCurrentClusterAndApp(c)
		},
		"safety": func() databaseconfig.GeneratedShardedDatabaseConfig {
			return dbconfighelpers.GetShardedSafetyConfigForCurrentClusterAndApp(c)
		},
		"safetyeventingestion": func() databaseconfig.GeneratedShardedDatabaseConfig {
			return dbconfighelpers.GetShardedSafetyeventingestionConfigForCurrentClusterAndApp(c)
		},
		"safetyeventtriage": func() databaseconfig.GeneratedShardedDatabaseConfig {
			return dbconfighelpers.GetShardedSafetyeventtriageConfigForCurrentClusterAndApp(c)
		},
		"safetyreporting": func() databaseconfig.GeneratedShardedDatabaseConfig {
			return dbconfighelpers.GetShardedSafetyreportingConfigForCurrentClusterAndApp(c)
		},
		"safetyrisk": func() databaseconfig.GeneratedShardedDatabaseConfig {
			return dbconfighelpers.GetShardedSafetyriskConfigForCurrentClusterAndApp(c)
		},
		"samsaraassistant": func() databaseconfig.GeneratedShardedDatabaseConfig {
			return dbconfighelpers.GetShardedSamsaraassistantConfigForCurrentClusterAndApp(c)
		},
		"scoring": func() databaseconfig.GeneratedShardedDatabaseConfig {
			return dbconfighelpers.GetShardedScoringConfigForCurrentClusterAndApp(c)
		},
		"sensorconfig": func() databaseconfig.GeneratedShardedDatabaseConfig {
			return dbconfighelpers.GetShardedSensorconfigConfigForCurrentClusterAndApp(c)
		},
		"sredummy": func() databaseconfig.GeneratedShardedDatabaseConfig {
			return dbconfighelpers.GetShardedSredummyConfigForCurrentClusterAndApp(c)
		},
		"tachograph": func() databaseconfig.GeneratedShardedDatabaseConfig {
			return dbconfighelpers.GetShardedTachographConfigForCurrentClusterAndApp(c)
		},
		"timecards": func() databaseconfig.GeneratedShardedDatabaseConfig {
			return dbconfighelpers.GetShardedTimecardsConfigForCurrentClusterAndApp(c)
		},
		"training": func() databaseconfig.GeneratedShardedDatabaseConfig {
			return dbconfighelpers.GetShardedTrainingConfigForCurrentClusterAndApp(c)
		},
		"trips": func() databaseconfig.GeneratedShardedDatabaseConfig {
			return dbconfighelpers.GetShardedTripsConfigForCurrentClusterAndApp(c)
		},
		"trips2": func() databaseconfig.GeneratedShardedDatabaseConfig {
			return dbconfighelpers.GetShardedTrips2ConfigForCurrentClusterAndApp(c)
		},
		"userorgpreferences": func() databaseconfig.GeneratedShardedDatabaseConfig {
			return dbconfighelpers.GetShardedUserorgpreferencesConfigForCurrentClusterAndApp(c)
		},
		"vin": func() databaseconfig.GeneratedShardedDatabaseConfig {
			return dbconfighelpers.GetShardedVinConfigForCurrentClusterAndApp(c)
		},
		"workflows": func() databaseconfig.GeneratedShardedDatabaseConfig {
			return dbconfighelpers.GetShardedWorkflowsConfigForCurrentClusterAndApp(c)
		},
		"workflowstate": func() databaseconfig.GeneratedShardedDatabaseConfig {
			return dbconfighelpers.GetShardedWorkflowstateConfigForCurrentClusterAndApp(c)
		},
		"workforcevideo": func() databaseconfig.GeneratedShardedDatabaseConfig {
			return dbconfighelpers.GetShardedWorkforcevideoConfigForCurrentClusterAndApp(c)
		},
	}
}
