// generated by sqlgengen -- DO NOT EDIT
package dataplatformtestinternalmodels

import (
	"fmt"

	"github.com/samsarahq/go/oops"

	"samsaradev.io/helpers/sqlhelpers"
)

type Bridges struct {
}

func (m *DataplatformtestinternalModels) initializeBridges() {
}

// Ignore unused import errors for packages that don't use a template needing these packages.
var _ = fmt.Printf
var _ = oops.Wrapf
var _ = sqlhelpers.SQLMultiValue
