`date` STRING,
`stat_type` INT,
`org_id` BIGINT,
`object_type` INT,
`object_id` BIGINT,
`time` BIGINT,
`value` STRUCT<
  `date`: STRING,
  `time`: BIGINT,
  `received_delta_seconds`: BIGINT,
  `is_start`: BOOLEAN,
  `is_end`: BOOLEAN,
  `is_databreak`: BOOLEAN,
  `int_value`: BIGINT,
  `double_value`: DOUBLE,
  `proto_value`: STRUCT<
    `system_stats`: STRUCT<
      `total_cpu_util`: FLOAT,
      `cpu_stats`: ARRAY<
        STRUCT<
          `cpu_name`: STRING,
          `cpu_util`: FLOAT,
          `min_freq`: BIGINT,
          `max_freq`: BIGINT,
          `cur_freq`: BIGINT,
          `online`: BOOLEAN
        >
      >,
      `memory_util`: FLOAT,
      `gpu_util`: FLOAT,
      `memory_stats`: STRUCT<
        `max_memory_util`: FLOAT,
        `top_processes_by_memory_usage`: ARRAY<
          STRUCT<
            `name`: STRING,
            `dirty_mem_kb`: BIGINT,
            `pss_mem_kb`: BIGINT,
            `swap_mem_kb`: BIGINT
          >
        >,
        `avg_mem_info`: STRUCT<
          `mem_total_kbytes`: BIGINT,
          `mem_free_kbytes`: BIGINT,
          `mem_available_kbytes`: BIGINT,
          `buffers_kbytes`: BIGINT,
          `cached_kbytes`: BIGINT,
          `swap_cached_kbytes`: BIGINT,
          `active_kbytes`: BIGINT,
          `inactive_kbytes`: BIGINT,
          `active_anon_kbytes`: BIGINT,
          `inactive_anon_kbytes`: BIGINT,
          `active_file_kbytes`: BIGINT,
          `inactive_file_kbytes`: BIGINT,
          `unevictable_kbytes`: BIGINT,
          `mlocked_kbytes`: BIGINT,
          `swap_total_kbytes`: BIGINT,
          `swap_free_kbytes`: BIGINT,
          `dirty_kbytes`: BIGINT,
          `writeback_kbytes`: BIGINT,
          `anon_pages_kbytes`: BIGINT,
          `mapped_kbytes`: BIGINT,
          `shmem_kbytes`: BIGINT,
          `slab_kbytes`: BIGINT,
          `sreclaimable_kbytes`: BIGINT,
          `sunreclaim_kbytes`: BIGINT,
          `kernel_stack_kbytes`: BIGINT,
          `page_tables_kbytes`: BIGINT,
          `nfs_unstable_kbytes`: BIGINT,
          `bounce_kbytes`: BIGINT,
          `writeback_tmp_kbytes`: BIGINT,
          `commit_limit_kbytes`: BIGINT,
          `committed_as_kbytes`: BIGINT,
          `vmalloc_total_kbytes`: BIGINT,
          `vmalloc_used_kbytes`: BIGINT,
          `vmalloc_chunk_kbytes`: BIGINT
        >,
        `max_mem_info`: STRUCT<
          `mem_total_kbytes`: BIGINT,
          `mem_free_kbytes`: BIGINT,
          `mem_available_kbytes`: BIGINT,
          `buffers_kbytes`: BIGINT,
          `cached_kbytes`: BIGINT,
          `swap_cached_kbytes`: BIGINT,
          `active_kbytes`: BIGINT,
          `inactive_kbytes`: BIGINT,
          `active_anon_kbytes`: BIGINT,
          `inactive_anon_kbytes`: BIGINT,
          `active_file_kbytes`: BIGINT,
          `inactive_file_kbytes`: BIGINT,
          `unevictable_kbytes`: BIGINT,
          `mlocked_kbytes`: BIGINT,
          `swap_total_kbytes`: BIGINT,
          `swap_free_kbytes`: BIGINT,
          `dirty_kbytes`: BIGINT,
          `writeback_kbytes`: BIGINT,
          `anon_pages_kbytes`: BIGINT,
          `mapped_kbytes`: BIGINT,
          `shmem_kbytes`: BIGINT,
          `slab_kbytes`: BIGINT,
          `sreclaimable_kbytes`: BIGINT,
          `sunreclaim_kbytes`: BIGINT,
          `kernel_stack_kbytes`: BIGINT,
          `page_tables_kbytes`: BIGINT,
          `nfs_unstable_kbytes`: BIGINT,
          `bounce_kbytes`: BIGINT,
          `writeback_tmp_kbytes`: BIGINT,
          `commit_limit_kbytes`: BIGINT,
          `committed_as_kbytes`: BIGINT,
          `vmalloc_total_kbytes`: BIGINT,
          `vmalloc_used_kbytes`: BIGINT,
          `vmalloc_chunk_kbytes`: BIGINT
        >,
        `min_mem_info`: STRUCT<
          `mem_total_kbytes`: BIGINT,
          `mem_free_kbytes`: BIGINT,
          `mem_available_kbytes`: BIGINT,
          `buffers_kbytes`: BIGINT,
          `cached_kbytes`: BIGINT,
          `swap_cached_kbytes`: BIGINT,
          `active_kbytes`: BIGINT,
          `inactive_kbytes`: BIGINT,
          `active_anon_kbytes`: BIGINT,
          `inactive_anon_kbytes`: BIGINT,
          `active_file_kbytes`: BIGINT,
          `inactive_file_kbytes`: BIGINT,
          `unevictable_kbytes`: BIGINT,
          `mlocked_kbytes`: BIGINT,
          `swap_total_kbytes`: BIGINT,
          `swap_free_kbytes`: BIGINT,
          `dirty_kbytes`: BIGINT,
          `writeback_kbytes`: BIGINT,
          `anon_pages_kbytes`: BIGINT,
          `mapped_kbytes`: BIGINT,
          `shmem_kbytes`: BIGINT,
          `slab_kbytes`: BIGINT,
          `sreclaimable_kbytes`: BIGINT,
          `sunreclaim_kbytes`: BIGINT,
          `kernel_stack_kbytes`: BIGINT,
          `page_tables_kbytes`: BIGINT,
          `nfs_unstable_kbytes`: BIGINT,
          `bounce_kbytes`: BIGINT,
          `writeback_tmp_kbytes`: BIGINT,
          `commit_limit_kbytes`: BIGINT,
          `committed_as_kbytes`: BIGINT,
          `vmalloc_total_kbytes`: BIGINT,
          `vmalloc_used_kbytes`: BIGINT,
          `vmalloc_chunk_kbytes`: BIGINT
        >
      >,
      `process_stats`: STRUCT<
        `total_cpu_usage_millipercent`: BIGINT,
        `total_samsara_usage_millipercent`: BIGINT,
        `process_infos`: ARRAY<
          STRUCT<
            `process_name`: INT,
            `custom_name`: STRING,
            `cpu_usage_millipercent`: BIGINT,
            `dirty_mem_kb`: BIGINT,
            `pss_mem_kb`: BIGINT
          >
        >
      >,
      `wifi_ap_health`: STRUCT<
        `count_failed_checks`: BIGINT,
        `count_successful_checks`: BIGINT
      >,
      `system_cpu_usage_millipercent`: BIGINT,
      `vector_processor_usage_millipercent`: BIGINT
    >
  >
>,
`_filename` STRING,
`_sort_key` STRING
