`date` STRING,
`org_id` BIGINT,
`device_id` BIGINT,
`time` BIGINT,
`value` STRUCT<
  `time`: BIGINT,
  `has_fix`: BOOLEAN,
  `latitude`: DOUBLE,
  `longitude`: DOUBLE,
  `gps_speed_meters_per_second`: DOUBLE,
  `gps_speed_invalid`: BOOLEAN,
  `heading_degrees`: DOUBLE,
  `heading_invalid`: BOOLEAN,
  `hdop`: DOUBLE,
  `vdop`: DOUBLE,
  `altitude_meters`: DOUBLE,
  `altitude_invalid`: BOOLEAN,
  `geoid_height_correction_meters`: DOUBLE,
  `has_revgeo`: BOOLEAN,
  `revgeo_street`: STRING,
  `revgeo_city`: STRING,
  `revgeo_state`: STRING,
  `revgeo_country`: STRING,
  `has_speed_limit`: BOOLEAN,
  `speed_limit_meters_per_second`: DOUBLE,
  `has_toll`: BOOLEAN,
  `toll`: BOOLEAN,
  `ecu_speed_meters_per_second`: DOUBLE,
  `has_ecu_speed`: BOOLEAN,
  `revgeo_postcode`: STRING,
  `has_way_id`: BOOLEAN,
  `way_id`: BIGINT,
  `speed_limit_source`: INT,
  `speed_limit_updated_at_ms`: BIGINT,
  `revgeo_house_number`: STRING,
  `revgeo_poi`: STRING,
  `revgeo_neighborhood`: STRING,
  `received_at_ms`: BIGINT,
  `accuracy_millimeters`: BIGINT,
  `accuracy_invalid`: BOOLEAN,
  `gps_fix_timestamp_utc_ms`: BIGINT,
  `location_source`: INT,
  `pre_release_speed_limit_meters_per_second`: DOUBLE,
  `pre_release_speed_limit_source`: INT,
  `exact_addresses_source`: INT,
  `speed_limit_is_smoothed`: BOOLEAN,
  `proxy_location_source_devices`: ARRAY<
    STRUCT<
      `org_id`: BIGINT,
      `device_id`: BIGINT,
      `in_customer_network`: BOOLEAN,
      `object_type`: INT
    >
  >,
  `is_spoofed`: BOOLEAN,
  `is_fixed`: BOOLEAN,
  `intermediate_locations`: ARRAY<
    STRUCT<
      `timestamp_utc_ms`: BIGINT,
      `latitude_1en7_degrees`: BIGINT,
      `longitude_1en7_degrees`: BIGINT,
      `gnss_speed_kmph_tenths`: BIGINT,
      `gnss_speed_invalid`: BOOLEAN,
      `ecu_speed_kmph_tenths`: BIGINT,
      `ecu_speed_invalid`: BOOLEAN
    >
  >,
  `altitude_uncertainty_meters`: BIGINT,
  `altitude_uncertainty_valid`: BOOLEAN,
  `gnss_speed_uncertainty_meters_per_second`: FLOAT,
  `gnss_speed_uncertainty_valid`: BOOLEAN,
  `heading_uncertainty_degrees`: BIGINT,
  `heading_uncertainty_valid`: BOOLEAN,
  `geofences`: ARRAY<BIGINT>,
  `geofences_computed`: BOOLEAN
>,
`scope` INT
