`date` STRING,
`stat_type` INT,
`org_id` BIGINT,
`object_type` INT,
`object_id` BIGINT,
`time` BIGINT,
`value` STRUCT<
  `date`: STRING,
  `time`: BIGINT,
  `received_delta_seconds`: BIGINT,
  `is_start`: BOOLEAN,
  `is_end`: BOOLEAN,
  `is_databreak`: BOOLEAN,
  `int_value`: BIGINT,
  `double_value`: DOUBLE,
  `proto_value`: STRUCT<
    `satellite_transmitted_data`: STRUCT<
      `has_gps_fix`: BOOLEAN,
      `latitude`: DOUBLE,
      `longitude`: DOUBLE,
      `speed_milliknots`: BIGINT,
      `gps_accuracy_millimeters`: BIGINT,
      `update_reason`: INT,
      `on_trip`: BOOLEAN,
      `signal_quality_valid`: BOOLEAN,
      `signal_quality`: BIGINT,
      `internal_metadata`: STRUCT<
        `protocol_version`: BIGINT,
        `sequence_num`: BIGINT,
        `db_disk_size_mb`: BIGINT,
        `transmit_delta_ms`: BIGINT,
        `transmit_offset_ms`: BIGINT,
        `db_num_log_events`: DECIMAL(20, 0),
        `log_db_full_percent`: FLOAT,
        `home_directory_full_percent`: FLOAT
      >,
      `iridium_metadata`: STRUCT<
        `protocol_revision_number`: INT,
        `cdr_reference`: BIGINT,
        `imei`: STRING,
        `session_status`: INT,
        `mom_sequence_number`: BIGINT,
        `session_timestamp_utc_ms`: BIGINT,
        `latitude`: DOUBLE,
        `longitude`: DOUBLE,
        `cep_radius_km`: BIGINT
      >,
      `original_payload`: BINARY,
      `brief_wake`: BOOLEAN,
      `different_trip`: BOOLEAN,
      `has_revgeo`: BOOLEAN,
      `revgeo_street`: STRING,
      `revgeo_city`: STRING,
      `revgeo_state`: STRING,
      `revgeo_country`: STRING,
      `revgeo_postcode`: STRING,
      `revgeo_house_number`: STRING,
      `revgeo_poi`: STRING,
      `revgeo_neighborhood`: STRING,
      `boot_message`: BOOLEAN,
      `panic_button_rate_limited`: BOOLEAN,
      `has_ble_sos`: BOOLEAN,
      `ble_sos`: ARRAY<BINARY>,
      `dtc_metadata`: STRUCT<
        `cellular_mobile_country_code`: BIGINT,
        `cellular_mobile_network_code`: BIGINT,
        `message_batch_index`: BIGINT
      >,
      `moderate_power_mode`: BOOLEAN
    >
  >
>,
`_filename` STRING,
`_sort_key` STRING
