`date` STRING,
`stat_type` INT,
`org_id` BIGINT,
`object_type` INT,
`object_id` BIGINT,
`time` BIGINT,
`value` STRUCT<
  `date`: STRING,
  `time`: BIGINT,
  `received_delta_seconds`: BIGINT,
  `is_start`: BOOLEAN,
  `is_end`: BOOLEAN,
  `is_databreak`: BOOLEAN,
  `int_value`: BIGINT,
  `double_value`: DOUBLE,
  `proto_value`: STRUCT<
    `location_with_road_context`: STRUCT<
      `latitude`: DOUBLE,
      `longitude`: DOUBLE,
      `has_fix`: BOOLEAN,
      `has_revgeo`: BOOLEAN,
      `revgeo_city`: STRING,
      `revgeo_state`: STRING,
      `revgeo_country`: STRING,
      `has_toll`: BOOLEAN,
      `toll`: BOOLEAN,
      `gps_speed_meters_per_second`: DOUBLE,
      `heading_degrees`: DOUBLE,
      `hdop`: DOUBLE,
      `accuracy_millimeters`: BIGINT,
      `accuracy_invalid`: BOOLEAN,
      `has_way_id`: BOOLEAN,
      `way_id`: DECIMAL(20, 0),
      `has_road_class`: BOOLEAN,
      `road_class`: INT,
      `has_speed_limit`: BOOLEAN,
      `speed_limit_meters_per_second`: DOUBLE,
      `has_ifta_geofence_exemption`: BOOLEAN,
      `ifta_geofence_exemption_types`: ARRAY<INT>,
      `ifta_exempt_place_id`: DECIMAL(20, 0)
    >
  >
>,
`_filename` STRING,
`_sort_key` STRING
