`date` STRING,
`stat_type` INT,
`org_id` BIGINT,
`object_type` INT,
`object_id` BIGINT,
`time` BIGINT,
`value` STRUCT<
  `date`: STRING,
  `time`: BIGINT,
  `received_delta_seconds`: BIGINT,
  `is_start`: BOOLEAN,
  `is_end`: BOOLEAN,
  `is_databreak`: BOOLEAN,
  `int_value`: BIGINT,
  `double_value`: DOUBLE,
  `proto_value`: STRUCT<
    `crux_proxy_test_mode_data`: STRUCT<
      `rssi_dbm`: INT,
      `mac_observed`: DECIMAL(20, 0),
      `protocol_version`: BIGINT,
      `adv_packet_verbatim`: BINARY,
      `adv_interval_ms`: BIGINT,
      `uuid`: INT,
      `product_id`: INT,
      `reset_reason`: INT,
      `flags`: BIGINT,
      `temperature_mc`: INT,
      `battery_mv`: INT,
      `fw_version`: BIGINT,
      `error_code`: BIGINT,
      `boot_count`: BIGINT,
      `self_test_result`: BIGINT,
      `time_since_reset`: BIGINT,
      `time_since_power_on_reset`: BIGINT,
      `mac_address_in_adv_packet`: DECIMAL(20, 0),
      `tx_power_dbm`: INT
    >
  >
>,
`_filename` STRING,
`_sort_key` STRING
