`timestamp` TIMESTAMP,
`org_id` BIGINT,
`device_id` BIGINT,
`current_gateway_serial` STRING,
`return_cm_serial` STRING,
`gateway_pre_2019_with_cm` BOOLEAN,
`replacement_items` MAP<
  STRING,
  ARRAY<STRING>
>,
`return_items` MAP<
  STRING,
  ARRAY<STRING>
>,
`health_status` STRING,
`return_type` STRING,
`warranty_exchange_reason` STRING,
`opportunity_tags` ARRAY<STRING>,
`initiated_user_id` BIGINT,
`order_number` STRING,
`updated_at` TIMESTAMP,
`customer_submitted_rma_order` BOOLEAN,
`customer_submitted_rma_order_at` TIMESTAMP,
`created_at` TIMESTAMP,
`sent_instruction_email_to_customer` BOOLEAN,
`recommended_action` STRING,
`manually_resolved_at` TIMESTAMP,
`manually_resolved_by_user_id` BIGINT,
`shipping_user_email` STRING,
`shipping_user_street_address` STRING,
`shipping_user_city` STRING,
`shipping_user_state` STRING,
`shipping_user_postal_code` STRING,
`shipping_user_country` STRING,
`date` DATE
