`vin` STRING,
`make` STRING,
`model` STRING,
`year` BIGINT,
`product_id` BIGINT,
`engine_model` STRING,
`asset_type` STRING,
`trailer_type` STRING,
`diagnostics_coverage` STRING,
`diagnostics_port_type` STRING,
`cable_id` BIGINT,
`cable_sku` STRING,
`notes` STRING,
`accessories` STRING,
`logic` INT,
`probability` DOUBLE,
`return_type` INT,
`error_text` STRING,
`timestamp` TIMESTAMP,
`is_api_request` BOOLEAN,
`gateway` STRING,
`supportedGateways` ARRAY<STRING>,
`user_email` STRING,
`sfdc_link` STRING,
`quantity` BIGINT,
`request_source` STRING,
`locale` STRING,
`algorithm_version` STRING,
`variant_id` BIGINT,
`error_code` STRING,
`selection_logic` STRING,
`rule_id` STRING,
`possible_cables_for_rule` MAP<STRING, STRING>,
`asset_subtype` STRING,
`powertrain` STRING,
`fuel_group` STRING,
`required_properties` MAP<STRING, STRING>,
`additional_properties` MAP<STRING, STRING>,
`cable_found_incompatible` STRING,
`cables_with_ratios_too_close` MAP<STRING, DOUBLE>,
`session_id` STRING,
`cell` STRING,
`user_role` STRING,
`ruleset_version` STRING,
`used_decoder` STRING,
`gateway_upgrade_required` BOOLEAN,
`compatible_gateways` ARRAY<STRING>,
`date` DATE
