`org_id` BIGINT,
`user_id` BIGINT,
`vms_device_id` BIGINT,
`server_recorded_timestamp` TIMESTAMP,
`projected_retention_days` BIGINT,
`total_camera_bitrate_mbps` DOUBLE,
`storage_per_day_tb` DOUBLE,
`storage_used_tb` DOUBLE,
`storage_total_tb` DOUBLE,
`camera_device_id_to_oldest_footage_days` MAP<BIGINT, BIGINT>,
`date` DATE
