`org_id` BIGINT,
`service_account_user_id` BIGINT,
`access_token_id` STRING,
`access_token_name` STRING,
`oauth_token_id` STRING,
`oauth_token_app_uuid` STRING,
`request_id` STRING,
`status_code` BIGINT,
`path_template` STRING,
`http_method` STRING,
`duration_ms` BIGINT,
`version` STRING,
`team` STRING,
`cell` STRING,
`ip_address` STRING,
`host` STRING,
`timestamp` TIMESTAMP,
`request_headers` MAP<
  STRING,
  ARRAY<STRING>
>,
`response_headers` MAP<
  STRING,
  ARRAY<STRING>
>,
`query_params` MAP<
  STRING,
  ARRAY<STRING>
>,
`body` BINARY,
`request_body` BINARY,
`s3_path` STRING,
`body_length` BIGINT,
`request_body_length` BIGINT,
`ecs_task_id` STRING,
`url` STRING,
`server_error` STRING,
`error_type` STRING,
`trace_id` STRING,
`date` DATE
