`successfully_processed` BOOLEAN,
`observation_time_ms` BIGINT,
`observation_batched_time_ms` BIGINT,
`central_org_id` BIGINT,
`central_object_type` BIGINT,
`central_object_id` BIGINT,
`ble_address` BIGINT,
`service_uuid` STRING,
`last_adv_packet_data` BINARY,
`parsed_packet_data` MAP<STRING, STRING>,
`peripheral_org_id` BIGINT,
`peripheral_hardware_id` BIGINT,
`skipped_reason` STRING,
`skipped_reason_details` STRING,
`date` DATE
