`timestamp` TIMESTAMP,
`org_id` BIGINT,
`device_id` BIGINT,
`product_id` BIGINT,
`latitude` DOUBLE,
`longitude` DOUBLE,
`accuracy_millimeters` BIGINT,
`source_devices` MAP<BIGINT, BOOLEAN>,
`aggregated_locations_by_network` MAP<STRING, BIGINT>,
`algorithm` STRING,
`aggregation_window_seconds` INT,
`timestamps_of_locations_used_for_aggregation_ms` ARRAY<BIGINT>,
`has_only_mobile_app_sources` BOOLEAN,
`has_mobile_and_device_sources` BOOLEAN,
`is_customer_facing` BOOLEAN,
`geofences` ARRAY<BIGINT>,
`buffer_zone_resolved_as_inside_count` INT,
`buffer_zone_geofences` ARRAY<BIGINT>,
`geofences_computed` BOOLEAN,
`time_since_last_motion_min` INT,
`time_since_last_observation_ms` BIGINT,
`has_movement_capability` BOOLEAN,
`is_peripheral_moving` BOOLEAN,
`central_locations_json` STRING,
`date` DATE
