-- NOTE: This query has been commented out because kinesisstats.osdcruxproxylocationdebug
-- and crux_proxy_location_debug have been removed and reserved. The new osdcruxdebug table has a
-- different schema that doesn't include scanner_data or adv_data fields. This query needs to be
-- rewritten to use the new data sources (e.g., osdcruxdebug, generic_proxy_readings_debug, or
-- datastreams.crux_unaggregated_locations) with appropriate joins to get scanner location data.

-- TODO: Should be a merge upsert instead of create/replace
-- create or replace table hardware_analytics.AT_summary_data as (select 
--         c.value.proto_value.crux_proxy_location_debug.adv_data.mac as peripheral_asset_id,
--         g.serial as peripheral_serial, 
--         d.org_id as peripheral_org_id,
--         d.device_id as peripheral_device_id,
-- g.product_id as peripheral_product_id,
-- --peripheral_org_type,
-- min(c.date) as first_observation_date,
-- min(c.time) as first_observation_ms,
-- min_by(c.value.proto_value.crux_proxy_location_debug.scanner_data.latitude_nd / 1000000000, time) as first_observation_lat,
-- min_by(c.value.proto_value.crux_proxy_location_debug.scanner_data.longitude_nd / 1000000000, time) as first_observation_lon,
-- min_by(c.value.proto_value.crux_proxy_location_debug.scanner_data.speed_milliknots * 1.15077945 / 1000, time) as first_observation_scanner_mph,
-- min_by(c.org_id, time) as first_observation_scanner_org_id,
-- min_by(c.object_id, time) as first_observation_scanner_device_id,
-- min_by(h.gateway_id, time) as first_observation_scanner_gateway_id,
-- min_by(h.product_id, time) as first_observation_scanner_product_id,
-- min_by(c.value.proto_value.crux_proxy_location_debug.adv_data.adv_packet_verbatim, time) as first_observation_advertising_payload_b64,
-- max(c.date) as last_observation_date,
-- max(c.time) as last_observation_ms,
-- max_by(c.value.proto_value.crux_proxy_location_debug.scanner_data.longitude_nd / 1000000000, time) as last_observation_lon,
-- max_by(c.value.proto_value.crux_proxy_location_debug.scanner_data.latitude_nd / 1000000000, time) as last_observation_lat,
-- max_by(c.value.proto_value.crux_proxy_location_debug.scanner_data.speed_milliknots * 1.15077945 / 1000, time) as last_observation_scanner_mph,
-- max_by(c.org_id, time) as last_observation_scanner_org_id,
-- max_by(c.object_id, time) as last_observation_scanner_device_id,
-- max_by(h.gateway_id, time) last_observation_scanner_gateway_id,
-- max_by(h.product_id, time) as last_observation_scanner_product_id,
-- max_by(c.value.proto_value.crux_proxy_location_debug.adv_data.adv_packet_verbatim, time) as last_observation_advertising_payload_b64
--     from kinesisstats.osdcruxproxylocationdebug as c
--     left join hardware.gateways_heartbeat as h -- need to replace this with an extended version that accurately captures range
--     on h.object_id = c.object_id
--     and date between h.first_heartbeat_date and h.last_heartbeat_date
--     and c.time between h.first_heartbeat_time and h.last_heartbeat_time
--     left join productsdb.gateways as g -- for peripheral gateway info
--     on c.value.proto_value.crux_proxy_location_debug.adv_data.mac = g.id
--     left join (select gateway_id, device_id, serial, org_id, 
--                 first_association_time, coalesce(last_association_time, unix_timestamp()*1000) as last_association_time 
--         from (select gateway_id, device_id, serial, org_id, 
--                     time as first_association_time, (lead(time) over(partition by gateway_id order by time)) - 1 as last_association_time
--             from (select gh.gateway_id, gh.device_id, g.serial, d.org_id, 
--                         cast(round(cast(gh.`timestamp` as double)*1000, 0) as long) as time
--                 from productsdb.gateway_device_history as gh
--                 join productsdb.gateways as g
--                 on gh.gateway_id = g.id
--                 join productsdb.devices as d
--                 on gh.device_id = d.id
--                 join definitions.products as dp
--                 on g.product_id = dp.product_id
--                 where dp.name like "AT%" )
--             )
--         ) as d -- to find the right org and device_id for each AT, needs to be for all AT* tables
--     on c.value.proto_value.crux_proxy_location_debug.adv_data.mac = d.gateway_id
--     and g.serial = d.serial
--     and c.time between d.first_association_time and d.last_association_time
--     where value.proto_value.crux_proxy_location_debug.adv_data.uuid = 2 
-- group by c.value.proto_value.crux_proxy_location_debug.adv_data.mac,
--         g.serial, 
--         d.org_id,
--         d.device_id,
-- g.product_id)