package datapipelineerrors

import (
	"os"
	"path/filepath"
	"text/template"

	"github.com/samsarahq/go/oops"

	"samsaradev.io/helpers/fileformatter"
	"samsaradev.io/helpers/ni/filepathhelpers"
)

var pythonTemplate = `# This file is generated by '$ taskrunner gen/dataplatform/datapipelineerrordefinitions' DO NOT EDIT
DATA_PIPELINE_SPOT_ERRORS = [
	{{range $definition := .SpotErrors -}}
		("{{$definition.ErrorMatchString}}", "{{$definition.ErrorType}}"),
	{{end}}
]

DATA_PIPELINE_AWS_CAPACITY_ERRORS = [
	{{range $definition := .AWSCapacityErrors -}}
		("{{$definition.ErrorMatchString}}", "{{$definition.ErrorType}}"),
	{{end}}
]


DATA_PIPELINE_ERRORS = [
	{{range $definition := .Errors -}}
		("{{$definition.ErrorMatchString}}", "{{$definition.ErrorType}}"),
	{{end}}
]

def get_error_classification(error_msg: str) -> str:
    for error, tag in DATA_PIPELINE_ERRORS:
        if error.lower() in error_msg.lower():
            return tag
    return "unclassified"

def is_aws_capacity_error(error_msg: str) -> bool:
    for err, _ in DATA_PIPELINE_AWS_CAPACITY_ERRORS:
        if err.lower() in error_msg.lower():
            return True
    return False

def is_spot_error(error_msg: str) -> bool:
    for err, _ in DATA_PIPELINE_SPOT_ERRORS:
        if err.lower() in error_msg.lower():
            return True
    return False`

func GenerateDataPipelineErrorDefinitions() error {
	if err := generatePythonDefinitionFile(); err != nil {
		return oops.Wrapf(err, "error generating python definition file")
	}

	return nil
}

func generatePythonDefinitionFile() error {
	var spotErrors []ErrorDefinition
	for _, errorDefinition := range errors {
		if errorDefinition.SpotError {
			spotErrors = append(spotErrors, errorDefinition)
		}
	}

	var awsCapacityErrors []ErrorDefinition
	for _, errorDefinition := range errors {
		if errorDefinition.AWSCapacityError {
			awsCapacityErrors = append(awsCapacityErrors, errorDefinition)
		}
	}

	pythonTemplateInput := struct {
		Errors            []ErrorDefinition
		SpotErrors        []ErrorDefinition
		AWSCapacityErrors []ErrorDefinition
	}{
		Errors:            errors,
		SpotErrors:        spotErrors,
		AWSCapacityErrors: awsCapacityErrors,
	}

	tmpl, err := template.New("datapipelines_errors_python_template").Parse(pythonTemplate)
	if err != nil {
		return oops.Wrapf(err, "error parsing datapipelines errors python template string into text.Template")
	}

	f, err := os.Create(filepath.Join(filepathhelpers.BackendRoot, "python3/samsaradev/infra/dataplatform/lambda/data_pipelines/databricks/error_definitions.py"))
	if err != nil {
		return oops.Wrapf(err, "unable to create file at 'python3/samsaradev/infra/dataplatform/lambda/data_pipelines/databricks/error_definitions.py'")
	}

	return fileformatter.ExecuteTmplWithFormat(f, pythonTemplateInput, tmpl, fileformatter.Python)
}
