source:
    type: dbt
    config:
    # Coordinates
    # To use this as-is, set the environment variable DBT_PROJECT_ROOT to the root folder of your dbt project
        manifest_path: "gtm_manifest.json"
        catalog_path: "gtm_catalog.json"
        sources_path: "gtm_sources.json" # optional for freshness
        run_results_paths:
        - "gtm_run_results.json"
        target_platform: databricks
        platform_instance: MarketingAnalytics
        include_compiled_code: true
        include_column_lineage: true
        incremental_lineage: false
        stateful_ingestion:
            enabled: true
        skip_sources_in_lineage: true
        entities_enabled:
            sources: 'NO'
            seeds: 'NO'
            test_definitions: 'YES'
            test_results: 'YES'
        node_name_pattern:
            allow:
                - '.*_gold$'
        meta_mapping:
            owner:
                match: ".*"
                operation: "add_owner"
                config:
                    owner_type: group
                    owner_category: TECHNICAL_OWNER
            term:
                match: ".*"
                operation: "add_term"
                config:
                    term: "{{ $match }}"
            terms_list:
                match: ".*"
                operation: "add_terms"
                config:
                    separator: ","
        column_meta_mapping:
            term:
                match: ".*"
                operation: "add_term"
                config:
                    term: "{{ $match }}"
pipeline_name: gtm_dbt
