source:
  type: unity-catalog
  config:
    workspace_url: https://samsara-dev-us-west-2.cloud.databricks.com/?o=5924096274798303
    token: "${DATABRICKS_UNITY_TOKEN}"
    emit_siblings: false
    include_usage_statistics: false
    include_hive_metastore: false
    include_table_lineage: false # we are ingesting table lineage directly from the system tables
    include_column_lineage: false
    include_notebooks: false
    format_sql_queries: true
    stateful_ingestion:
      enabled: false
    catalog_pattern:
      allow:
        - "default"
    schema_pattern:
      allow:
        - "default.dataprep"
        - "default.dataprep_assets"
        - "default.dataprep_cellular"
        - "default.dataprep_firmware"
        - "default.dataprep_ml"
        - "default.dataprep_routing"
        - "default.dataprep_safety"
        - "default.dataprep_telematics"
        - "default.growth"
        - "default.data_analytics"
        - "default.firmware"
        - "default.firmware_dev"
        - "default.adasmetrics"
        - "default.apollo"
        - "default.baxter"
        - "default.bigquery"
        - "default.cm3xinvestigation"
        - "default.compliance_metrics"
        - "default.connectedworker"
        - "default.databricks_alerts"
        - "default.dataproducts"
        - "default.devexp"
        - "default.firebase_crashlytics"
        - "default.gql_query_performance_report"
        - "default.gtms"
        - "default.ksdifftool"
        - "default.mdm"
        - "default.mldatasets"
        - "default.mobile_metrics"
        - "default.multicam"
        - "default.vgdiagnostics"
        - "default.alert_latency"
        - "default.aria_report"
        - "default.billing"
        - "default.compliance"
        - "default.customer"
        - "default.dataplatform"
        - "default.dataplatform_stable_report"
        - "default.datascience"
        - "default.devecosystem"
        - "default.dispatchdb"
        - "default.dojo"
        - "default.finops"
        - "default.firmwarerelease"
        - "default.fivetran_netsuite_finance"
        - "default.fuel_maintenance"
        - "default.hardware"
        - "default.hardware_analytics"
        - "default.helpers"
        - "default.labelbox"
        - "default.marketingdata"
        - "default.mda_sandbox"
        - "default.mda_stage"
        - "default.netsuite_data"
        - "default.netsuite_suiteanalytics"
        - "default.pagerduty_bronze"
        - "default.people_analytics"
        - "default.opsmetrics"
        - "default.platops"
        - "default.release_management"
        - "default.report_staging"
        - "default.routeload_logs"
        - "default.s3inventory"
        - "default.sda_gold"
        - "default.sfdc_data"
        - "default.shared_people_ops_data"
        - "default.solutions_integration_services"
        - "default.supportops"
        - "default.technical_support"
        - "default.trips_transformations"
        - "default.year_review_metrics"
        - "default.fivetran_launchdarkly_bronze"
        - "default.accuweather"
        - "default.mediaexperience_prod"
        - "default.canonical_distance_updates"
        - "default.hardware_features"
        - "default.incidentio_bronze"
      deny:
        - "default.dataplatform_dev"
        - "default.data_analytics_from_eu_west_1"
        - "default.hardware_dev"
        - "default.compliance_shard_0db"
        - "default.compliance_shard_1db"
        - "default.compliance_shard_2db"
        - "default.compliance_shard_3db"
        - "default.compliance_shard_4db"
        - "default.compliance_shard_5db"
        - "default.mdm_shard_0db"
        - "default.mdm_shard_1db"
        - "default.mdm_shard_2db"
        - "default.mdm_shard_3db"
        - "default.mdm_shard_4db"
        - "default.mdm_shard_5db"
        - "default.dataplatformtestinternaldb_shards"
        - "default.dataplatformtestinternal_shard_0db"
        - "default.dataplatformtestinternal_shard_1db"
        - "default.dataplatformtestinternal_shard_2db"
        - "default.dataplatformtestinternal_shard_3db"
        - "default.dataplatformtestinternal_shard_4db"
        - "default.dataplatformtestinternal_shard_5db"
        - "default.devecosystem_dev"
        - "default.marketingdata_dev"
        - "default.dojo_tmp"
        - "default.dojo_tests_new"
    table_pattern:
      deny:
        - "default.*.test_"
        - "default.*.raman_"
        - "default.*.jack_"
        - "default.*.tpassaro_"
        - "default.*.parth_"
        - "default.*.moonchu_"
        - "default.*.moon_"
        - "default.*.bdonecker_"
        - "default.*.temp_"
        - "default.*.temporary_"
        - "default.*.eli_"
        - "default.*.lucas_"
        - "default.*.meenu_"
        - "default.*._temp"
        - "default.*.apuzyk_"
        - "default.*.eric_"
        - "default.*.pang_"
        - "default.*.srajvans_"
        - "default.*.srajvanshi_"
        - "default.*.chenyu_"
        - "default.*.tmp_"
        - "default.*.agovan_"
        - "default.*.alice_"
        - "default.*.abrahm_"
        - "default.*.gil_"
        - "default.*.jk_"
        - "default.*.joyce_"
        - "default.*.udita_"
