package metadataregistry

import (
	"samsaradev.io/team"
	"samsaradev.io/team/components"
)

// Specify owners for Unmanaged Data Sets
// (i.e NOT KinesisStats, RDS, DataStreams, or Pipelines. These assets have their owner registries with owners)
// Ex:
//    "{db_name}.{table_name}": team.DataPlatform,

var Owners = map[string]components.TeamInfo{ // lint: +sorted
	"billing.dataplatform_costs":                         team.DataPlatform,
	"dataprep.445_calendar":                              team.DataEngineering,
	"dataprep.api_active_users_and_deployments":          team.DataEngineering,
	"dataprep.api_monthly_active_users_and_deployments":  team.DataEngineering,
	"dataprep.api_performancew":                          team.DataEngineering,
	"dataprep.customer_health_tracking":                  team.DataEngineering,
	"dataprep.customer_metadata":                         team.DataEngineering,
	"dataprep.customer_nps":                              team.DataEngineering,
	"dataprep.customer_support":                          team.DataEngineering,
	"dataprep.device_anomalies":                          team.DataEngineering,
	"dataprep.device_builds":                             team.DataEngineering,
	"dataprep.device_cables":                             team.DataEngineering,
	"dataprep.device_canbus":                             team.DataEngineering,
	"dataprep.device_gps_accuracy":                       team.DataEngineering,
	"dataprep.device_heartbeats":                         team.DataEngineering,
	"dataprep.devices_free_trials":                       team.DataEngineering,
	"dataprep.devices_sold":                              team.DataEngineering,
	"dataprep.free_trial_serials":                        team.DataEngineering,
	"dataprep.manual_odometer":                           team.DataEngineering,
	"dataprep.routeload_data":                            team.DataEngineering,
	"dataprep.sam_scheduled_reports":                     team.DataEngineering,
	"dataprep.thermal_limiter_safe_mode":                 team.DataEngineering,
	"dataprep_cellular.att_daily_usage":                  team.CoreServices,
	"dataprep_cellular.vodafone_daily_usage":             team.CoreServices,
	"dataprep_routing.scheduled_distances":               team.Routing,
	"dataprep_safety.anomalies_by_service":               team.DataScience,
	"dataprep_safety.attached_cm_usb_ranges":             team.DataScience,
	"dataprep_safety.cm_anomalies":                       team.DataScience,
	"dataprep_safety.cm_daily_data_usage":                team.DataScience,
	"dataprep_safety.cm_device_health_daily":             team.DataScience,
	"dataprep_safety.cm_device_health_intervals":         team.DataScience,
	"dataprep_safety.cm_linked_vgs":                      team.DataScience,
	"dataprep_safety.cm_overheating_durations":           team.DataScience,
	"dataprep_safety.cm_physically_disconnected_ranges":  team.DataScience,
	"dataprep_safety.cm_power_ranges":                    team.DataScience,
	"dataprep_safety.cm_recording_durations":             team.DataScience,
	"dataprep_safety.cm_safe_mode_durations":             team.DataScience,
	"dataprep_safety.cm_speed_limit_available_durations": team.DataScience,
	"dataprep_safety.cm_temps":                           team.DataScience,
	"dataprep_safety.cm_vg_intervals":                    team.DataScience,
	"dataprep_safety.device_adas_settings_tracking":      team.DataScience,
	"dataprep_safety.device_build_and_bootcount":         team.DataScience,
	"dataprep_safety.device_settings_tracking":           team.DataScience,
	"dataprep_safety.org_adas_settings_tracking":         team.DataScience,
	"dataprep_safety.safety_harsh_events_intervals":      team.DataScience,
	"dataprep_safety.safety_harsh_events_upload_events":  team.DataScience,
	"dataprep_safety.vg_air_temp":                        team.DataScience,
	"dataprep_safety.video_request_data":                 team.DataScience,
	"dataprep_telematics.daily_eld_relevant_devices":     team.DataEngineering,
	"dataprep_telematics.vg_fleet_diagnostics_latest":    team.DataEngineering,
	"samsara_zendesk.call_metric":                        team.DataEngineering,
	"samsara_zendesk.group":                              team.DataEngineering,
	"samsara_zendesk.organization":                       team.DataEngineering,
	"samsara_zendesk.ticket":                             team.DataEngineering,
	"samsara_zendesk.ticket_comment":                     team.DataEngineering,
	"samsara_zendesk.ticket_custom_field":                team.DataEngineering,
	"samsara_zendesk.ticket_field_history":               team.DataEngineering,
	"samsara_zendesk.ticket_form_history":                team.DataEngineering,
	"samsara_zendesk.ticket_link":                        team.DataEngineering,
	"samsara_zendesk.ticket_tag":                         team.DataEngineering,
	"samsara_zendesk.user":                               team.DataEngineering,
}
