package deltalakedeletion

// TableDeletionSpec is the struct used to instantiate a record in the deletion registry.
// A guide for registering a table in the data lake to the deletion framework can be found here:
// - https://samsara.atlassian-us-gov-mod.net/wiki/spaces/DATA/pages/17802424/Data+Lake+Deletion+Framework+A+Guide+to+Table+Registration
type TableDeletionSpec struct {
	Database                     string `json:"database"`
	Table                        string `json:"table"`
	CustomerIdentificationColumn string `json:"customer_identification_column"`
	Group                        string `json:"group"`
	Format                       string `json:"format"`
}

var AllUSDeletionRegistry = []TableDeletionSpec{
	{
		Database:                     "jack_test",
		Table:                        "deletion_test",
		CustomerIdentificationColumn: "org_id",
		Group:                        "notebooks",
		Format:                       "delta",
	},
	{
		Database:                     "api_logs",
		Table:                        "api",
		CustomerIdentificationColumn: "OrgId",
		Group:                        "notebooks",
		Format:                       "delta",
	},
	{
		Database:                     "datastreams_history",
		Table:                        "api_logs",
		CustomerIdentificationColumn: "org_id",
		Group:                        "datastreams",
		Format:                       "delta",
	},
	{
		Database:                     "kinesisstats_history",
		Table:                        "osdevicetodrivercards",
		CustomerIdentificationColumn: "org_id",
		Group:                        "kinesisstats",
		Format:                       "delta",
	},
	{
		Database:                     "kinesisstats_history",
		Table:                        "osdtachographdriverstate",
		CustomerIdentificationColumn: "org_id",
		Group:                        "kinesisstats",
		Format:                       "delta",
	},
	{
		Database:                     "kinesisstats_history",
		Table:                        "osdrivercardtodevice",
		CustomerIdentificationColumn: "org_id",
		Group:                        "kinesisstats",
		Format:                       "delta",
	},
	{
		Database:                     "kinesisstats_history",
		Table:                        "osdtachographdriverinfo",
		CustomerIdentificationColumn: "org_id",
		Group:                        "kinesisstats",
		Format:                       "delta",
	},
	{
		Database:                     "kinesisstats_history",
		Table:                        "osdtachographvudownload",
		CustomerIdentificationColumn: "org_id",
		Group:                        "kinesisstats",
		Format:                       "delta",
	},
	{
		Database:                     "s3bigstats",
		Table:                        "osdtachographvudownload_raw",
		CustomerIdentificationColumn: "org_id",
		Group:                        "s3bigstats",
		Format:                       "delta",
	},
	{
		Database:                     "datastreams_history",
		Table:                        "connected_equipment_reefer_command_logs",
		CustomerIdentificationColumn: "org_id",
		Group:                        "datastreams",
		Format:                       "delta",
	},
	// [DataType_SAFETY_EVENTS]
	{
		Database:                     "kinesisstats_history",
		Table:                        "osdaccelerometer",
		CustomerIdentificationColumn: "org_id",
		Group:                        "kinesisstats",
		Format:                       "delta",
	},
	{
		Database:                     "s3bigstats",
		Table:                        "osdaccelerometer_raw",
		CustomerIdentificationColumn: "org_id",
		Group:                        "s3bigstats",
		Format:                       "delta", // Verified on Amundsen
	},
	{
		Database:                     "dataprep_ml",
		Table:                        "dashcam_images",
		CustomerIdentificationColumn: "org_id",
		Group:                        "datapipelines",
		Format:                       "delta",
	},
	{
		Database:                     "dataprep",
		Table:                        "osdaccelerometer_event_traces",
		CustomerIdentificationColumn: "org_id",
		Group:                        "notebooks",
		Format:                       "delta",
	},
	// [DataType_SAFETY_EVENTS] score_event_report_v3 data pipeline
	{
		Database:                     "safety_report",
		Table:                        "safety_events",
		CustomerIdentificationColumn: "org_id",
		Group:                        "datapipelines",
		Format:                       "delta",
	},
	{
		Database:                     "safety_report",
		Table:                        "safety_event_labels",
		CustomerIdentificationColumn: "org_id",
		Group:                        "datapipelines",
		Format:                       "delta",
	},
	{
		Database:                     "safety_report",
		Table:                        "safety_event_hourly_agg",
		CustomerIdentificationColumn: "org_id",
		Group:                        "datapipelines",
		Format:                       "delta",
	},
	{
		Database:                     "safety_report",
		Table:                        "safety_event_labels_hourly_agg",
		CustomerIdentificationColumn: "org_id",
		Group:                        "datapipelines",
		Format:                       "delta",
	},
	{
		Database:                     "safety_report",
		Table:                        "safety_event_hourly_agg_v2",
		CustomerIdentificationColumn: "org_id",
		Group:                        "datapipelines",
		Format:                       "delta",
	},
	{
		Database:                     "safety_report",
		Table:                        "trip_with_safety_event_labels",
		CustomerIdentificationColumn: "org_id",
		Group:                        "datapipelines",
		Format:                       "delta",
	},
	{
		Database:                     "safety_report",
		Table:                        "trip_with_safety_event_labels_hourly_agg",
		CustomerIdentificationColumn: "org_id",
		Group:                        "datapipelines",
		Format:                       "delta",
	},
	{
		Database:                     "safety_report",
		Table:                        "trip_speeding",
		CustomerIdentificationColumn: "org_id",
		Group:                        "datapipelines",
		Format:                       "delta",
	},
	{
		Database:                     "safety_report",
		Table:                        "trip_stats_hourly_agg",
		CustomerIdentificationColumn: "org_id",
		Group:                        "datapipelines",
		Format:                       "delta",
	},
	{
		Database:                     "safety_report",
		Table:                        "score_event_report_v3",
		CustomerIdentificationColumn: "org_id",
		Group:                        "datapipelines",
		Format:                       "delta",
	},
	{
		Database:                     "report_staging",
		Table:                        "score_event_report_v3",
		CustomerIdentificationColumn: "org_id",
		Group:                        "datapipelines",
		Format:                       "delta",
	},
	{
		Database:                     "datastreams_history",
		Table:                        "driver_assignment_dropped_backfill_messages",
		CustomerIdentificationColumn: "org_id",
		Group:                        "datastreams",
		Format:                       "delta",
	},
	{
		Database:                     "datastreams_history",
		Table:                        "oem_api_data_logs",
		CustomerIdentificationColumn: "org_id",
		Group:                        "datastreams",
		Format:                       "delta",
	},
	{
		Database:                     "datastreams_history",
		Table:                        "driver_assignment_audit_log",
		CustomerIdentificationColumn: "org_id",
		Group:                        "datastreams",
		Format:                       "delta",
	},
	{
		Database:                     "datastreams_history",
		Table:                        "driver_assignment_settings_audit_log",
		CustomerIdentificationColumn: "org_id",
		Group:                        "datastreams",
		Format:                       "delta",
	},
	{
		Database:                     "datastreams_history",
		Table:                        "internal_rma_audit_log",
		CustomerIdentificationColumn: "org_id",
		Group:                        "datastreams",
		Format:                       "delta",
	},
	{
		Database:                     "canonical_distance",
		Table:                        "combined",
		CustomerIdentificationColumn: "org_id",
		Group:                        "datapipelines",
		Format:                       "delta",
	},
	{
		Database:                     "canonical_distance",
		Table:                        "filtered_odometer",
		CustomerIdentificationColumn: "org_id",
		Group:                        "datapipelines",
		Format:                       "delta",
	},
	{
		Database:                     "canonical_distance",
		Table:                        "total_distance",
		CustomerIdentificationColumn: "org_id",
		Group:                        "datapipelines",
		Format:                       "delta",
	},
	{
		Database:                     "kinesisstats_history",
		Table:                        "osdodometer",
		CustomerIdentificationColumn: "org_id",
		Group:                        "kinesisstats",
		Format:                       "delta",
	},
	{
		Database:                     "datastreams_history",
		Table:                        "speed_limit_locations",
		CustomerIdentificationColumn: "org_id",
		Group:                        "datastreams",
		Format:                       "delta",
	},
	{
		Database:                     "datastreams_history",
		Table:                        "speed_spike_detections",
		CustomerIdentificationColumn: "org_id",
		Group:                        "datastreams",
		Format:                       "delta",
	},
	{
		Database:                     "datastreams_history",
		Table:                        "tile_generation_logs",
		CustomerIdentificationColumn: "org_id",
		Group:                        "datastreams",
		Format:                       "delta",
	},
	{
		Database:                     "messagesdb_hashed",
		Table:                        "messages_hashed",
		CustomerIdentificationColumn: "org_id",
		Group:                        "notebooks",
		Format:                       "delta",
	},
}

var AllEUDeletionRegistry = []TableDeletionSpec{
	{
		Database:                     "jack_test",
		Table:                        "deletion_test",
		CustomerIdentificationColumn: "org_id",
		Group:                        "notebooks",
		Format:                       "delta",
	},
	{
		Database:                     "api_logs",
		Table:                        "api",
		CustomerIdentificationColumn: "OrgId",
		Group:                        "notebooks",
		Format:                       "delta",
	},
	{
		Database:                     "datastreams_history",
		Table:                        "api_logs",
		CustomerIdentificationColumn: "org_id",
		Group:                        "datastreams",
		Format:                       "delta",
	},
	{
		Database:                     "kinesisstats_history",
		Table:                        "osdevicetodrivercards",
		CustomerIdentificationColumn: "org_id",
		Group:                        "kinesisstats",
		Format:                       "delta",
	},
	{
		Database:                     "kinesisstats_history",
		Table:                        "osdtachographdriverstate",
		CustomerIdentificationColumn: "org_id",
		Group:                        "kinesisstats",
		Format:                       "delta",
	},
	{
		Database:                     "kinesisstats_history",
		Table:                        "osdrivercardtodevice",
		CustomerIdentificationColumn: "org_id",
		Group:                        "kinesisstats",
		Format:                       "delta",
	},
	{
		Database:                     "kinesisstats_history",
		Table:                        "osdtachographdriverinfo",
		CustomerIdentificationColumn: "org_id",
		Group:                        "kinesisstats",
		Format:                       "delta",
	},
	{
		Database:                     "kinesisstats_history",
		Table:                        "osdtachographvudownload",
		CustomerIdentificationColumn: "org_id",
		Group:                        "kinesisstats",
		Format:                       "delta",
	},
	{
		Database:                     "s3bigstats",
		Table:                        "osdtachographvudownload_raw",
		CustomerIdentificationColumn: "org_id",
		Group:                        "s3bigstats",
		Format:                       "delta",
	},
	{
		Database:                     "datastreams_history",
		Table:                        "connected_equipment_reefer_command_logs",
		CustomerIdentificationColumn: "org_id",
		Group:                        "datastreams",
		Format:                       "delta",
	},
	// [DataType_SAFETY_EVENTS]
	{
		Database:                     "kinesisstats_history",
		Table:                        "osdaccelerometer",
		CustomerIdentificationColumn: "org_id",
		Group:                        "kinesisstats",
		Format:                       "delta",
	},
	{
		Database:                     "s3bigstats",
		Table:                        "osdaccelerometer_raw",
		CustomerIdentificationColumn: "org_id",
		Group:                        "s3bigstats",
		Format:                       "delta", // Verified on Amundsen
	},
	{
		Database:                     "dataprep_ml",
		Table:                        "dashcam_images",
		CustomerIdentificationColumn: "org_id",
		Group:                        "datapipelines",
		Format:                       "delta",
	},
	{
		Database:                     "dataprep",
		Table:                        "osdaccelerometer_event_traces",
		CustomerIdentificationColumn: "org_id",
		Group:                        "notebooks",
		Format:                       "delta",
	},
	// [DataType_SAFETY_EVENTS] score_event_report_v3 data pipeline
	{
		Database:                     "safety_report",
		Table:                        "safety_events",
		CustomerIdentificationColumn: "org_id",
		Group:                        "datapipelines",
		Format:                       "delta",
	},
	{
		Database:                     "safety_report",
		Table:                        "safety_event_labels",
		CustomerIdentificationColumn: "org_id",
		Group:                        "datapipelines",
		Format:                       "delta",
	},
	{
		Database:                     "safety_report",
		Table:                        "safety_event_hourly_agg",
		CustomerIdentificationColumn: "org_id",
		Group:                        "datapipelines",
		Format:                       "delta",
	},
	{
		Database:                     "safety_report",
		Table:                        "safety_event_labels_hourly_agg",
		CustomerIdentificationColumn: "org_id",
		Group:                        "datapipelines",
		Format:                       "delta",
	},
	{
		Database:                     "safety_report",
		Table:                        "safety_event_hourly_agg_v2",
		CustomerIdentificationColumn: "org_id",
		Group:                        "datapipelines",
		Format:                       "delta",
	},
	{
		Database:                     "safety_report",
		Table:                        "trip_with_safety_event_labels",
		CustomerIdentificationColumn: "org_id",
		Group:                        "datapipelines",
		Format:                       "delta",
	},
	{
		Database:                     "safety_report",
		Table:                        "trip_with_safety_event_labels_hourly_agg",
		CustomerIdentificationColumn: "org_id",
		Group:                        "datapipelines",
		Format:                       "delta",
	},
	{
		Database:                     "safety_report",
		Table:                        "trip_speeding",
		CustomerIdentificationColumn: "org_id",
		Group:                        "datapipelines",
		Format:                       "delta",
	},
	{
		Database:                     "safety_report",
		Table:                        "trip_stats_hourly_agg",
		CustomerIdentificationColumn: "org_id",
		Group:                        "datapipelines",
		Format:                       "delta",
	},
	{
		Database:                     "safety_report",
		Table:                        "score_event_report_v3",
		CustomerIdentificationColumn: "org_id",
		Group:                        "datapipelines",
		Format:                       "delta",
	},
	{
		Database:                     "report_staging",
		Table:                        "score_event_report_v3",
		CustomerIdentificationColumn: "org_id",
		Group:                        "datapipelines",
		Format:                       "delta",
	},
	{
		Database:                     "datastreams_history",
		Table:                        "oem_api_data_logs",
		CustomerIdentificationColumn: "org_id",
		Group:                        "datastreams",
		Format:                       "delta",
	},
	{
		Database:                     "datastreams_history",
		Table:                        "driver_assignment_audit_log",
		CustomerIdentificationColumn: "org_id",
		Group:                        "datastreams",
		Format:                       "delta",
	},
	{
		Database:                     "datastreams_history",
		Table:                        "driver_assignment_settings_audit_log",
		CustomerIdentificationColumn: "org_id",
		Group:                        "datastreams",
		Format:                       "delta",
	},
	{
		Database:                     "canonical_distance",
		Table:                        "combined",
		CustomerIdentificationColumn: "org_id",
		Group:                        "datapipelines",
		Format:                       "delta",
	},
	{
		Database:                     "canonical_distance",
		Table:                        "filtered_odometer",
		CustomerIdentificationColumn: "org_id",
		Group:                        "datapipelines",
		Format:                       "delta",
	},
	{
		Database:                     "canonical_distance",
		Table:                        "total_distance",
		CustomerIdentificationColumn: "org_id",
		Group:                        "datapipelines",
		Format:                       "delta",
	},
	{
		Database:                     "kinesisstats_history",
		Table:                        "osdodometer",
		CustomerIdentificationColumn: "org_id",
		Group:                        "kinesisstats",
		Format:                       "delta",
	},
	{
		Database:                     "datastreams_history",
		Table:                        "speed_limit_locations",
		CustomerIdentificationColumn: "org_id",
		Group:                        "datastreams",
		Format:                       "delta",
	},
	{
		Database:                     "datastreams_history",
		Table:                        "speed_spike_detections",
		CustomerIdentificationColumn: "org_id",
		Group:                        "datastreams",
		Format:                       "delta",
	},
	{
		Database:                     "datastreams_history",
		Table:                        "tile_generation_logs",
		CustomerIdentificationColumn: "org_id",
		Group:                        "datastreams",
		Format:                       "delta",
	},
	{
		Database:                     "messagesdb_hashed",
		Table:                        "messages_hashed",
		CustomerIdentificationColumn: "org_id",
		Group:                        "notebooks",
		Format:                       "delta",
	},
}

var AllCARegionDeletionRegistry = []TableDeletionSpec{
	{
		Database:                     "jack_test",
		Table:                        "deletion_test",
		CustomerIdentificationColumn: "org_id",
		Group:                        "notebooks",
		Format:                       "delta",
	},
}
