from datamodel.common.constants import (
    LANGFUSE_CLICKHOUSE_OBSERVATIONS_SCHEMA,
    LANGFUSE_CLICKHOUSE_SCORES_SCHEMA,
    LANGFUSE_CLICKHOUSE_TRACES_SCHEMA,
    MIXPANEL_SCHEMA,
)

# the tables in this dict are sorted by table name - this is enforced in the tests
descriptions: dict[str, dict[str, str]] = {
    "default.auditlog.datahub_beta_tables": {
        "description": "This table contains information about beta tables from certified_tables.",
        "schema": {
            "table_name": "Name of table currently in beta status",
            "expiration_date": "Date when table should be out of beta status",
            "date": "Date of snapshot",
        },
    },
    "default.auditlog.table_freshness": {
        "description": "Determines freshness of tables based on when they were last updated",
        "schema": {
            "table_name": "Name of table in Databricks",
            "poll_date_hour": "Hour that the data was polled",
            "last_update_age_hours": "Time in hours since last update",
            "freshness_slo_hours": "SLO for table as agreed upon within code",
            "poll_type": "Type of event being polled for (values include table_most_recent_event and table_last_updated)",
        },
    },
    "default.customer360.customer_360_snapshot": {
        "description": "State of an org for use in Customer360",
        "schema": {
            "sfdc_id": "Account ID from Salesforce",
            "name": "",
            "Industry": "",
            "ae_id": "User ID for the account executive",
            "ae_name": "Name of the account executive",
            "ae_email": "Email of the account executive",
            "first_purchase_date": "Customer's first purchase date",
            "status": "Current status of the customer e.g. existing customer, open opportunity, assigned, etc.",
            "segment": "Segment of the customer e.g. management, enterprise, etc.",
            "region": "Region of the customer e.g. east, west, central, etc.",
            "billingcity": "",
            "billingpostalcode": "",
            "billingcountry": "",
            "billingcountrycode": "",
            "date_first_trial_shipped": "",
            "lifetime_acv": "Lifetime revenue for the customer",
            "delinquent": "",
            "org_size": "",
            "org_type": "",
            "implementation_consultant": "ID of the customer's implementation consultant.",
            "implementation_consultant_name": "",
            "csm": "ID of the customer's customer success manager.",
            "csm_name": "Name of the customer's customer success manager.",
            "csm_tier": "Tier of the customer e.g. elite, premier, starter, plus.",
        },
    },
    "default.customer360.org_compliance": {
        "description": "Gives a breakdown on org-level compliance",
        "schema": {
            "num_unassigned_segments": "Number of unassigned HoS logs for org",
            "unassigned_driver_time_hours": "Total driver hours that went unassigned",
        },
    },
    "default.customer360.org_dates": {
        "description": "First heartbeat date for orgs",
        "schema": {
            "org_id": "",
            "sam_number": "",
            "first_heartbeat_date": "Minimum first heartbeat date for a device within the org",
            "date": "",
        },
    },
    "default.data_analytics.api_mappings": {
        "description": "API paths that can be accessed",
        "schema": {
            "api_category": "Type of API being accessed",
            "specialized_category": "More descriptive category (if api_category is Specialized APIs)",
            "expected_rate_limit_tier": "Limit on API requests",
            "http_method": "HTTP method for requests",
            "path_template": "Path being accessed",
            "Concat": "Combination of http_method and path_template",
        },
    },
    "default.data_analytics.cm_device_settings": {
        "description": "Provides a breakdown on CM devices within an org",
        "schema": {
            "date": "",
            "org_id": "",
            "org_name": "",
            "has_octo": "Whether org has an Octo connection or not",
            "total_online_cm31": "",
            "total_online_cm32": "",
            "total_online_cm33": "",
            "total_online_cm34": "",
            "total_online_ahd1": "",
            "total_online_ahd4": "",
            "cm_brigid_mix": "Values include CM Only (if only CM31/CM32), Brigid Only (if only CM33/CM34), Mixed (if both), or Not Online if devices are not online",
            "inward_outward_mix": "Values include Outward Only (if only CM31/CM33), Inward/Outward Only (if only CM32/CM34), Mixed (if both), or Not Online if devices are not online",
            "locale": "",
            "account_industry": "",
            "account_size_segment_name": "",
            "account_cs_tier": "",
            "settings_url": "Settings URL in Cloud dashboard for cameras",
            "cm31_cm32_ahd1_storage_hours_setting": "Storage hours setting for CM31/CM32/AHD1s",
            "cm33_cm34_storage_hours_setting": "Storage hours setting for CM33/CM34s",
            "high_res_storage_percent_setting": "Whether high res storage is enabled or not",
            "pm_duration_hours": "How long parking mode is enabled for (in hours)",
            "audio_recording_enabled": "Whether audio recording is enabled or not",
            "camera_id_enabled": "Whether the Camera ID feature is enabled or not",
            "camera_id_confirmation_mode_enabled": "Which type of confirmation mode is enabled",
            "camera_id_autoassignment_groups_enabled": "Whether autoassignment groups are enabled or not",
            "livestream_enabled": "Whether livestreaming features are enabled or not",
            "livestream_outward_camera_enabled": "Whether livestreaming is enabled for outward cameras or not",
            "livestream_inward_camera_enabled": "Whether livestreaming is enabled for inward cameras or not",
            "livestream_audio_stream_enabled": "Whether livestreaming is enabled with audio or not",
            "livestream_allowance_min": "Allowed time for livestreaming (in minutes)",
            "connection_duration_minutes_rolling30days": "Connection duration (in minutes) over last 30 days",
            "livestream_usage_pct": "Usage percentage of livestreaming (based on allowance and connection duration)",
        },
    },
    "default.data_analytics.cm_memory_usage": {
        "description": "Memory usage stats for CM devices",
        "schema": {
            "date": "",
            "org_id": "",
            "device_id": "ID of the CM device",
            "99th_percentile_memory_usage": "99th percentile of memory usage for the CM device during the timespan",
            "median_memory_usage": "Median memory usage for the CM device during the timespan",
        },
    },
    "default.data_analytics.dataprep_vg3x_daily_health_metrics": {
        "description": "Daily health metrics on VG3x devices",
        "schema": {
            "date": "",
            "org_id": "",
            "org_type": "",
            "org_name": "",
            "device_id": "",
            "product_type": "",
            "latest_build_on_day": "Latest build version for given day",
            "status": "Possible values are Alive and Active, based on trips",
            "has_modi": "Whether VG has a Modi connection (Diagnostics bus) or not",
            "has_baxter": "Whether VG has a Baxter connection or not",
            "has_octo": "Whether VG has an Octo connection or not",
            "trip_count": "Total number of trips taken by the device",
            "total_distance_meters": "Total distance (in meters) covered by the device",
            "product_version": "Software version of product",
            "rollout_stage_id": "Rollout stage of device",
            "product_program_id": "",
            "product_program_type": "",
            "99th_percentile_memory_usage": "99th percentile of memory usage for the VG",
            "median_memory_usage": "Median memory usage for the VG",
            "gw_first_heartbeat_date": "First heartbeat date for the VG",
            "gw_last_heartbeat_date": "Last heartbeat date for the VG",
            "oom_count": "Count of OOM errors",
            "battery_status": "Battery status of the VG",
        },
    },
    "default.data_analytics.octo_anomalies": {
        "description": "Error/anomaly details on Octo connections",
        "schema": {
            "date": "",
            "start_ms": "Start of interval",
            "end_ms": "End of interval",
            "octo_total_anomalies": "Total anomalies detected",
            "octo_runtime_errors": "Runtime errors",
            "octo_kernel_errors": "Kernel errors",
            "octo_negative_one_errors": "Event -1 received errors within the Octo connection",
            "octo_anomaly_event_service_count": "Count of service names that have errors associated with them",
        },
    },
    "default.data_analytics.octo_auxcam_on_trip_disconnect_w_power": {
        "description": "Disconnect events for Octo Auxcams",
        "schema": {
            "trip_start_date": "",
            "trip_start_ms": "",
            "trip_end_ms": "",
            "auxcam_disconnect_start_ms": "Start time in milliseconds of disconnect event",
            "auxcam_disconnect_end_ms": "End time in milliseconds of disconnect event",
            "auxcam_disconnect_duration_min": "Duration of disconnect event in minutes",
            "auxcam_disconnect_gt_15min": "Whether disconnect event lasted more than 15 minutes",
        },
    },
    "default.data_analytics.octo_bootup_time": {
        "description": "Boot events for Octo connections",
        "schema": {
            "date": "",
            "vg_started_on": "Timestamp at which VG was started",
            "octo_started_on": "Timestamp at which Octo was started",
            "bootup_time_sec": "Time in seconds for Octo to boot up",
            "boot": "Boot type (cold/warm)",
        },
    },
    "default.data_analytics.octo_build_and_bootcount": {
        "description": "This table contains build and bootcount metrics for each Octo-VG interval.",
        "schema": {
            "vg_bootcount": "Number of times VG booted during interval",
            "vg_build": "Build version of VG",
            "octo_bootcount": "Number of times Octo booted during interval",
            "octo_build": "Build version of Octo",
        },
    },
    "default.data_analytics.octo_cm_stills": {
        "description": "Octo still capture events",
        "schema": {
            "date": "",
            "org_id": "",
            "cm_device_id": "",
            "octo_deviceid": "",
            "unix_trigger_time_ms": "Time at which still was captured",
            "octo_captured": "Whether there's an associated Octo for the still or not",
        },
    },
    "default.data_analytics.octo_hvr_e2e_duration": {
        "description": "Octo Historical Video Request events with associated duration",
        "schema": {
            "date": "",
            "org_id": "",
            "octo_device_id": "",
            "hvr_id": "ID of video request",
            "created_at_ms": "",
            "asset_ready_at_ms": "Timestamp at which asset was ready",
            "completed_at_ms": "",
            "octo_receive_request_time_ms": "Time in milliseconds at which Octo received result",
            "time_from_retrieve_to_uploadcomplete_minutes": "Time from retrieve to upload completed (minutes)",
            "total_time_to_retrieve_and_upload_minutes": "Total time to retrieve and upload video (minutes)",
        },
    },
    "default.data_analytics.octo_linked_vgs": {
        "description": "Table contains the VG<->Octo device ID pairs for Ocoto 1x and includes additional data like the org name, type and Octo Product ID",
        "schema": {
            "start_at": "Timestamp at which pairing started",
            "start_at_ms": "Time in milliseconds at which pairing started",
            "end_at": "Timestamp at which pairing ended (will be null if still active)",
            "end_at_ms": "Time in milliseconds at which pairing ended (will be null if still active)",
        },
    },
    "default.data_analytics.octo_on_trip_disconnect_w_power": {
        "description": "Disconnect events for Octo connections",
        "schema": {
            "trip_start_date": "",
            "trip_start_ms": "",
            "trip_end_ms": "",
            "octo_disconnect_start_ms": "Start time in milliseconds of disconnect event",
            "octo_disconnect_end_ms": "End time in milliseconds of disconnect event",
            "octo_disconnect_duration_min": "Duration of disconnect event in minutes",
            "octo_disconnect_gt_15min": "Whether disconnect event lasted more than 15 minutes",
        },
    },
    "default.data_analytics.octo_overheating_durations": {
        "description": "Overheating durations for VG-Octo pairings",
        "schema": {
            "date": "",
            "trip_start_ms": "",
            "trip_end_ms": "",
            "trip_duration_ms": "",
            "overheated_duration_ms": "Duration that Octo-VG pairing was overheated during trip",
            "overheated_count": "Count of overheating events during the trip",
        },
    },
    "default.data_analytics.octo_parking_mode_recording_durations": {
        "description": "Parking mode events for Octo-VG pairings",
        "schema": {
            "date": "",
            "org_id": "",
            "octo_deviceid": "",
            "parking_mode_enabled": "Whether parking mode was enabled or not",
            "pm_start_ms": "Start time in milliseconds of parking mode",
            "pm_end_ms": "End time in milliseconds of parking mode",
            "pm_duration_ms": "Duration of parking mode in milliseconds",
            "recording_duration_ms": "Recording duration during parking mode (if any)",
        },
    },
    "default.data_analytics.octo_recording_durations": {
        "description": "Recording durations for Octo connections",
        "schema": {
            "duration_ms": "Total time in interval",
            "interval_connected_duration": "How long Octo was connected during the interval",
            "recording_duration_ms": "Total time spent recording within interval",
        },
    },
    "default.data_analytics.octo_report": {
        "description": "Details on Octo connections",
        "schema": {
            "octo_serial": "",
            "org_name": "",
            "octo_last_online_datetime": "Timestamp at which Octo was last online",
            "octo_first_online_datetime": "Timestamp at which Octo was first online",
            "vg_serial": "Serial of connected VG device",
            "vg_deviceid": "",
            "vehicle_name": "Name of connected VG",
            "vin": "VIN of VG",
            "make": "Make of the VG associated with the Octo device",
            "model": "Model of the VG associated with the Octo device",
            "year": "Year of the VG associated with the Octo device",
            "vg_last_online_date": "Date at which VG was last online",
            "camera_serial": "Serial of CM device (if any)",
            "last_reported_city": "Last known city of pairing",
            "last_reported_state": "Last known state of pairing",
            "miles_driven": "",
            "VG_Cloud_link": "Link to corresponding VG device",
        },
    },
    "default.data_analytics.octo_resolution_durations": {
        "description": "How long Octo connections were in various recording states",
        "schema": {
            "resolution": "Resolution quality used in recording",
            "total_recording_time_hrs": "Total time spend recording (in hours) for specified resolution",
        },
    },
    "default.data_analytics.octo_safe_mode_durations": {
        "description": "Safe mode durations for VG-Octo pairings",
        "schema": {
            "date": "",
            "trip_start_ms": "",
            "trip_end_ms": "",
            "trip_duration_ms": "",
            "safe_mode_duration_ms": "Duration that pairing was in safe mode during trip",
            "safe_mode_count": "Count of safe mode events during the trip",
        },
    },
    "default.data_analytics.octo_safety_harsh_events": {
        "description": "Harsh events detected by Octo",
        "schema": {
            "date": "",
            "event_ms": "",
            "event_id": "Event ID for harsh event",
            "accel_type": "Acceleration type of harsh event",
            "uploaded_file_set": "Uploaded files (if any) from event",
            "successful_file_upload": "True/false depending on if file set is empty or not",
        },
    },
    "default.data_analytics.octo_still_uploads": {
        "description": "Octo still upload events",
        "schema": {
            "date": "",
            "org_id": "",
            "octo_deviceid": "",
            "logged_time": "Time of upload event",
            "event_id": "ID of upload event",
            "report_type": "Type of report being uploaded",
            "upload_duration_ms": "",
            "total_upload_duration_ms": "",
            "upload_attempts": "",
        },
    },
    "default.data_analytics.octo_time_to_first_frame": {
        "description": "Time for Octo connections to receive their first frame",
        "schema": {
            "date": "",
            "org_id": "",
            "time": "",
            "engine_state": "",
            "recording_start_ms": "Start time in milliseconds of recording",
            "already_recording": "Whether camera was already recording or not",
            "seconds_to_first_frame": "Seconds between engine start and recording",
        },
    },
    "default.data_analytics.octo_time_to_last_frame": {
        "description": "Time for Octo connections to receive their last frame",
        "schema": {
            "date": "",
            "org_id": "",
            "time": "",
            "engine_state": "",
            "contains_pm_interval": "Whether recording contains a parking mode interval or not",
            "engine_off_after_recording": "Time at which engine was turned off after recording",
            "engine_off_after_recording_during_disconnect": "Whether Octo was disconnected at any point during this process",
            "time_to_last_frame_minutes": "Time to the final frame of the recording (in minutes)",
        },
    },
    "default.data_analytics.octo_vg_cm_connections": {
        "description": "Shows the association between VG/Octo/CM",
        "schema": {
            "vg_build": "Build version of VG",
            "octo_build": "Build version of Octo",
            "cm_build": "Build version of CM",
        },
    },
    "default.data_analytics.octo_vg_cpu_usage": {
        "description": "CPU usage for VG-Octo pairings",
        "schema": {
            "org_id": "",
            "date": "",
            "avg_octo_vg_total_cpu_usage": "Daily average CPU usage for VG-Octo pairing",
        },
    },
    "default.data_analytics.platform_token": {
        "description": "API call stats for different integrations",
        "schema": {
            "monthly_calls": "Total number of API calls made",
            "unique_integration": "API integration name",
        },
    },
    "default.data_analytics.speed_alert_two_distance": {
        "description": "Speeding events on trips",
        "schema": {
            "total_distance_miles": "Total distance covered during trip",
            "num_events": "Number of speeding events that occurred in the state of question for that org",
        },
    },
    "default.data_analytics.speed_incab_alerts_distance": {
        "description": "Speeding and incab alert events",
        "schema": {
            "date": "",
            "org_id": "",
            "org_name": "",
            "account_size_segment_name": "",
            "account_industry": "",
            "state": "Starting state of trip",
            "country": "Starting country of trip",
            "total_distance_miles": "Total distance covered during speeding events",
            "num_incab_alerts": "Number of incab alerts triggered during speeding events",
        },
    },
    "default.data_analytics.speed_limit_overrides": {
        "description": "Speed limit overrides for drivers",
        "schema": {
            "org_id": "",
            "date": "",
            "created_at_ms": "Timestamp at which override was created",
            "revgeo_state": "State in which override is taking place",
            "revgeo_country": "Country in which override is taking place",
            "original_speed_limit_milliknots": "Original speed limit value in milliknots",
            "override_speed_limit_milliknots": "Override speed limit value in milliknots",
            "original_speed_limit_mph": "Original speed limit value in mph",
            "override_speed_limit_mph": "Override speed limit value in mph",
        },
    },
    "default.data_analytics.speed_limit_overrides_distance": {
        "description": "Speeding limit override events, along with associated distance",
        "schema": {
            "date": "",
            "org_id": "",
            "org_name": "",
            "account_size_segment_name": "",
            "account_industry": "",
            "state": "State in which trip originated",
            "country": "Country in which trip originated",
            "total_distance_miles": "Total distance covered during speeding events",
            "num_overrides": "Number of speeding limit overrides",
        },
    },
    "default.data_analytics.speeding_events_distance": {
        "description": "Speeding events on trips",
        "schema": {
            "total_distance_miles": "Total distance covered during trip",
            "num_events": "Number of speeding events that occurred in the state of question for that org",
        },
    },
    "default.data_analytics.traveled_ways": {
        "description": "Recently traveled ways",
        "schema": {
            "way_id": "ID of OSRM way",
            "revgeo_state": "State in which way is located",
            "revgeo_country": "Country in which way is located",
        },
    },
    "default.data_analytics.vg3x_daily_summary": {
        "description": "Daily summary of devices in the VG3x series",
        "schema": {
            "date": "",
            "org_id": "",
            "org_name": "",
            "org_type": "",
            "device_id": "",
            "latest_gateway_id": "ID of latest gateway associated with device",
            "serial": "",
            "product_id": "",
            "camera_product_id": "Product ID of camera associated with VG",
            "active_builds_on_day": "Number of active builds on the day in question",
            "latest_build_on_day": "Latest build on the day in question",
            "trip_count": "Total number of trips taken",
            "total_distance_meters": "Total distance traveled in meters",
            "has_modi": "Whether VG has a Modi (Diagnostics bus) or not",
            "has_baxter": "Whether VG has a Baxter connection or not",
            "has_octo": "Whether VG has an Octo connection or not",
            "product_version": "",
            "rollout_stage_id": "",
            "product_program_id": "",
            "product_program_type": "",
        },
    },
    "default.data_analytics.vg_cpu_usage": {
        "description": "Details on VG device CPU usage",
        "schema": {
            "date": "",
            "org_id": "",
            "device_id": "",
            "95th_percentile_cpu_usage": "95th percentile CPU reading for a given device",
            "median_cpu_usage": "Median CPU reading for a given device",
        },
    },
    "default.data_analytics.vg_hardware_variant_info": {
        "description": "Context on VG hardware",
        "schema": {
            "product_id": "Product ID of gateway",
            "bom_version": "BOM version of VG",
            "build_phase": "Build phase for VG software",
            "product_version": "Product version of VG",
        },
    },
    "default.data_analytics.widget_daily_summary": {
        "description": "Daily summary of existing widgets",
        "schema": {
            "date": "",
            "org_id": "",
            "org_name": "",
            "org_type": "",
            "widget_id": "",
            "product_type": "",
            "serial": "",
            "first_connection_date": "First date the widget made a connection",
            "last_connection_date": "Latest date where the widget made a connection",
        },
    },
    "default.dataengineering.osdcm3xpowerstats_intervals": {
        "description": "Power stats on CM3x devices",
        "schema": {
            "date": "",
            "stat_type": "",
            "org_id": "",
            "object_id": "",
            "start_ms": "",
            "start_ms_human": "Start time as timestamp",
            "end_ms": "",
            "end_ms_human": "End time as timestamp",
            "product_id": "",
            "product_name": "",
            "usb_system_power_now_uw": "Power reading from USB system",
            "battery_voltage_now_uv": "Battery voltage reading",
        },
    },
    "default.dataengineering.osdcm3xthermalsensors_intervals": {
        "description": "Thermal sensor readings on CM3x devices",
        "schema": {
            "date": "",
            "stat_type": "",
            "org_id": "",
            "object_id": "",
            "product_id": "",
            "product_name": "",
            "start_ms": "",
            "start_ms_human": "Start time as timestamp",
            "end_ms": "",
            "end_ms_human": "End time as timestamp",
            "soc_temp_milli_degree_c": "Temperature reading on chip",
            "emmc_temp_milli_degree_c": "Embedded multi media card temperature reading",
            "road_cam_temp_milli_degree_c": "Road cam temperature reading",
            "driver_cam_temp_milli_degree_c": "Driver cam temperature reading",
        },
    },
    "default.dataengineering.osdsystemstats_intervals": {
        "description": "Memory/CPU stats on Bridgid devices",
        "schema": {
            "date": "",
            "stat_type": "",
            "org_id": "",
            "object_id": "",
            "start_ms": "",
            "start_ms_human": "Start time as timestamp",
            "end_ms": "",
            "end_ms_human": "End time as timestamp",
            "product_id": "",
            "product_name": "",
            "total_cpu_util": "CPU utilization within interval",
            "memory_util": "Memory utilization within interval",
            "vector_processor_usage_millipercent": "Vector processing usage reading at interval",
        },
    },
    "default.dataprep.firmwares_rollout_stage": {
        "description": "Frimware release and rollout details",
        "schema": {
            "date": "",
            "rollout_stage": "Stage of a rollout/release",
            "product_id": "",
            "product_firmware_id": "Firmware ID for product",
            "product_program_id": "ID of program behind firmware",
        },
    },
    "default.dataprep_telematics.vg_fleet_diagnostics_latest": {
        "description": "Diagnostic readings for VGs",
        "schema": {
            "org_name": "",
            "org_id": "",
            "object_id": "",
            "product_id": "",
            "serial": "",
            "device_name": "",
            "make": "",
            "model": "",
            "year": "",
            "engine_model": "",
            "primary_fuel_type": "",
            "engine_manufacturer": "",
            "has_ecm_vin": "Whether the device has a VIN reading or not",
            "has_ecm_odo": "Whether the device has an odometer reading or not",
            "has_ecm_enginehours": "Whether the device has an engine hours reading or not",
            "cable_id": "",
            "cable_name": "",
            "ecm_vin_value": "Latest VIN reading value",
            "ecm_odometer_value": "Latest odometer reading",
            "ecm_engine_hour_value": "Latest engine hours reading",
            "first_vin_date": "Date of first VIN reading within last week",
            "last_vin_date": "Date of last VIN reading within last week",
            "fuel_level_value": "Latest fuel level reading",
            "fuel_consumption_value": "Latest fuel consumption reading",
            "first_fuel_consumption_date": "Date of first fuel consumption within last week",
            "last_fuel_consumption_date": "Date of latest fuel consumption within last week",
            "seatbelt_value": "Latest seatbelt reading for vehicle",
            "battery_voltage_value": "Latest voltage reading for vehicle",
            "first_odometer_date": "Date of first odometer reading within last week",
            "last_odometer_date": "Date of latest odometer reading within last week",
            "first_engine_hour_date": "Date of first engine hour reading within last week",
            "last_engine_hour_date": "Date of latest engine hour reading within last week",
            "last_belt_date": "Date of latest seatbelt reading within last week",
            "last_fuel_level_date": "Date of latest fuel level reading within last week",
            "first_heartbeat": "Date of first heartbeat reading within last week",
            "last_heartbeat": "Date of latest heartbeat reading within last week",
            "first_trip_date": "Date of first trip within last week",
            "last_trip_date": "Date of latest trip within last week",
            "vin_value": "Value of latest VIN reading",
            "ecm_vin_detected": "Whether there's a latest VIN value or not",
            "ecm_odometer_detected": "Whether there's a latest odometer value or not",
            "ecm_engine_hours_detected": "Whether there's a latest engine hours value or not",
            "fuel_level_detected": "Whether there's a latest fuel level value or not",
            "fuel_consumption_detected": "Whether there's a latest fuel consumption value or not",
            "seatbelt_detected": "Whether there's a latest seatbelt value or not",
            "org_type": "",
            "link": "Link to VG device in Cloud dashboard",
        },
    },
    "default.definitions.oem_type_name": {
        "description": "Lookup file for OEM (Original Equipment Manufacturer) types",
        "schema": {
            "id": "ID of OEM",
            "name": "Associated name of OEM",
        },
    },
    "default.dojo.chatbot_response_categorization": {
        "description": "Categorizes chatbot responses by response type to track chatbot performance and response quality. Each record represents a categorized chatbot response with the reasoning for the categorization.",
        "schema": {
            "trace_id": "Unique identifier for the chatbot conversation trace",
            "response_type": "Type of response provided by the chatbot (e.g., data_provided, fallback_not_found, fallback_unsupported, followup_clarification, fallback_permission, error)",
            "reason": "Detailed explanation for why the response was categorized with this response_type",
            "date": "Date of the trace",
        },
    },
    "default.dojo.chatbot_usecase_categorization": {
        "description": "Categorizes user queries and use cases submitted to the chatbot to understand user intent and usage patterns. Each record represents a categorized user query with the reasoning for the categorization.",
        "schema": {
            "trace_id": "Unique identifier for the chatbot conversation trace",
            "usecase_type": "Type of use case or intent identified in the user query (e.g., safety_scores_ranking, navigation, location, mileage_odometer, unclear, or combinations thereof)",
            "reason": "Detailed explanation for why the query was categorized with this usecase_type",
            "date": "Date of the trace",
        },
    },
    "default.dojo.dev_langfuse_clickhouse_dataset_run_items": {
        "description": "Dev environment (US only) Langfuse dataset run items data sourced from ClickHouse, representing evaluation metrics for dataset runs.",
        "schema": {
            "id": "Unique identifier for the dataset run item record",
            "project_id": "Langfuse project identifier, consistent across all Langfuse tables",
            "dataset_run_id": "Identifier for the specific dataset run this item belongs to",
            "dataset_item_id": "Identifier for the dataset item being evaluated in this run",  # Source: Schema definition and usage in dataset_to_csv.py
            "dataset_id": "Identifier for the dataset containing this item",
            "trace_id": "Foreign key to dojo.dev_langfuse_clickhouse_traces.id - links to the trace generated for this dataset item",
            "observation_id": "Foreign key to dojo.dev_langfuse_clickhouse_observations.id - links to the observation within the trace",
            "error": "Error message if the dataset item evaluation failed, null if successful",
            "created_at": "Timestamp when this dataset run item record was created in Langfuse",
            "updated_at": "Timestamp when this dataset run item record was last updated in Langfuse",
            "dataset_run_name": "Human-readable name of the dataset run",
            "dataset_run_description": "Optional description of the dataset run",
            "dataset_run_metadata": "Key-value metadata associated with the dataset run",
            "dataset_run_created_at": "Timestamp when the dataset run was created in Langfuse",
            "dataset_item_input": "JSON string containing the input data for this dataset item",
            "dataset_item_expected_output": "JSON string containing the expected output for this dataset item",
            "dataset_item_metadata": "Key-value metadata associated with the dataset item",
            "event_ts": "Event timestamp from the original Langfuse event",
            "is_deleted": "Soft delete flag (0=active, 1=deleted)",
            "date": "Partition column in YYYY-MM-DD format, derived from dataset_run_created_at for data partitioning",
        },
    },
    "default.dojo.dev_langfuse_clickhouse_observations": {
        "description": "Dev environment (US only) Langfuse observations sourced from ClickHouse, tracking individual LLM calls, generations, and spans within AI application traces.",
        "schema": LANGFUSE_CLICKHOUSE_OBSERVATIONS_SCHEMA,
    },
    "default.dojo.dev_langfuse_clickhouse_scores": {
        "description": "Dev environment (US only) Langfuse score objects sourced from ClickHouse, capturing evaluation metrics (trace/observation level) with context, metadata, and source.",
        "schema": LANGFUSE_CLICKHOUSE_SCORES_SCHEMA,
    },
    "default.dojo.dev_langfuse_clickhouse_traces": {
        "description": "Dev environment (US only) Langfuse trace data sourced from ClickHouse, representing complete AI application workflows or user sessions.",
        "schema": LANGFUSE_CLICKHOUSE_TRACES_SCHEMA,
    },
    "default.dojo.device_trip_stats": {
        "description": "Tracks daily mileage and driving time per device",
        "schema": {
            "date": "",
            "drive_time_hours": "",
            "driven_distance_miles": "",
            "org_id": "",
            "trip_count": "",
            "vg_id": "",
        },
    },
    "default.dojo.langfuse_all_observations": {
        "description": "Unified view of Langfuse observations (spans, events, generations) sourced from both ClickHouse and RDS, supporting rich observability.",
        "schema": {
            "id": "Unique observation ID (e.g. span or event identifier)",
            "trace_id": "Trace ID grouping related observations within a request",
            "project_id": "Langfuse project identifier",
            "environment": "Deployment environment (e.g. default); null for RDS observations",
            "type": "Observation type: GENERATION, SPAN, EVENT (rare)",
            "parent_observation_id": "Identifier for parent span or observation, enabling nested structure",
            "start_time": "Observation start time",
            "end_time": "Observation end time (duration endpoint)",
            "name": 'Descriptive name of the observation (e.g. "process-event-summarization", "gpt-4.1-mini", "litellm-acompletion")',
            "metadata": "JSON metadata at observation level (arbitrary key-value context)",
            "level": "Log verbosity level: DEFAULT, ERROR, DEBUG",
            "status_message": "Optional status or error message to accompany level",
            "version": "Version or release of the instrumentation at observation creation",
            "input": "Input data captured for this observation (e.g. prompt, function input)",
            "output": "Output data captured (e.g. LLM response or result)",
            "provided_model_name": 'Model name provided at observation time (e.g. "gpt-4.1-mini-2025-04-14", "gpt-4o-mini", "Qwen/Qwen2.5-VL-32B-Instruct")',
            "internal_model_id": "Internal/instrumentation model identifier",
            "model_parameters": "Model parameters (e.g. temperature, max_tokens)",
            "provided_usage_details": "Reported token usage (input/output) if provided; null for RDS observations",
            "usage_details": "Structured usage details (Langfuse SDK parsed); null for RDS observations",
            "provided_cost_details": "Raw cost info if directly provided; null for RDS observations",
            "cost_details": "Structured cost breakdown as captured by Langfuse instrumentation; null for RDS observations",
            "total_cost": "DO NOT USE THIS FIELD, USE calculated_total_cost INSTEAD",
            "calculated_total_cost": "Total cost incurred for the observation (double precision) calculated from the provided_cost_details",
            "completion_start_time": "Time when LLM completion began",
            "prompt_id": "Identifier for a defined prompt template or prompt usage",
            "prompt_name": "Name of the prompt template (if available); null for RDS observations",
            "prompt_version": "Prompt version (if tracked); null for RDS observations",
            "created_at": "Record insertion timestamp",
            "updated_at": "Record last updated timestamp",
            "event_ts": "Event timestamp as recorded in ClickHouse (if available); null for RDS observations",
            "is_deleted": "Soft-delete flag (1 = deleted) from ClickHouse only; null for RDS observations",
            "date": "Partition date for storage",
            "source_system": "Source of observation: clickhouse or rds",
        },
    },
    "default.dojo.langfuse_all_scores": {
        "description": "Unified view of Langfuse score objects from both ClickHouse and RDS, capturing evaluation metrics (trace/observation/session/dataset-run level) with context, metadata, cost, and source.",
        "schema": {
            "id": "Unique score identifier",
            "timestamp": "Timestamp when the score was recorded",
            "project_id": 'Langfuse project identifier (e.g. "clv7bsfr9000110zwxcg8aftp")',
            "environment": 'Deployment environment (e.g. "default"); null for RDS source',
            "trace_id": "Trace ID that this score is associated with",
            "observation_id": "Observation ID that this score is associated with",
            "name": 'Score metric name (e.g. "time_to_first_token_seconds", "feedback_vote", "auto-categorization", "reasonable answer")',
            "value": "Numeric score value (double precision)",
            "source": 'Source of the score: "API" (most common), "ANNOTATION" (RDS only)',
            "comment": "Optional comment or description for the score",
            "author_user_id": "User ID who created or provided the score",
            "config_id": "Configuration identifier for the scoring criteria",
            "data_type": 'Data type of the score: "NUMERIC" (most common), "CATEGORICAL", "BOOLEAN" (RDS only)',
            "string_value": "String representation of the score value (if applicable)",
            "queue_id": "Queue identifier for batch processing",
            "created_at": "Record creation timestamp",
            "updated_at": "Record last update timestamp",
            "event_ts": "Event timestamp from Clickhouse data source; null for RDS observations",
            "is_deleted": "Soft-delete flag (Clickhouse only): 1 = deleted; null for RDS observations",
            "date": "Partition date",
            "source_system": "Source of score data: clickhouse or rds",
        },
    },
    "default.dojo.langfuse_all_traces": {
        "description": "Unified view of Langfuse trace data from both Clickhouse and RDS sources. Provides a consistent schema for analytics and downstream processing.",
        "schema": {
            "id": "Unique trace identifier (e.g. UUID or user-supplied traceId)",
            "timestamp": "Timestamp when the trace was recorded (trace start time)",
            "name": 'Descriptive name of the trace (e.g. "inbox-summ", "litellm-acompletion", "OwlQuery async", "OpenAI-generation")',
            "user_id": "Identifier for the user associated with the trace-enables per-user observability",
            "metadata": "Arbitrary JSON metadata at trace level (e.g. request ID, source, version)",
            "release": 'Release or application version associated with the trace (e.g. "build:heads/main-0-gb66e089c4", "build:tags/release/owlchat/0.23.3-0-gafe186871")',
            "version": 'Semantic version of your application or component (e.g. "1.0")',
            "project_id": 'Langfuse project identifier (e.g. "cm4buoaqw0007wx4siqknz10n", "cmagxi7ba000689084u99jygf")',
            "environment": "Deployment environment (e.g. default); null for RDS source",
            "public": "Visibility flag-whether the trace is publicly shareable",
            "bookmarked": "Flag indicating if a trace was bookmarked for review or follow-up",
            "tags": "Trace-level tags used for filtering and organization in the UI/API",
            "input": "Input to the traced operation (e.g. prompt or request payload)",
            "output": "Output of the operation (e.g. LLM response, result)",
            "session_id": "Session identifier grouping related traces (e.g. conversation or user flow)",
            "created_at": "Record creation timestamp",
            "updated_at": "Record last update timestamp",
            "event_ts": "Optional event timestamp from Clickhouse data source; null for RDS observations",
            "is_deleted": "Soft-delete flag (Clickhouse only): 1 = deleted; null for RDS observations",
            "date": "Partition date",
            "source_system": "Source of trace data: clickhouse or rds",
        },
    },
    "default.dojo.langfuse_clickhouse_observations": {
        "description": "Langfuse observations sourced from ClickHouse, tracking individual LLM calls, generations, and spans within AI application traces. Raw ClickHouse data before unification in langfuse_all_observations.",
        "schema": LANGFUSE_CLICKHOUSE_OBSERVATIONS_SCHEMA,
    },
    "default.dojo.langfuse_clickhouse_scores": {
        "description": "Langfuse score objects sourced from ClickHouse, capturing evaluation metrics (trace/observation level) with context, metadata, and source. Raw ClickHouse data before unification in langfuse_all_scores.",
        "schema": LANGFUSE_CLICKHOUSE_SCORES_SCHEMA,
    },
    "default.dojo.langfuse_clickhouse_traces": {
        "description": "Langfuse trace data sourced from ClickHouse, representing complete AI application workflows or user sessions. Raw ClickHouse data before unification in langfuse_all_traces.",
        "schema": LANGFUSE_CLICKHOUSE_TRACES_SCHEMA,
    },
    "default.inference_store.device_known_locations": {
        "description": "Clustered known stop locations identified using DBSCAN clustering from trip data. Each row represents one known location cluster for an organization. Derived from datamodel_telematics.fct_trips using H3 spatial indexing. Refreshed daily. Note: Only includes stops with duration > 10 minutes and trips > 500 meters.",
        "schema": {
            "org_id": "Organization ID. Foreign key to dim_organizations.org_id. Sourced from fct_trips.",
            "latitude": "Median latitude of cluster centroid in WGS84 (EPSG:4326) decimal degrees. Computed as median of end_latitude values within the cluster. Valid range: -90 to 90.",
            "longitude": "Median longitude of cluster centroid in WGS84 (EPSG:4326) decimal degrees. Computed as median of end_longitude values within the cluster. Valid range: -180 to 180.",
            "number_of_stops": "Total count of trip stops within this cluster location. Aggregated from trip_count_for_end_coords across all stop coordinates in the cluster.",
            "lookback_days": "Number of historical days used for clustering this organization's data. Dynamically calculated based on org's daily stop volume to stay within processing limits (max 2M stops). Capped at 365 days maximum.",
            "polygon": "GeoJSON Polygon representing the cluster boundary. Struct with type (always 'Polygon') and coordinates (array of coordinate rings). Coordinates are in [longitude, latitude] order per GeoJSON spec. Polygon is guaranteed to be closed (first point equals last point).",
            "polygon.type": "GeoJSON geometry type. Always 'Polygon' for this table.",
            "polygon.coordinates": "Array of coordinate rings defining the polygon boundary. Each ring is an array of [longitude, latitude] coordinate pairs in WGS84. First and last coordinates are identical (closed polygon). Derived from H3 cell boundaries at resolution 10.",
            "polygon_area": "Area of the cluster polygon in square meters. Computed using WGS84 ellipsoid geodesic calculation via pyproj. Larger values indicate more spread-out stop locations.",
            "driver_id_counts": "Map of driver IDs to their stop counts within this cluster. Type: Map<INT64, INT32>. Keys are driver_id values (0 indicates unassigned driver), values are number of stops made by that driver at this location.",
            "cluster_idx": "Unique cluster identifier within an organization, assigned by DBSCAN algorithm. Values start at 0 and increment sequentially. Note: Noise points (cluster_idx = -1) are excluded from this table.",
            "date": "Date when clustering was computed. Format: YYYY-MM-DD. Partition column for table storage. Table is overwritten daily with fresh clustering results.",
        },
    },
    "default.metrics_repo.custom_role_orgs_count": {
        "description": "(Regional) The total number of orgs having a user with at least one custom role",
        "schema": {
            "user_count": "Number of users with a custom role",
            "fraction_custom_role": "Fraction of users in the org with a custom role",
        },
    },
    "default.metrics_repo.device_tags_attributes_count": {
        "description": "(Regional) The percent of devices with at least one tag and at least one attribute",
        "schema": {
            "tags_size": "Number of tags for a given device",
            "attributes_size": "Number of attributes for a given device",
        },
    },
    "default.metrics_repo.devices_active_count": {
        "description": "(Global) Devices with either a heartbeat or a heartbeat/trip. For VGs and CMs, we use the heartbeat/trip combo, while other devices just need a heartbeat to be considered active.",
        "schema": {
            "is_device_active": "Whether the device is active or not",
            "device_id": "The ID of the customer device that the data belongs to",
        },
    },
    "default.metrics_repo.devices_online_count": {
        "description": "(Global) Devices with at least one heartbeat.",
        "schema": {
            "is_device_online": "Whether the device has a heartbeat or not",
            "device_id": "The ID of the customer device that the data belongs to",
        },
    },
    "default.metrics_repo.driver_tags_attributes_count": {
        "description": "(Regional) The percent of drivers with at least one tag and at least one attribute",
        "schema": {
            "driver_id": "The ID of the driver that the data belongs to",
            "tags_size": "Total number of tags for the driver",
            "attributes_size": "Total number of attributes for the driver",
        },
    },
    "default.metrics_repo.users_with_safety_inbox_activity_count": {
        "description": "(Global) Users that have engaged with events in the safety inbox.",
        "schema": {
            "distinct_id": "User ID interacting with safety inbox",
        },
    },
    "default.metrics_repo.vehicle_crashes_avg": {
        "description": "(Regional) Calculates total crash events per 1000 miles.",
        "schema": {
            "crash_count": "Count of crash events",
            "distance_miles": "The total distance covered (in miles) by an org's fleet",
        },
    },
    "default.metrics_repo.vehicle_drowsiness_avg": {
        "description": "(Regional) Calculates drowsiness events per 1000 miles.",
        "schema": {
            "drowsy_count": "Count of drowsiness detection events",
            "distance_miles": "The total distance covered (in miles) by an org's fleet",
        },
    },
    "default.metrics_repo.vehicle_drowsiness_sum": {
        "description": "(Regional) Calculates drowsiness events per 1000 miles.",
        "schema": {
            "drowsy_count": "Count of drowsiness detection events",
            "distance_miles": "The total distance covered (in miles) by an org's fleet",
        },
    },
    "default.metrics_repo.vehicle_inattentive_driving_avg": {
        "description": "(Regional) Stats on inattentive driving incidents (VG devices only).",
        "schema": {
            "generic_distraction_count": "Count of manual distracted driving events",
            "edge_distracted_driving_count": "Count of automation distracted driving events",
            "total_distraction_count": "Combined automated and manual total",
            "distance_miles": "The total distance covered (in miles) by an org's fleet",
        },
    },
    "default.metrics_repo.vehicle_inattentive_driving_sum": {
        "description": "(Regional) Stats on inattentive driving incidents (VG devices only).",
        "schema": {
            "generic_distraction_count": "Count of manual distracted driving events",
            "edge_distracted_driving_count": "Count of automatic distracted driving events",
            "total_distraction_count": "Combined automated and manual total",
            "distance_miles": "The total distance covered (in miles) by an org's fleet",
        },
    },
    "default.metrics_repo.vehicle_mobile_usage_avg": {
        "description": "(Regional) Stats on mobile usage incidents while driving (VG devices only).",
        "schema": {
            "edge_mobile_usage_count": "Mobile usage events that are detected through AI",
            "raw_mobile_usage_count": "Mobile usage events that are manually detected",
            "mobile_usage_count": "Combined mobile usage events",
            "distance_miles": "The total distance covered (in miles) by an org's fleet",
        },
    },
    "default.metrics_repo.vehicle_mobile_usage_sum": {
        "description": "(Regional) Stats on mobile usage incidents while driving (VG devices only).",
        "schema": {
            "edge_mobile_usage_count": "Mobile usage events that are detected through AI",
            "raw_mobile_usage_count": "Mobile usage events that are manually detected",
            "mobile_usage_count": "Combined mobile usage events",
            "distance_miles": "The total distance covered (in miles) by an org's fleet",
        },
    },
    "default.metrics_repo.vehicle_mpg_by_org_avg": {
        "description": "(Regional) The miles per gallon calculation by org over a specific lookback window. Null if the value is improbably high (above 200) or low (below 2).",
        "schema": {
            "mpge": "The weighted average of per-vehicle MPG for the given org across the lookback window (28 or 7 days)",
            "total_fuel_consumed_gallons": "The total amount of fuel (in gallons) that the org consumed.",
            "total_distance_traveled_miles": "The total distance traveled (in miles) by the org's vehicles.",
            "total_energy_consumed_kwh": "The total energy consumed (in kilowatt-hours) by the org's electric vehicles.",
        },
    },
    "default.metrics_repo.vehicle_severe_speeding_percent": {
        "description": "(Regional) Calculates severe speeding percent (used in fleet benchmarks).",
        "schema": {
            "severe_speeding_ms": "Time spent in severe speeding state",
            "driving_time_ms": "Total drive time",
        },
    },
    "default.metrics_repo.vehicle_severe_speeding_sum": {
        "description": "(Regional) Calculates amount of time spent severe speeding",
        "schema": {
            "severe_speeding_ms": "Time spent in severe speeding state",
            "driving_time_ms": "Total drive time",
        },
    },
    "default.metrics_repo.vehicle_utilization_by_org_percent": {
        "description": "(Regional) Stats on inattentive driving incidents (VG devices only).",
        "schema": {
            "total_available_hours": "Total available hours for the org's fleet",
            "total_utilized_hours": "Total utilized hours for the org's fleet",
        },
    },
    "default.mixpanel_samsara.ai_chat_agent_context_selected": {
        "description": "Choosing the context in the AI Assistant chat window",
        "schema": MIXPANEL_SCHEMA,
    },
    "default.mixpanel_samsara.ai_chat_fault_code_chat_entrypoint": {
        "description": "Clicking on a fault code to get more information via the Ask Samsara feature",
        "schema": MIXPANEL_SCHEMA,
    },
    "default.mixpanel_samsara.ai_chat_first_token": {
        "description": "First token when AI chat is initiated",
        "schema": MIXPANEL_SCHEMA,
    },
    "default.mixpanel_samsara.ai_chat_floating_init": {
        "description": "AI chat initiated",
        "schema": MIXPANEL_SCHEMA,
    },
    "default.mixpanel_samsara.ai_chat_floating_open": {
        "description": "AI chat events registered by Mixpanel",
        "schema": MIXPANEL_SCHEMA,
    },
    "default.mixpanel_samsara.ai_chat_inline_icon_click": {
        "description": "Clicking on the AI Assistant button in the top navigation",
        "schema": MIXPANEL_SCHEMA,
    },
    "default.mixpanel_samsara.ai_chat_send": {
        "description": "AI chat send events registered by Mixpanel",
        "schema": MIXPANEL_SCHEMA,
    },
    "default.mixpanel_samsara.client_mfa_email_otp_submitted": {
        "description": "Events registered by Mixpanel when a user logs in through MFA",
        "schema": MIXPANEL_SCHEMA,
    },
    "default.mixpanel_samsara.cloud_route": {
        "description": "Samsara dashboard events registered by Mixpanel",
        "schema": MIXPANEL_SCHEMA,
    },
    "default.mixpanel_samsara.cloud_route_session": {
        "description": "Tracks the duration of dashboard events",
        "schema": MIXPANEL_SCHEMA,
    },
    "default.mixpanel_samsara.ecodriving_difficultyscore_tooltip_opened": {
        "description": "Opening the difficulty tooltip in Advanced Ecodriving",
        "schema": MIXPANEL_SCHEMA,
    },
    "default.mixpanel_samsara.entityviewevent": {
        "description": "Events registered by Mixpanel when the user looks at an entity in DataHub",
        "schema": MIXPANEL_SCHEMA,
    },
    "default.mixpanel_samsara.fleet_address_autocomplete_location_selected": {
        "description": "Choosing an autocompleted location",
        "schema": MIXPANEL_SCHEMA,
    },
    "default.mixpanel_samsara.fleet_address_autocomplete_lsd_coordinate_search": {
        "description": "Using LSD coordinates to autocomplete an address",
        "schema": MIXPANEL_SCHEMA,
    },
    "default.mixpanel_samsara.fleet_benchmarks_change_peer_group_click": {
        "description": "Changing peer group in Fleet Benchmarks",
        "schema": MIXPANEL_SCHEMA,
    },
    "default.mixpanel_samsara.fleet_benchmarks_compare_clear_selections": {
        "description": "Cleared selections in fleet benchmarks",
        "schema": MIXPANEL_SCHEMA,
    },
    "default.mixpanel_samsara.fleet_benchmarks_compare_compare_modal_appeared": {
        "description": "Compare modal appeared in fleet benchmarks",
        "schema": MIXPANEL_SCHEMA,
    },
    "default.mixpanel_samsara.fleet_benchmarks_compare_compare_modal_cancelled": {
        "description": "Compare modal cancelled in fleet benchmarks report",
        "schema": MIXPANEL_SCHEMA,
    },
    "default.mixpanel_samsara.fleet_benchmarks_compare_compare_occurred": {
        "description": "Compare event occurred in fleet benchmarks",
        "schema": MIXPANEL_SCHEMA,
    },
    "default.mixpanel_samsara.fleet_benchmarks_edit_peer_group_click": {
        "description": "Peer groups edited for fleet benchmarks",
        "schema": MIXPANEL_SCHEMA,
    },
    "default.mixpanel_samsara.fleet_benchmarks_edit_peer_group_edit_existing_tag_group": {
        "description": "Tag groups edited for fleet benchmarks",
        "schema": MIXPANEL_SCHEMA,
    },
    "default.mixpanel_samsara.fleet_benchmarks_filters_change_date": {
        "description": "Date filters changed in fleet benchmarks",
        "schema": MIXPANEL_SCHEMA,
    },
    "default.mixpanel_samsara.fleet_benchmarks_metric_cards_peer_group_distribution_clicked": {
        "description": "Peer group distribution is clicked in the Fleet Benchmarks report",
        "schema": MIXPANEL_SCHEMA,
    },
    "default.mixpanel_samsara.fleet_benchmarks_metric_cards_trend_clicked": {
        "description": "Trend views are clicked on in Fleet Benchmarks",
        "schema": MIXPANEL_SCHEMA,
    },
    "default.mixpanel_samsara.fleet_benchmarks_metric_cards_view_report_clicked": {
        "description": "Metric card view report clicked in fleet benchmarks",
        "schema": MIXPANEL_SCHEMA,
    },
    "default.mixpanel_samsara.fleet_dispatch_route_edit_route_save": {
        "description": "Events for edit and then saving routes in the Dispatch page",
        "schema": MIXPANEL_SCHEMA,
    },
    "default.mixpanel_samsara.fleet_jammingon_toggle": {
        "description": "Events for toggling on/off the jamming feature in the Overview page",
        "schema": MIXPANEL_SCHEMA,
    },
    "default.mixpanel_samsara.fleet_lsdoverlay_toggle": {
        "description": "Events for toggling on/off the LSD overlay",
        "schema": MIXPANEL_SCHEMA,
    },
    "default.mixpanel_samsara.fleet_maintenance_status_open_fault_description_modal": {
        "description": "Events corresponding to opening a fault description on the Maintenance Status page",
        "schema": MIXPANEL_SCHEMA,
    },
    "default.mixpanel_samsara.fleet_public_alert_overlay_click": {
        "description": "Clicking on public alert overlay in the fleet overview page",
        "schema": MIXPANEL_SCHEMA,
    },
    "default.mixpanel_samsara.fleet_publicalerts_toggle": {
        "description": "Clicking on the public alerts toggle on the fleet overview page",
        "schema": MIXPANEL_SCHEMA,
    },
    "default.mixpanel_samsara.fleet_reports_advanced_custom_dashboard_dashboard_module_select": {
        "description": "Select a module from the custom dashboards page",
        "schema": MIXPANEL_SCHEMA,
    },
    "default.mixpanel_samsara.fleet_reports_advanced_idling_filter_change": {
        "description": "Events where the filter was changed on the Advanced Idling report",
        "schema": MIXPANEL_SCHEMA,
    },
    "default.mixpanel_samsara.fleet_reports_advanced_idling_heat_map_zoom": {
        "description": "Events where the heat map was zoomed in the Advanced Idling report",
        "schema": MIXPANEL_SCHEMA,
    },
    "default.mixpanel_samsara.fleet_reports_advanced_idling_tab_change": {
        "description": "Events where the tab was changed in the Advanced Idling report",
        "schema": MIXPANEL_SCHEMA,
    },
    "default.mixpanel_samsara.fleet_reports_safety_aggregated_inbox_details_page_speed_sign_verified_label_toggled": {
        "description": "Toggling the verified label for a speed sign in the Aggregated Inbox",
        "schema": MIXPANEL_SCHEMA,
    },
    "default.mixpanel_samsara.fleet_reports_safety_aggregated_inbox_switchtooldview": {
        "description": "Events registered by Mixpanel when the user switches to the old view for Safety Inbox",
        "schema": MIXPANEL_SCHEMA,
    },
    "default.mixpanel_samsara.fleet_reports_safety_aggregated_inbox_toolbar_click_send_to_coaching": {
        "description": "Clicking on the send to coaching button in the Aggregated Inbox",
        "schema": MIXPANEL_SCHEMA,
    },
    "default.mixpanel_samsara.fleet_reports_safety_inbox_click_safety_event": {
        "description": "Events registered by Mixpanel when the user clicks on a safety event in the Safety Inbox",
        "schema": MIXPANEL_SCHEMA,
    },
    "default.mixpanel_samsara.fleet_reports_safety_inbox_switchtonewview": {
        "description": "Events registered by Mixpanel when the user switches to the new view for Safety Inbox",
        "schema": MIXPANEL_SCHEMA,
    },
    "default.mixpanel_samsara.fleet_reports_safety_speeding_inbox_switchtonewview": {
        "description": "Events registered by Mixpanel when the user switches to the new view for Safety Speeding Inbox",
        "schema": MIXPANEL_SCHEMA,
    },
    "default.mixpanel_samsara.fleet_reports_safety_supervisor_insights_send_to_coaching_modal_coach_assignment_changed": {
        "description": "Events corresponding to the coach assignment changing in Supervisor Insights",
        "schema": MIXPANEL_SCHEMA,
    },
    "default.mixpanel_samsara.fleet_reports_safety_supervisor_insights_send_to_coaching_modal_dismiss_menu_opened": {
        "description": "Events corresponding to dismissing the menu opening in the send to coaching modal in Supervisor Insights",
        "schema": MIXPANEL_SCHEMA,
    },
    "default.mixpanel_samsara.fleet_reports_safety_supervisor_insights_send_to_coaching_modal_modal_opened": {
        "description": "Events corresponding to opening the coaching modal in Supervisor Insights",
        "schema": MIXPANEL_SCHEMA,
    },
    "default.mixpanel_samsara.fleet_reports_safety_supervisor_insights_send_to_coaching_modal_send_to_coaching_submitted": {
        "description": "Events corresponding to going through the send to coaching modal in Supervisor Insights",
        "schema": MIXPANEL_SCHEMA,
    },
    "default.mixpanel_samsara.fleet_reports_safety_supervisor_insights_send_to_coaching_modal_show_all_events_clicked": {
        "description": "Events corresponding to showing all events sent to coaching in Supervisor Insights",
        "schema": MIXPANEL_SCHEMA,
    },
    "default.mixpanel_samsara.fleet_safety_aggregated_inbox_verified_speed_sign_context_label_mismatch": {
        "description": "Mixpanel events that are triggered when a speed sign is flagged as mismatched",
        "schema": MIXPANEL_SCHEMA,
    },
    "default.mixpanel_samsara.fleet_safety_coaching_sessions_click_begin_sessions": {
        "description": "Events registered by Mixpanel when a coaching sessions is begun",
        "schema": MIXPANEL_SCHEMA,
    },
    "default.mixpanel_samsara.fleet_safety_coaching_sessions_complete_session": {
        "description": "Events registered by Mixpanel when a coaching sessions is marked as complete",
        "schema": MIXPANEL_SCHEMA,
    },
    "default.mixpanel_samsara.fleet_threat_details_tooltip_click": {
        "description": "Clicking on threat details tooltip in the overview page",
        "schema": MIXPANEL_SCHEMA,
    },
    "default.mixpanel_samsara.fleet_vehicle_show_faults_open_fault_description_modal": {
        "description": "Events corresponding to looking at fault descriptions on the Fleet Overview page",
        "schema": MIXPANEL_SCHEMA,
    },
    "default.mixpanel_samsara.fleet_weather_toggle": {
        "description": "Clicking on the weather toggle on the fleet overview page",
        "schema": MIXPANEL_SCHEMA,
    },
    "default.mixpanel_samsara.global_search_focus": {
        "description": "Window focus on the global search bar",
        "schema": MIXPANEL_SCHEMA,
    },
    "default.mixpanel_samsara.global_search_preview": {
        "description": "Preview results when using the global search bar",
        "schema": MIXPANEL_SCHEMA,
    },
    "default.mixpanel_samsara.global_search_search": {
        "description": "Clicking on the global search bar",
        "schema": MIXPANEL_SCHEMA,
    },
    "default.mixpanel_samsara.global_search_select": {
        "description": "Selecting an option on the global search bar",
        "schema": MIXPANEL_SCHEMA,
    },
    "default.mixpanel_samsara.homepagesearchevent": {
        "description": "Events registered by Mixpanel when a search is done in the homepage",
        "schema": MIXPANEL_SCHEMA,
    },
    "default.mixpanel_samsara.homepageviewevent": {
        "description": "Events registered by Mixpanel when the homepage is viewed",
        "schema": MIXPANEL_SCHEMA,
    },
    "default.mixpanel_samsara.live_share": {
        "description": "Sharing links for safety events",
        "schema": MIXPANEL_SCHEMA,
    },
    "default.mixpanel_samsara.notificationcenter_alltabclick": {
        "description": "Clicking on the tab in Notification Center to view all notifications",
        "schema": MIXPANEL_SCHEMA,
    },
    "default.mixpanel_samsara.notificationcenter_batchaction_givefeedback": {
        "description": "Giving feedback on a variety of notifications from Notification Center",
        "schema": MIXPANEL_SCHEMA,
    },
    "default.mixpanel_samsara.notificationcenter_batchaction_managenotification": {
        "description": "Managing a set of notifications from Notification Center",
        "schema": MIXPANEL_SCHEMA,
    },
    "default.mixpanel_samsara.notificationcenter_batchaction_markasread": {
        "description": "Marking a set of notifications as read from Notification Center",
        "schema": MIXPANEL_SCHEMA,
    },
    "default.mixpanel_samsara.notificationcenter_batchaction_markasunread": {
        "description": "Marking a set of notifications as unread from Notification Center",
        "schema": MIXPANEL_SCHEMA,
    },
    "default.mixpanel_samsara.notificationcenter_markallasread": {
        "description": "Marking all notifcations as read from Notification Center",
        "schema": MIXPANEL_SCHEMA,
    },
    "default.mixpanel_samsara.notificationcenter_notificationaction_givefeedback": {
        "description": "Providing feedback on a notification from Notification Center",
        "schema": MIXPANEL_SCHEMA,
    },
    "default.mixpanel_samsara.notificationcenter_notificationaction_managenotification": {
        "description": "Mangaging a notification from Notification Center",
        "schema": MIXPANEL_SCHEMA,
    },
    "default.mixpanel_samsara.notificationcenter_notificationaction_markasread": {
        "description": "Marking a notification as read from Notification Center",
        "schema": MIXPANEL_SCHEMA,
    },
    "default.mixpanel_samsara.notificationcenter_notificationaction_markasunread": {
        "description": "Marking a notification as unread from Notification Center",
        "schema": MIXPANEL_SCHEMA,
    },
    "default.mixpanel_samsara.notificationcenter_notificationclick": {
        "description": "Clicking on a notification from the Notification Center",
        "schema": MIXPANEL_SCHEMA,
    },
    "default.mixpanel_samsara.notificationcenter_panelopen": {
        "description": "Opening the panel from Notification Center",
        "schema": MIXPANEL_SCHEMA,
    },
    "default.mixpanel_samsara.notificationcenter_unreadtabclick": {
        "description": "Clicking on an unread tab from Notification Center",
        "schema": MIXPANEL_SCHEMA,
    },
    "default.mixpanel_samsara.org_config_fuel_advanced_idling_settings_saved": {
        "description": "Events where the org config fuel settings were saved for the Advanced Idling report",
        "schema": MIXPANEL_SCHEMA,
    },
    "default.mixpanel_samsara.positive_recognition_kudos_send_kudos": {
        "description": "Events registered by Mixpanel when the user sends kudos to a driver",
        "schema": MIXPANEL_SCHEMA,
    },
    "default.mixpanel_samsara.report_export_download_csv": {
        "description": "Events registered by Mixpanel when the user downloads a CSV export file",
        "schema": MIXPANEL_SCHEMA,
    },
    "default.mixpanel_samsara.report_export_email_csv": {
        "description": "Exporting a CSV report via email",
        "schema": MIXPANEL_SCHEMA,
    },
    "default.mixpanel_samsara.safety_event_review_portal_review_complete_duration": {
        "description": "Reviewing the duration of an event in the SER portal",
        "schema": MIXPANEL_SCHEMA,
    },
    "default.mixpanel_samsara.searchevent": {
        "description": "Events registered by Mixpanel when the user searches in DataHub",
        "schema": MIXPANEL_SCHEMA,
    },
    "default.mixpanel_samsara.self_serve_feature": {
        "description": "Events registered by Mixpanel when the user chooses a feature using self-serve",
        "schema": MIXPANEL_SCHEMA,
    },
    "default.mixpanel_samsara.smart_maps_weather_forecast_overlay_details_clicked": {
        "description": "Events registered by Mixpanel when the weather forecast overlay details are clicked",
        "schema": MIXPANEL_SCHEMA,
    },
    "default.mixpanel_samsara.spotlight_close": {
        "description": "Spotlight close events in the dashboard",
        "schema": MIXPANEL_SCHEMA,
    },
    "default.mixpanel_samsara.spotlight_open": {
        "description": "Spotlight open events in the dashboard",
        "schema": MIXPANEL_SCHEMA,
    },
    "default.mixpanel_samsara.spotlight_search": {
        "description": "Spotlight search events in the dashboard",
        "schema": MIXPANEL_SCHEMA,
    },
    "default.mixpanel_samsara.spotlight_select": {
        "description": "Spotlight select events in the dashboard",
        "schema": MIXPANEL_SCHEMA,
    },
    "default.mixpanel_samsara.supervisor_insights_coaching_effectiveness_click_view_drivers": {
        "description": "Events corresponding to viewing drivers for coaching effectiveness in Supervisor Insights",
        "schema": MIXPANEL_SCHEMA,
    },
    "default.mixpanel_samsara.supervisor_insights_coaching_timeliness_click_send_notification": {
        "description": "Events corresponding to sending a notification on coaching timeliness in Supervisor Insights",
        "schema": MIXPANEL_SCHEMA,
    },
    "default.mixpanel_samsara.supervisor_insights_drivers_requiring_attention_click_driver_name": {
        "description": "Events corresponding to clicking on the name on a driver requiring attention in Supervisor Insights",
        "schema": MIXPANEL_SCHEMA,
    },
    "default.mixpanel_samsara.supervisor_insights_drivers_requiring_attention_click_send_message": {
        "description": "Events corresponding to sending a message to a driver requiring attention in Supervisor Insights",
        "schema": MIXPANEL_SCHEMA,
    },
    "default.mixpanel_samsara.supervisor_insights_drivers_requiring_attention_click_send_to_coaching": {
        "description": "Events corresponding to sending a driver requiring attention to coaching in Supervisor Insights",
        "schema": MIXPANEL_SCHEMA,
    },
    "default.mixpanel_samsara.supervisor_insights_drivers_requiring_attention_safety_score_entry_risk_pill_click": {
        "description": "Events corresponding to clicking on the risk pill in the Risk Insights page",
        "schema": MIXPANEL_SCHEMA,
    },
    "default.mixpanel_samsara.supervisor_insights_drivers_requiring_attention_safety_score_entry_send_to_coaching_click": {
        "description": "Events corresponding to sending a risk event to coaching",
        "schema": MIXPANEL_SCHEMA,
    },
    "default.mixpanel_samsara.supervisor_insights_drivers_to_recognize_click_driver_name": {
        "description": "Events corresponding to clicking on a driver name to recognize them in Supervisor Insights",
        "schema": MIXPANEL_SCHEMA,
    },
    "default.mixpanel_samsara.supervisor_insights_training_timeliness_click_send_message": {
        "description": "Events corresponding to sending a training message in Supervisor Insights",
        "schema": MIXPANEL_SCHEMA,
    },
    "default.mixpanel_samsara.supervisor_view_ecodriving_score_navigation_click": {
        "description": "Events corresponding to clicking on the Ecodriving Score in Supervisor View",
        "schema": MIXPANEL_SCHEMA,
    },
    "default.mixpanel_samsara.supervisor_view_safety_score_navigation_click": {
        "description": "Events corresponding to clicking on the Safety Score in Supervisor View",
        "schema": MIXPANEL_SCHEMA,
    },
    "default.mixpanel_samsara.troy_admin_global_navigate": {
        "description": "All admin events tracked through Mixpanel",
        "schema": MIXPANEL_SCHEMA,
    },
    "default.mixpanel_samsara.troy_driver_global_navigate": {
        "description": "All driver events tracked through Mixpanel",
        "schema": MIXPANEL_SCHEMA,
    },
    "default.mixpanel_samsara.vr4_modalbeingviewed_count": {
        "description": "Events for modal being viewed in video requests",
        "schema": MIXPANEL_SCHEMA,
    },
    "default.mixpanel_samsara.worker_safety_threat_detail_click": {
        "description": "Events registered by Mixpanel when the worker safety threat detail is clicked",
        "schema": MIXPANEL_SCHEMA,
    },
    "default.mixpanel_samsara.worker_safety_threat_detail_map_card_on_the_ground_tab_click": {
        "description": "Events for accessing the On The Ground feature for Weather Intelligence",
        "schema": MIXPANEL_SCHEMA,
    },
    "default.shared_people_ops_data.employees_by_bu": {
        "description": "Breaks down employees by BU",
        "schema": {
            "Email_-_Work": "Email of employee",
            "Worker": "Name of employee",
            "Manager": "Name of employee's manager",
            "Department": "Department (area of business) of employee",
            "Cost_Center": "Cost center (where costs are charged for accounting purposes) that employee belongs to",
            "Cost_Center_Parent": "Parent cost center of employee",
            "Business_Unit": "Business unit (subset of department) of employee",
            "Worker_Active": "Is worker active or not",
            "effective_date": "Last run date of pipeline",
        },
    },
}
