select 'week' as period,
date,
period_start,
period_end,
cloud_region,
region,
account_size_segment,
account_arr_segment,
account_industry,
industry_vertical,
is_paid_safety_customer,
is_paid_telematics_customer,
is_paid_stce_customer,
full_admin_orgs,
custom_role_orgs,
total_orgs,
device_attributes,
device_attributes_orgs,
device_tags,
device_tags_orgs,
device_tags_attributes,
total_devices,
total_device_orgs,
driver_tags,
driver_tags_orgs,
driver_attributes,
driver_attributes_orgs,
driver_tags_attributes,
total_drivers,
total_driver_orgs,
csv_upload_failures,
csv_uploads,
average_row_error_rate,
active_cloud_dashboard_users,
active_cloud_dashboard_orgs,
total_possible_cloud_dashboard_users
from product_analytics.agg_product_scorecard_platform_mpr_global_weekly

union all

select 'month' as period,
date_month as date,
period_start,
period_end,
cloud_region,
region,
account_size_segment,
account_arr_segment,
account_industry,
industry_vertical,
is_paid_safety_customer,
is_paid_telematics_customer,
is_paid_stce_customer,
full_admin_orgs,
custom_role_orgs,
total_orgs,
device_attributes,
device_attributes_orgs,
device_tags,
device_tags_orgs,
device_tags_attributes,
total_devices,
total_device_orgs,
driver_tags,
driver_tags_orgs,
driver_attributes,
driver_attributes_orgs,
driver_tags_attributes,
total_drivers,
total_driver_orgs,
csv_upload_failures,
csv_uploads,
average_row_error_rate,
active_cloud_dashboard_users,
active_cloud_dashboard_orgs,
total_possible_cloud_dashboard_users
from product_analytics.agg_product_scorecard_platform_mpr_global_monthly
