WITH base AS (
  SELECT
    date,
    org_id,
    driver_id,
    pipeline_version,
    process_uuid,
    risk_score,
    classification,
    origin_service,
    timestamp,
    get_json_object(response, '$.trip_date') AS trip_date,
    CAST(get_json_object(response, '$.base_value') AS DOUBLE) AS base_value,
    get_json_object(request, '$.record_hash_key') AS record_hash_key,
    response,
    ROW_NUMBER() OVER (
      PARTITION BY org_id, driver_id, date
      ORDER BY get_json_object(response, '$.trip_date') DESC, timestamp DESC
    ) AS row_num
  FROM datastreams.driver_trip_risk_score_v2_inference_results
),
exploded AS (
  SELECT
    date,
    org_id,
    driver_id,
    pipeline_version,
    process_uuid,
    risk_score,
    classification,
    origin_service,
    timestamp,
    trip_date,
    base_value,
    record_hash_key,
    EXPLODE(
      FROM_JSON(
         get_json_object(response, '$.explainability'),
        'ARRAY<STRUCT<feature:STRING, shap_value:DOUBLE,value:DOUBLE, percent_contribution:DOUBLE, direction:STRING>>'
      )
    ) AS feature_data
  FROM base
  WHERE row_num = 1
),
exploded_features AS (
  SELECT *, feature_data.feature AS feature_name
  FROM exploded
)
SELECT
  date,
  org_id,
  driver_id,
  pipeline_version,
  process_uuid,
  risk_score,
  classification,
  origin_service,
  timestamp,
  trip_date,
  base_value,
  record_hash_key,
  TO_JSON(trip_duration_weighted) AS trip_duration_weighted,
  TO_JSON(n_org_vg_devices) AS n_org_vg_devices,
  TO_JSON(over_speed_limit_mins_60d) AS over_speed_limit_mins_60d,
  TO_JSON(driver_tenure_days) AS driver_tenure_days,
  TO_JSON(distracted_driving_60d) AS distracted_driving_60d,
  TO_JSON(trip_count_below_freezing_60d) AS trip_count_below_freezing_60d,
  TO_JSON(trip_count_over_35_60d) AS trip_count_over_35_60d,
  TO_JSON(proportion_urban_driving_environment_locations_60d) AS proportion_urban_driving_environment_locations_60d,
  TO_JSON(primary_max_weight_lbs) AS primary_max_weight_lbs,
  TO_JSON(hos_violation_count_60d) AS hos_violation_count_60d,
  TO_JSON(moderate_speeding_mins_60d) AS moderate_speeding_mins_60d,
  TO_JSON(mobile_usage_violations_60d) AS mobile_usage_violations_60d,
  TO_JSON(max_speed_weighted) AS max_speed_weighted,
  TO_JSON(proportion_rural_driving_environment_locations_60d) AS proportion_rural_driving_environment_locations_60d,
  TO_JSON(proportion_roadway_service_60d) AS proportion_roadway_service_60d,
  TO_JSON(harsh_braking_60d) AS harsh_braking_60d,
  TO_JSON(proportion_mixed_driving_environment_locations_60d) AS proportion_mixed_driving_environment_locations_60d,
  TO_JSON(proportion_roadway_residential_60d) AS proportion_roadway_residential_60d,
  TO_JSON(light_speeding_mins_60d) AS light_speeding_mins_60d,
  TO_JSON(proportion_roadway_motorway_60d) AS proportion_roadway_motorway_60d,
  TO_JSON(trip_ended_at_night_weighted) AS trip_ended_at_night_weighted,
  TO_JSON(is_eld_relevant_device) AS is_eld_relevant_device,
  TO_JSON(trip_count_60d) AS trip_count_60d,
  TO_JSON(proportion_roadway_trunk_60d) AS proportion_roadway_trunk_60d,
  TO_JSON(proportion_roadway_secondary_60d) AS proportion_roadway_secondary_60d,
  TO_JSON(proportion_roadway_null_60d) AS proportion_roadway_null_60d,
  TO_JSON(trip_ended_in_morning_60d) AS trip_ended_in_morning_60d,
  TO_JSON(severe_speeding_mins_60d) AS severe_speeding_mins_60d,
  TO_JSON(coached_events_60d) AS coached_events_60d,
  TO_JSON(total_events_weighted) AS total_events_weighted,
  TO_JSON(speeding_60d) AS speeding_60d,
  TO_JSON(labelled_crash_count_prev_1_year) AS labelled_crash_count_prev_1_year,
  TO_JSON(proportion_roadway_tertiary_60d) AS proportion_roadway_tertiary_60d,
  TO_JSON(proportion_roadway_unclassified_60d) AS proportion_roadway_unclassified_60d,
  TO_JSON(rolling_stop_60d) AS rolling_stop_60d,
  TO_JSON(proportion_roadway_primary_60d) AS proportion_roadway_primary_60d,
  TO_JSON(drowsiness_60d) AS drowsiness_60d,
  TO_JSON(harsh_turns_60d) AS harsh_turns_60d,
  TO_JSON(proportion_roadway_living_street_60d) AS proportion_roadway_living_street_60d,
  TO_JSON(following_distance_60d) AS following_distance_60d,
  TO_JSON(speeding_ratio_weighted) AS speeding_ratio_weighted,
  TO_JSON(heavy_speeding_mins_60d) AS heavy_speeding_mins_60d,
  TO_JSON(crashes_60d) AS crashes_60d,
  TO_JSON(trip_distance_miles_60d) AS trip_distance_miles_60d,
  TO_JSON(lane_departure_60d) AS lane_departure_60d,
  TO_JSON(virtual_coaching_60d) AS virtual_coaching_60d,
  TO_JSON(harsh_accelerations_60d) AS harsh_accelerations_60d
FROM exploded_features
PIVOT (
  FIRST(CAST(feature_data AS STRUCT<feature:STRING, shap_value:DOUBLE,value:DOUBLE, percent_contribution:DOUBLE, direction:STRING>))
  FOR feature_name IN (
    'trip_duration_weighted',
    'n_org_vg_devices',
    'over_speed_limit_mins_60d',
    'driver_tenure_days',
    'distracted_driving_60d',
    'trip_count_below_freezing_60d',
    'trip_count_over_35_60d',
    'proportion_urban_driving_environment_locations_60d',
    'primary_max_weight_lbs',
    'hos_violation_count_60d',
    'moderate_speeding_mins_60d',
    'mobile_usage_violations_60d',
    'max_speed_weighted',
    'proportion_rural_driving_environment_locations_60d',
    'proportion_roadway_service_60d',
    'harsh_braking_60d',
    'proportion_mixed_driving_environment_locations_60d',
    'proportion_roadway_residential_60d',
    'light_speeding_mins_60d',
    'proportion_roadway_motorway_60d',
    'trip_ended_at_night_weighted',
    'is_eld_relevant_device',
    'trip_count_60d',
    'proportion_roadway_trunk_60d',
    'proportion_roadway_secondary_60d',
    'proportion_roadway_null_60d',
    'trip_ended_in_morning_60d',
    'severe_speeding_mins_60d',
    'coached_events_60d',
    'total_events_weighted',
    'speeding_60d',
    'labelled_crash_count_prev_1_year',
    'proportion_roadway_tertiary_60d',
    'proportion_roadway_unclassified_60d',
    'rolling_stop_60d',
    'proportion_roadway_primary_60d',
    'drowsiness_60d',
    'harsh_turns_60d',
    'proportion_roadway_living_street_60d',
    'following_distance_60d',
    'speeding_ratio_weighted',
    'heavy_speeding_mins_60d',
    'crashes_60d',
    'trip_distance_miles_60d',
    'lane_departure_60d',
    'virtual_coaching_60d',
    'harsh_accelerations_60d'
  )
)
