command: [
  "streamlit",
  "run",
  "app.py"
]

env:
  - name: STREAMLIT_BROWSER_GATHER_USAGE_STATS
    value: "false"
  - name: "SERVING_ENDPOINT"
    valueFrom: "serving_endpoint"
  - name: "DB_INSTANCE_NAME"
    value: "dataproductstest"
  - name: "DB_NAME"
    value: "databricks_postgres"
  - name: "DB_PORT"
    value: "5432"
  - name: "OBO_ENABLED"
    value: True
  - name: "IS_DEV"
    value: "true"
