-- DO NOT EDIT - THIS FILE IS AUTOMATICALLY GENERATED
-- generated by taskrunner gen/netsuitedataview
-- source: samsaradev.io/platform/finops/cmd/netsuite_data_sql_gen/consolidated_invoices_map.sql
SELECT
  CAST(FIRST(ci_map.scs_consolidated_invoice_id, true) AS BIGINT) AS consolidated_invoice_id,
  CAST(ci_map.transaction_id AS BIGINT),
  REPLACE(customers.sam_number, '-', '') AS sam_number
FROM
  edw.netsuite_sterling.scs_consolidated_invoice_map AS ci_map
INNER JOIN edw.netsuite_sterling.transactions AS transactions
  ON transactions.transaction_id = ci_map.transaction_id
INNER JOIN edw.netsuite_sterling.netsuite_customer AS customers
  ON transactions.entity_id = customers.customer_id
WHERE
  ci_map.is_deleted = false
GROUP BY
  ci_map.transaction_id,
  customers.sam_number
