-- DO NOT EDIT - THIS FILE IS AUTOMATICALLY GENERATED
-- generated by taskrunner gen/netsuitedataview
-- source: samsaradev.io/platform/finops/cmd/netsuite_data_sql_gen/licenses.sql
SELECT
  CASE
    (items.item_name)
    WHEN 'LIC-NVR10-5' THEN 'LIC-NVR10-5'
    WHEN 'LIC-CM-EXPRESS-12MO' THEN 'LIC-CM-EXPRESS'
    WHEN 'LIC-AG-12MO' THEN 'LIC-AG-ENT'
    WHEN 'lic-express-vg' THEN 'LIC-VG-EXPRESS'
    WHEN 'LIC-CM1-EXPRESS(2)' THEN 'LIC-CM1-EXPRESS'
    WHEN 'LIC-VG-ENT (O)' THEN 'LIC-VG-ENT'
    WHEN 'LIC-CM-60MO' THEN 'LIC-CM-ENT'
    WHEN 'LIC-VG-EXPRESS-12MO' THEN 'LIC-VG-EXPRESS'
    WHEN 'LIC-CM1-EXPRESS(2)' THEN 'LIC-CM1-EXPRESS'
    WHEN 'LIC-VG-60MO' THEN 'LIC-VG-ENT'
    ELSE items.item_name
  END AS sku,
  -- Rename the license values for clarity
  CASE
    WHEN customers.sam_number IS NOT NULL THEN replace(customers.sam_number, '-', '') -- Remove '-' in SAM number
    ELSE replace(entity.sam_number, '-', '') -- Remove '-' in SAM number
  END AS sam_number,
  CASE
    WHEN t.reprocessed_reason_id IS NOT NULL THEN
    CAST(t.original_order_number_id AS INT)
  ELSE CAST(tl.transaction_id AS BIGINT)
  END AS netsuite_transaction_id, -- Replaces Reprocessed orders with original order id
  CAST(tl.transaction_line_id AS INT) AS netsuite_transaction_line_id,
  t.rtn_number AS return_number,
  t.order_number AS order_number,
  CASE
    (t.transaction_type)
    WHEN 'Return Authorization' THEN 0 - SUM(ABS(tl.item_count)) -- If this is a return, flip the quantity
    ELSE SUM(ABS(tl.item_count)) -- If this is anything else, count it as positive quantity
  END AS quantity,
  t.transaction_type,
  t._fivetran_synced,
  t.is_deleted AS _fivetran_deleted,
  tl.sfdc_product_line_id,
  t.status AS status,
  t.create_date AS order_created_at,
  CAST(t.return_type_id AS INT) AS return_type_id,
  CAST(t.return_subtype_id AS INT) AS return_subtype_id,
  COALESCE(CAST(t.created_from_id AS BIGINT),CAST(created_from_transaction_2.transaction_id AS BIGINT)) AS created_from_id,
  COALESCE(created_from_transaction.status, created_from_transaction_2.status) AS created_from_status, -- we will reference back the original sales orders' status instead of using this
  CASE
    WHEN t.transaction_type = 'Sales Order' AND t.order_type = 'Free Trial Opportunity' THEN to_timestamp(t.trial_start_date)
    WHEN t.transaction_type = 'Return Authorization' THEN COALESCE(t.rma_start_date, t.start_date, contract_item_start_date, created_from_transaction.start_date, created_from_transaction_2.start_date)
    ELSE COALESCE(t.start_date, contract_item_start_date)
  END AS start_date,
  CASE
      WHEN t.transaction_type = 'Sales Order' AND t.order_type = 'Free Trial Opportunity' THEN to_timestamp(t.trial_end_date)
      WHEN t.transaction_type = 'Return Authorization' THEN COALESCE(t.rma_end_date_for_ra, t.end_date, contract_item_end_date, created_from_transaction.end_date, created_from_transaction_2.end_date)
      ELSE COALESCE(t.end_date, contract_item_end_date)
  END AS end_date
FROM
  edw.netsuite_sterling.transactions AS t
  INNER JOIN edw.netsuite_sterling.transaction_line AS tl ON t.transaction_id = tl.transaction_id
  FULL OUTER JOIN edw.netsuite_sterling.netsuite_customer AS customers on customers.customer_id = t.end_customer_id
  FULL OUTER JOIN edw.netsuite_sterling.netsuite_customer AS entity on entity.customer_id = t.entity_id
  FULL OUTER JOIN edw.netsuite_sterling.item_product_group AS items ON items.item_id = tl.item_id
  FULL OUTER JOIN edw.netsuite_sterling.transactions AS created_from_transaction ON created_from_transaction.transaction_id = t.created_from_id
  LEFT JOIN edw.netsuite_sterling.transactions AS created_from_transaction_2 ON created_from_transaction_2.order_number = t.order_number and created_from_transaction_2.transaction_type = 'Sales Order' and created_from_transaction_2.order_type = 'Revenue Opportunity'
  --created_from_transaction_2 is required when order created_from_id is missing, we are using the order number to join on the underlying transaction
WHERE
(
  (
    -- Sales orders
    t.transaction_type = 'Sales Order'
    AND t.order_number NOT LIKE '%-ETF%'
    AND t.trandate != '2029-01-01'
    AND t.order_type in ('Revenue Opportunity', 'Free Trial Opportunity')
    AND LOWER(t.order_number) NOT LIKE '%-x'
  )
  OR
  (
    -- Returns
    t.transaction_type = 'Return Authorization'
    AND (
      t.return_type_id = 1 -- Includes Remorse Refund Returns
      OR t.return_type_id = 5 -- Includes Delinquent Returns
    )
    AND (
      t.return_subtype_id NOT IN (2, 4) -- Excludes Sales Order X Processing and Mexico Migration Return Subtypes
      OR t.return_subtype_id IS NULL -- Includes Return Subtypes that are NULL
    )
    AND t.trandate != '2029-01-01'
  )
)
  AND items.item_name LIKE 'LIC-%'
GROUP BY
  items.item_name,
  netsuite_transaction_id,
  customers.sam_number,
  tl.transaction_line_id,
  t.reprocessed_reason_id,
  t.original_order_number_id,
  t.rtn_number,
  t.order_number,
  t.order_type,
  t.trial_end_date,
  t.trial_start_date,
  t.status,
  t.transaction_type,
  t.create_date,
  t.end_date,
  tl.contract_item_end_date,
  t.start_date,
  t.rma_start_date,
  t.rma_end_date_for_ra,
  t.return_type_id,
  t.return_subtype_id,
  t.created_from_id,
  created_from_status,
  created_from_transaction.start_date,
  created_from_transaction.end_date,
  created_from_transaction_2.start_date,
  created_from_transaction_2.end_date,
  created_from_transaction_2.transaction_id,
  tl.sfdc_product_line_id,
  tl.contract_item_start_date,
  entity.sam_number,
  t._fivetran_synced,
  t.is_deleted
