-- DO NOT EDIT - THIS FILE IS AUTOMATICALLY GENERATED
-- generated by taskrunner gen/netsuitedataview
-- source: samsaradev.io/platform/finops/cmd/netsuite_data_sql_gen/netsuite_child_invoice_amounts.sql
--
-- When calculating invoice amounts, we don't consider positive values because
-- they're not associated with item types and therefore cannot be broken down
-- into sub groups like tax and shipping. Also, if you take the sum of all
-- positive amounts for a given transaction it is always equal to the sum of
-- all negative values.
SELECT
  tl.transaction_id,
  SUM(
    IF(
      items.type_name IN ('Sales Tax Group', 'Sales Tax Item')
      -- Only consider lines with negative values.
      and tl.amount_foreign < 0,
      ABS(tl.amount_foreign),
      0
    )
  ) AS tax,
  SUM(
    IF(
      items.type_name = 'Shipping Cost Item'
      -- Only consider lines with negative values.
      and tl.amount_foreign < 0,
      ABS(tl.amount_foreign),
      0
    )
  ) AS shipping,
  SUM(
    IF(
      items.type_name NOT IN (
        'Shipping Cost Item',
        'Sales Tax Item',
        'Sales Tax Group'
      )
      -- Only consider lines with negative values.
      and tl.amount_foreign < 0,
      ABS(tl.amount_foreign),
      0
    )
  ) AS subtotal,
  SUM(
    IF(
      items.type_name is null
      and tl.amount_foreign > 0,
      tl.amount_foreign,
      0
    )
  ) AS total,
  SUM(tl.amount_foreign_linked) AS payment
FROM
  edw.netsuite_sterling.transaction_line AS tl
  LEFT OUTER JOIN edw.netsuite_sterling.item_product_group AS items
  ON tl.item_id = items.item_id
GROUP BY
  transaction_id
