-- DO NOT EDIT - THIS FILE IS AUTOMATICALLY GENERATED
-- generated by taskrunner gen/netsuitedataview
-- source: samsaradev.io/platform/finops/cmd/netsuite_data_sql_gen/netsuite_child_invoices.sql
SELECT
  transactions.order_type,
  transactions.create_date,
  transactions._fivetran_synced,
  transactions.is_deleted,
  transactions.tranid AS invoice_number,
  CAST(transactions.transaction_id AS BIGINT),
  REPLACE(customers.sam_number, '-', '') AS sam_number,
  -- remove sam_number decoration
  BROUND(invoice_amounts.total - invoice_amounts.shipping - invoice_amounts.tax, 2) AS cost_amount,
  BROUND(invoice_amounts.shipping, 2) AS shipping_amount,
  BROUND(invoice_amounts.tax, 2) AS tax_amount,
  BROUND(invoice_amounts.payment, 2) AS payment_amount,
  currencies.symbol,
  --This is the ISO Currency code
  transactions.amount_unbilled,
  transactions.exchange_rate,
  transactions.status AS invoice_status,
  transactions.due_date,
  transactions.payment_status_id AS payment_status,
  transactions.charge_error_message,
  transactions.related_tranid AS po_number,
  CAST(transactions.transaction_id AS BIGINT) AS netsuite_internal_id,
  transactions.order_number,
  transaction_addresses.bill_company AS billing_addressee,
  transaction_addresses.bill_name AS billing_attention,
  transaction_addresses.bill_address_line_1,
  transaction_addresses.bill_address_line_2,
  transaction_addresses.bill_city,
  transaction_addresses.bill_state,
  transaction_addresses.bill_zip,
  transaction_addresses.bill_country,
  transaction_addresses.bill_phone_number,
  transaction_addresses.ship_attention,
  transaction_addresses.ship_name AS shipping_addressee,
  transaction_addresses.ship_address_line_1,
  transaction_addresses.ship_address_line_2,
  transaction_addresses.ship_city,
  transaction_addresses.ship_state,
  transaction_addresses.ship_zip,
  transaction_addresses.ship_country,
  transaction_addresses.ship_phone_number,
  consolidated_invoices_map.consolidated_invoice_id AS consolidated_invoice_id,
  BROUND(invoice_amounts.total, 2) AS total_amount
  -- The transactions table is the base record for all invoices
FROM
  edw.netsuite_sterling.transactions AS transactions
  INNER JOIN edw.netsuite_sterling.netsuite_customer AS customers -- Many transactions to One customer
    ON transactions.entity_id = customers.customer_id
  LEFT OUTER JOIN edw.netsuite_sterling.currency AS currencies -- Many transactions to One currency
    ON transactions.currency_id = currencies.currency_id
  LEFT OUTER JOIN netsuite_data.transaction_addresses AS transaction_addresses -- One transaction to One transaction_address
    ON transaction_addresses.transaction_id = transactions.transaction_id
  LEFT OUTER JOIN netsuite_data.consolidated_invoices_map AS consolidated_invoices_map
    ON consolidated_invoices_map.transaction_id = transactions.transaction_id
  LEFT OUTER JOIN netsuite_data.netsuite_child_invoice_amounts AS invoice_amounts
    ON invoice_amounts.transaction_id = transactions.transaction_id
WHERE
  (
    SUBSTRING(transactions.order_type, 0, 7) = 'Revenue'
    AND transactions.order_type IS NOT NULL
  )
  AND customers.invoice_push_to_cloud_overrid = 'F'
  AND transactions.reseller_id IS NULL
  AND transactions.finance_partner_id IS NULL
  AND transactions.upfitter_id IS NULL
  AND (
    transactions.status = 'Open'
    OR transactions.status = 'Paid In Full'
  )
  AND invoice_amounts.total != 0
  AND transactions.transaction_type = 'Invoice'
