-- DO NOT EDIT - THIS FILE IS AUTOMATICALLY GENERATED
-- generated by taskrunner gen/netsuitedataview
-- source: samsaradev.io/platform/finops/cmd/netsuite_data_sql_gen/netsuite_consolidated_invoices.sql
SELECT
  ci.scs_consolidated_invoice_num AS consolidated_invoice_num,
  CAST(ci.scs_consolidated_invoice_id AS BIGINT) AS consolidated_invoice_id,
  IF(
    (
      COALESCE(
        ci_amount.total_amount,
        0.0
      ) - COALESCE(
        ci_amount.payment_amount,
        0.0
      )
    ) <= 0.01, 0.0,
    COALESCE(
        ci_amount.total_amount,
        0.0
      ) -
      COALESCE(
        ci_amount.payment_amount,
        0.0
      )
  ) AS amount_remaining,
  ci_amount.total_amount AS total_amount,
  ci.due_date,
  ci.date_created AS create_date,
  ci._fivetran_synced,
  ci.is_deleted AS _fivetran_deleted,
  REPLACE(customers.sam_number, '-', '') AS sam_number, -- remove sam_number decoration
  IF((COALESCE(ci_amount.total_amount, 0.0) - COALESCE(ci_amount.payment_amount, 0.0))<=0.01, 'PAID_IN_FULL', 'OPEN') AS invoice_status,
  currencies.symbol AS currency_symbol,
  ci.payment_status_id AS payment_status,
  ci.charge_error_message
FROM
  edw.netsuite_sterling.scs_consolidated_invoice AS ci
LEFT OUTER JOIN netsuite_data.netsuite_consolidated_invoice_calculated_amount AS ci_amount
  ON ci_amount.consolidated_invoice_id = ci.scs_consolidated_invoice_id
INNER JOIN edw.netsuite_sterling.netsuite_customer AS customers
  ON ci.customer_id = customers.customer_id
LEFT OUTER JOIN edw.netsuite_sterling.currency AS currencies
  ON ci.currency_id = currencies.currency_id
WHERE
  ci.is_deleted = false OR
  ci.is_deleted IS NULL
