-- DO NOT EDIT - THIS FILE IS AUTOMATICALLY GENERATED
-- generated by taskrunner gen/netsuitedataview
-- source: samsaradev.io/platform/finops/cmd/netsuite_data_sql_gen/netsuite_consolidated_invoice_calculated_amount.sql
SELECT
  SUM(COALESCE(netsuite_child_invoice_amounts.payment, 0.0)) AS payment_amount,
  SUM(COALESCE(netsuite_child_invoice_amounts.total, 0.0)) AS total_amount,
  consolidated_invoice_invoices_map.scs_consolidated_invoice_id AS consolidated_invoice_id
FROM netsuite_data.netsuite_child_invoice_amounts AS netsuite_child_invoice_amounts

INNER JOIN edw.netsuite_sterling.scs_consolidated_invoice_map AS consolidated_invoice_invoices_map
  ON consolidated_invoice_invoices_map.transaction_id = netsuite_child_invoice_amounts.transaction_id

GROUP BY consolidated_invoice_invoices_map.scs_consolidated_invoice_id
