-- DO NOT EDIT - THIS FILE IS AUTOMATICALLY GENERATED
-- generated by taskrunner gen/netsuitedataview
-- source: samsaradev.io/platform/finops/cmd/netsuite_data_sql_gen/netsuite_deletion.sql
SELECT
  CAST(t.transaction_id AS BIGINT) AS transaction_id,
  CASE
      WHEN c.sam_number IS NOT NULL THEN replace(c.sam_number, '-', '')
      ELSE replace(e.sam_number, '-', '')
  END AS sam_number,
  t._fivetran_synced,
  t.is_deleted AS _fivetran_deleted,
  t.date_deleted
FROM edw.netsuite_sterling.transactions t
  LEFT JOIN edw.netsuite_sterling.netsuite_customer c ON c.customer_id = t.end_customer_id
  LEFT JOIN edw.netsuite_sterling.netsuite_customer e ON e.customer_id = t.entity_id
WHERE t.is_deleted = True
