-- DO NOT EDIT - THIS FILE IS AUTOMATICALLY GENERATED
-- generated by taskrunner gen/netsuitedataview
-- source: samsaradev.io/platform/finops/cmd/netsuite_data_sql_gen/transaction_addresses.sql
SELECT
  transaction_id,
  FIRST(bill_address_line_1, true) AS bill_address_line_1,
  FIRST(bill_address_line_2, true) AS bill_address_line_2,
  FIRST(bill_address_line_3, true) AS bill_address_line_3,
  FIRST(bill_city, true) AS bill_city,
  FIRST(bill_company, true) AS bill_company,
  FIRST(bill_country, true) AS bill_country,
  FIRST(bill_name, true) AS bill_name,
  FIRST(bill_phone_number, true) AS bill_phone_number,
  FIRST(bill_state, true) AS bill_state,
  FIRST(bill_zip, true) AS bill_zip,
  FIRST(ship_address_line_1, true) AS ship_address_line_1,
  FIRST(ship_address_line_2, true) AS ship_address_line_2,
  FIRST(ship_address_line_3, true) AS ship_address_line_3,
  FIRST(ship_attention, true) AS ship_attention,
  FIRST(ship_city, true) AS ship_city,
  FIRST(ship_company, true) AS ship_company,
  FIRST(ship_country, true) AS ship_country,
  FIRST(ship_name, true) AS ship_name,
  FIRST(ship_phone_number, true) AS ship_phone_number,
  FIRST(ship_state, true) AS ship_state,
  FIRST(ship_zip, true) AS ship_zip
FROM
  edw.netsuite_sterling.transaction_address
GROUP BY
  transaction_id
