-- DO NOT EDIT - THIS FILE IS AUTOMATICALLY GENERATED
-- generated by taskrunner gen/netsuitedataview
-- source: samsaradev.io/platform/finops/cmd/netsuite_data_sql_gen/order_history.sql
--
-- This sql should have the same schema as the corresponding transformed one. 
-- If there are any changes, the transformed one may need to be changed as well.
WITH order_synced AS (
  -- Update the entire order if the Sales Order or any Item Fulfillment has updated
  SELECT
    transactions.order_number AS order_number,
    GREATEST(
      COALESCE(MAX(transactions._fivetran_synced), TO_TIMESTAMP('1000-01-01 00:00:00')),
      COALESCE(MAX(transaction_inventory_numbers._fivetran_synced), TO_TIMESTAMP('1000-01-01 00:00:00'))
    ) AS max_synced
  FROM biztech_edw_netsuite_sb1.transactions AS transactions
  LEFT JOIN biztech_edw_netsuite_sb1.transaction_inventory_numbers AS transaction_inventory_numbers
    ON transaction_inventory_numbers.transaction_id = transactions.transaction_id
      AND transactions.transaction_type = 'Item Fulfillment'
  WHERE transactions.transaction_type = 'Sales Order'
    OR transactions.transaction_type = 'Transfer Order'
    OR transactions.transaction_type = 'Item Fulfillment'
  GROUP BY transactions.order_number
)
SELECT
  CAST(sales_orders.transaction_id AS BIGINT) AS sales_order_transaction_id,
  CAST(item_fulfillments.transaction_id AS BIGINT) AS item_fulfillment_transaction_id,
  CAST(item_fulfillment_lines.transaction_line_id AS INT) AS item_fulfillment_transaction_line_id,
  sales_orders.order_number AS order_number,
  REPLACE(customers.sam_number, '-', '') AS sam_number,
  sales_orders.transaction_type = 'Transfer Order' AS is_transfer_order,
  item_fulfillment_line_items.name AS item_sku,
  item_fulfillment_line_items.displayname AS item_name,
  CAST(ABS(item_fulfillment_lines.item_count) AS INT) AS item_quantity,
  transaction_inventory_numbers.inventory_number AS serial_number,
  sales_orders.status AS sales_order_status,
  item_fulfillments.status AS item_fulfillment_status,
  item_fulfillment_tracking_numbers.tracking_number AS tracking_number,
  item_fulfillment_address.ship_attention AS shipping_contact,
  item_fulfillment_lines.shipping_email AS shipping_contact_email_address,
  sales_orders.shipping_carrier AS delivery_carrier,
  sales_orders.email AS purchased_by_email,

  sales_orders.create_date AS order_created_at,
  item_fulfillments.create_date AS shipped_at,

  -- Shipping Address
  item_fulfillment_address.ship_city,
  item_fulfillment_address.ship_country,
  item_fulfillment_address.ship_state,
  item_fulfillment_address.ship_zip,
  item_fulfillment_address.ship_address_line_1,
  item_fulfillment_address.ship_address_line_2,
  item_fulfillment_address.ship_address_line_3,

  -- Billing Address
  item_fulfillment_address.bill_city,
  item_fulfillment_address.bill_country,
  item_fulfillment_address.bill_state,
  item_fulfillment_address.bill_zip,
  item_fulfillment_address.bill_address_line_1,
  item_fulfillment_address.bill_address_line_2,
  item_fulfillment_address.bill_address_line_3,

  order_synced.max_synced AS _fivetran_synced,
  sales_orders._fivetran_deleted AS _fivetran_deleted

FROM biztech_edw_netsuite_sb1.transactions AS sales_orders
INNER JOIN biztech_edw_netsuite_sb1.customers AS customers
  ON (sales_orders.transaction_type = 'Sales Order' AND sales_orders.entity_id = customers.customer_id)
    OR (sales_orders.transaction_type = 'Transfer Order' AND sales_orders.end_customer_id = customers.customer_id)
INNER JOIN order_synced
  ON sales_orders.order_number = order_synced.order_number
LEFT JOIN biztech_edw_netsuite_sb1.transactions AS item_fulfillments
  ON sales_orders.order_number = item_fulfillments.order_number
    AND item_fulfillments.transaction_type = 'Item Fulfillment'
LEFT JOIN biztech_edw_netsuite_sb1.transaction_address AS item_fulfillment_address
  ON item_fulfillment_address.transaction_id = item_fulfillments.transaction_id
-- An Item Fulfillment can have multiple tracking numbers
LEFT JOIN biztech_edw_netsuite_sb1.transaction_tracking_numbers AS item_fulfillment_tracking_numbers
  ON item_fulfillment_tracking_numbers.transaction_id = item_fulfillments.transaction_id
LEFT JOIN biztech_edw_netsuite_sb1.transaction_lines AS item_fulfillment_lines
  ON item_fulfillment_lines.transaction_id = item_fulfillments.transaction_id
    AND item_fulfillment_lines.gross_amount IS NULL -- Identifies individual lines per product
LEFT JOIN biztech_edw_netsuite_sb1.items AS item_fulfillment_line_items
  ON item_fulfillment_line_items.item_id = item_fulfillment_lines.item_id
-- Not all Items have serial numbers
LEFT JOIN biztech_edw_netsuite_sb1.transaction_inventory_numbers AS transaction_inventory_numbers
  ON transaction_inventory_numbers.transaction_id = item_fulfillments.transaction_id
    AND transaction_inventory_numbers.transaction_line = item_fulfillment_lines.transaction_line_id
WHERE
   (sales_orders.transaction_type = 'Sales Order' OR sales_orders.transaction_type = 'Transfer Order')
   AND (item_fulfillment_line_items.name LIKE 'LIC-%'
    OR item_fulfillment_line_items.name LIKE 'HW-%'
    OR item_fulfillment_line_items.name LIKE 'CBL-%'
    OR item_fulfillment_line_items.name LIKE 'ACC-%')
ORDER BY (sales_order_transaction_id, item_fulfillment_transaction_id, item_fulfillment_transaction_line_id)
