-- DO NOT EDIT - THIS FILE IS AUTOMATICALLY GENERATED
-- generated by taskrunner gen/netsuitedataview
-- source: samsaradev.io/platform/finops/cmd/netsuite_data_sql_gen/netsuite_deletion.sql
SELECT
  CAST(t.transaction_id AS BIGINT) AS transaction_id,
  CASE
      WHEN c.SAM_Number IS NOT NULL THEN replace(c.SAM_Number, '-', '')
      ELSE replace(e.SAM_Number, '-', '')
  END AS sam_number,
  t._fivetran_synced,
  t._fivetran_deleted,
  t.date_deleted
FROM biztech_edw_netsuite_sb1.transactions t
  LEFT JOIN biztech_edw_netsuite_sb1.customers c ON c.CUSTOMER_ID = t.END_CUSTOMER_ID
  LEFT JOIN biztech_edw_netsuite_sb1.customers e ON e.CUSTOMER_ID = t.ENTITY_ID
WHERE t._fivetran_deleted = True
