-- DO NOT EDIT - THIS FILE IS AUTOMATICALLY GENERATED
-- generated by taskrunner gen/netsuitedataview
-- source: samsaradev.io/platform/finops/cmd/netsuite_data_sql_gen/consolidated_invoices_map.sql
--
-- This sql should have the same schema as the corresponding transformed one. 
-- If there are any changes, the transformed one may need to be changed as well.
SELECT
  CAST(FIRST(ci_map.scs___consolidated_invoice_id, true) AS BIGINT) AS consolidated_invoice_id,
  CAST(ci_map.transaction_id AS BIGINT),
  REPLACE(customers.sam_number, '-', '') AS sam_number
FROM
  biztech_edw_netsuite_sb1.scs___consolidated_invoice_invoices_map AS ci_map
INNER JOIN biztech_edw_netsuite_sb1.transactions AS transactions
  ON transactions.transaction_id = ci_map.transaction_id
INNER JOIN biztech_edw_netsuite_sb1.customers AS customers
  ON transactions.entity_id = customers.customer_id
WHERE
  ci_map._fivetran_deleted = false
GROUP BY
  ci_map.transaction_id,
  customers.sam_number
