-- DO NOT EDIT - THIS FILE IS AUTOMATICALLY GENERATED
-- generated by taskrunner gen/netsuitedataview
-- source: samsaradev.io/platform/finops/cmd/netsuite_data_sql_gen/exchange_history.sql
--
-- This sql should have the same schema as the corresponding transformed one. 
-- If there are any changes, the transformed one may need to be changed as well.
WITH item_receipt_serials AS (
  SELECT
 item_receipts.created_from_id,
 item_receipt_inventory_numbers.inventory_number AS serial_number,
 item_receipts_lines.item_id,
 items.name AS sku


FROM biztech_edw_netsuite_sb1.transactions AS item_receipts
INNER JOIN biztech_edw_netsuite_sb1.transaction_lines AS item_receipts_lines
  ON item_receipts.transaction_id = item_receipts_lines.transaction_id
INNER JOIN biztech_edw_netsuite_sb1.transaction_inventory_numbers AS item_receipt_inventory_numbers
  ON item_receipt_inventory_numbers.transaction_id = item_receipts.transaction_id
    AND item_receipt_inventory_numbers.transaction_line = item_receipts_lines.transaction_line_id
INNER JOIN biztech_edw_netsuite_sb1.items AS items
  ON items.item_id = item_receipts_lines.item_id

WHERE
  item_receipts.transaction_type = 'Item Receipt' AND
  created_from_id IS NOT NULL AND
  item_receipt_inventory_numbers.inventory_number IS NOT NULL
), exchange_synced AS (
  -- Update the entire exchange if the Return Authorization or Item Receipt has updated
  SELECT
    transactions.transaction_id AS transaction_id,
    GREATEST(
      COALESCE(MAX(transactions._fivetran_synced), TO_TIMESTAMP('1000-01-01 00:00:00')),
      COALESCE(MAX(item_receipts._fivetran_synced), TO_TIMESTAMP('1000-01-01 00:00:00')),
      COALESCE(MAX(item_receipt_inventory_numbers._fivetran_synced), TO_TIMESTAMP('1000-01-01 00:00:00'))
    ) AS max_synced
  FROM biztech_edw_netsuite_sb1.transactions AS transactions
  LEFT JOIN biztech_edw_netsuite_sb1.transactions AS item_receipts
    ON item_receipts.created_from = transactions.transaction_id
      AND item_receipts.transaction_type = 'Item Receipt'
  LEFT JOIN biztech_edw_netsuite_sb1.transaction_inventory_numbers AS item_receipt_inventory_numbers
    ON item_receipt_inventory_numbers.transaction_id = item_receipts.transaction_id
  WHERE transactions.transaction_type = 'Return Authorization'
  GROUP BY transactions.transaction_id
)
SELECT
  CAST(transactions.transaction_id AS BIGINT) AS transaction_id,
  transactions.transaction_type AS transaction_type,
  CAST(transaction_lines.transaction_line_id AS int) AS transaction_line_id,
  transactions.status,
  transactions.rtn_number AS return_number,
  transactions.order_number AS order_number,
  REPLACE(customers.sam_number, '-', '') AS sam_number,

  items.name AS sku_product_returned,
  items.displayname AS name_product_returned,
  items.name AS sku_product_received,
  items.displayname AS name_product_received,

  ABS(transaction_lines.item_count) AS initial_quantity,
  ABS(transaction_lines.number_billed) AS refunded_quantity,
  ABS(transaction_lines.quantity_received_in_shipment) AS received_quantity,

  item_receipts.serial_number,
  transactions.return_serial_list AS return_serial_list_returned,

  transactions.shipping_carrier AS delivery_carrier,
  address.ship_attention AS shipping_contact,
  transaction_lines.shipping_email AS shipping_contact_email_address,
  transactions.email AS requested_by_email,

  transactions.create_date AS exchange_created_at,

  -- Shipping Address
  address.ship_city,
  address.ship_country,
  address.ship_state,
  address.ship_zip,
  address.ship_address_line_1,
  address.ship_address_line_2,
  address.ship_address_line_3,

  -- Used for processing
  exchange_synced.max_synced AS _fivetran_synced,
  transactions._fivetran_deleted AS _fivetran_deleted

FROM biztech_edw_netsuite_sb1.transactions AS transactions
INNER JOIN biztech_edw_netsuite_sb1.transaction_lines AS transaction_lines
  ON transaction_lines.transaction_id = transactions.transaction_id
INNER JOIN biztech_edw_netsuite_sb1.customers AS customers
  ON transactions.entity_id = customers.customer_id
INNER JOIN biztech_edw_netsuite_sb1.transaction_address AS address
  ON address.transaction_id = transactions.transaction_id
INNER JOIN biztech_edw_netsuite_sb1.items AS items
  ON items.item_id = transaction_lines.item_id
LEFT JOIN item_receipt_serials AS item_receipts
  ON transaction_lines.item_id = item_receipts.item_id
  AND transactions.transaction_id = item_receipts.created_from_id
INNER JOIN exchange_synced
  ON transactions.transaction_id = exchange_synced.transaction_id

WHERE
  transactions.transaction_type = 'Return Authorization'
  AND (items.name LIKE 'HW-%' OR items.name LIKE 'CBL-%' OR items.name LIKE 'ACC-%')
  AND transactions.rtn_number LIKE 'RTN-%' AND transactions.rtn_number NOT LIKE 'RTN-Undefined%'
  AND transactions.rtn_number != 'RTN-'
  AND (
    transactions.return_type_id = 2 -- 'Exchange'
    OR transactions.return_type_id = 3 -- 'Warranty Exchange'
  ) AND transaction_lines.kit_part_number IS NULL
