// Code generated by MockGen. DO NOT EDIT.
// Source: samsaradev.io/infra/dataplatform/datapipelines/datapipelineapi/datapipelineapilambda (interfaces: API)

// Package mock_datapipelineapilambda is a generated GoMock package.
package mock_datapipelineapilambda

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"

	datapipelineapilambda "samsaradev.io/infra/dataplatform/datapipelines/datapipelineapi/datapipelineapilambda"
)

// MockAPI is a mock of API interface.
type MockAPI struct {
	ctrl     *gomock.Controller
	recorder *MockAPIMockRecorder
}

// MockAPIMockRecorder is the mock recorder for MockAPI.
type MockAPIMockRecorder struct {
	mock *MockAPI
}

// NewMockAPI creates a new mock instance.
func NewMockAPI(ctrl *gomock.Controller) *MockAPI {
	mock := &MockAPI{ctrl: ctrl}
	mock.recorder = &MockAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAPI) EXPECT() *MockAPIMockRecorder {
	return m.recorder
}

// DescribeNodeExecution mocks base method.
func (m *MockAPI) DescribeNodeExecution(arg0 context.Context, arg1 string) (*datapipelineapilambda.NodeExecutionDetails, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DescribeNodeExecution", arg0, arg1)
	ret0, _ := ret[0].(*datapipelineapilambda.NodeExecutionDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DescribeNodeExecution indicates an expected call of DescribeNodeExecution.
func (mr *MockAPIMockRecorder) DescribeNodeExecution(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeNodeExecution", reflect.TypeOf((*MockAPI)(nil).DescribeNodeExecution), arg0, arg1)
}
