// Code generated by generate_db_boilerplate. DO NOT EDIT.
package main

import (
	"context"

	"log"
	"os"

	"go.uber.org/fx"

	"samsaradev.io/infra/config"
	"samsaradev.io/infra/dbtools/dbversionstate"
	"samsaradev.io/infra/samsaraaws/s3iface"
	"samsaradev.io/system"
)

func main() {

	var app *migrateApp

	fxApp := system.NewFx(
		&config.ConfigParams{},
		fx.Provide(func(appConfig *config.AppConfig, s3Client s3iface.S3API) dbversionstate.DBState {
			if appConfig.IsDevEnv() && os.Getenv("BUILDKITE") == "" {
				return &dbversionstate.LocalState{}
			}
			return dbversionstate.NewS3State(s3Client)
		}),
		fx.Provide(new),
		fx.Populate(&app),
	)

	ctx := context.Background()

	if err := fxApp.Start(ctx); err != nil {
		log.Fatalf("Failed to start fxApp")
	}

	// Block migrate until the previous run finishes.
	app.waitForLeaderHelper.BlockUntilLeader(ctx)

	if os.Getenv("BUILDKITE") != "" {
		databaseRegions := []string{}
		if err := dbversionstate.CheckProductionDBVersions(AppliedVersions, databaseRegions); err != nil {
			log.Fatalf("DB Versions are being used that haven't been applied in production yet %s", err)
		}
	}

	versionStateMap, err := dbversionstate.GetDBVersionState(app.dbState, AppliedVersions)
	if err != nil {
		log.Fatalln(err)
	}

	runGeneratedMigrations(app, versionStateMap)

	if err := fxApp.Stop(ctx); err != nil {
		log.Fatalf("Failed to stop fxApp")
	}
}
