// Code generated by generate_db_boilerplate. DO NOT EDIT.
package main

import (
	"samsaradev.io/infra/dataplatform/dataplatformtestinternalmodels"
)

var AppliedVersions = map[string]int{
	"dataplatformtestinternal": dataplatformtestinternalmodels.Versions.Applied,
}
