# Stub file for hello world example
AWS_INSUFFICIENT_INSTANCE_CAPACITY_EXCEPTION = "AWS_INSUFFICIENT_INSTANCE_CAPACITY"
CLOUD_PROVIDER_LAUNCH_EXCEPTION = "CLOUD_PROVIDER_LAUNCH"
FAILED_READ_EXCEPTION = "FAILED_READ"
LIBRARY_EXCEPTION = "LIBRARY_EXCEPTION"
SHUFFLE_EXCEPTION = "SHUFFLE_EXCEPTION"
