// Code generated by backendfeaturescompiler; DO NOT EDIT.

package features

import (
	"sync"
	"time"

	"gopkg.in/launchdarkly/go-sdk-common.v2/lduser"
	"gopkg.in/launchdarkly/go-sdk-common.v2/ldvalue"

	"samsaradev.io/helpers/l10n/l10nconstants"
	"samsaradev.io/infra/releasemanagement/featureflagaccessor/interfaces"
	"samsaradev.io/infra/releasemanagement/featureflagaccessor/targeting"
	"samsaradev.io/infra/releasemanagement/featureflagaccessor/utils"
	"samsaradev.io/infra/releasemanagement/launchdarkly"
	"samsaradev.io/infra/releasemanagement/releasemanagementproto"
)

/* This file contains generated accessors for feature flags defined by the
 * parent package in feature_flags.json. To add an accessor for a new flag, add
 * its key to feature_flags.json and run:
 * GO_DIR="infra/dataplatform/app/kinesisstatsdeltalakebackfiller" taskrunner gen/feature_flags/backend
 *
 * For more information, see our documentation for working with LaunchDarkly
 * feature flags:
 * https://samsara.atlassian-us-gov-mod.net/wiki/spaces/RD/pages/4366868/How+to+Use+LaunchDarkly+Feature+Flags
 */

// BackendUser implements interfaces.BackendUser.
var _ interfaces.BackendUser = (*BackendUser)(nil)

// BackendUser implements interfaces.BackendUser.
//
// Provide this struct to generated feature flag accessors to evaluate backend
// flags in this package and any child packages.
type BackendUser struct {
	ldUser *lduser.User
	sync.Once

	// Common backend targeting attributes.
	IsLocal        bool
	OrgId          int64
	OrgName        string
	OrgCell        string
	OrgLocale      l10nconstants.LocaleId
	OrgIsInternal  bool
	OrgReleaseType *releasemanagementproto.OrgReleaseType
	OrgCreatedAt   time.Time
	OrgDeviceCount *uint64
	UserId         int64
	UserName       string
	UserEmail      string

	// Custom targeting attributes.
	Objectstat string
}

func (user *BackendUser) AsBackendLdUser() *lduser.User {
	if user.ldUser != nil {
		return user.ldUser
	}

	user.Do(func() {
		custom := make(map[string]ldvalue.Value)
		custom["objectstat"] = ldvalue.String(user.Objectstat)
		user.ldUser = utils.AccessorUser{
			IsLocal:        user.IsLocal,
			OrgId:          user.OrgId,
			OrgName:        user.OrgName,
			OrgCell:        user.OrgCell,
			OrgLocale:      user.OrgLocale,
			OrgIsInternal:  user.OrgIsInternal,
			OrgReleaseType: user.OrgReleaseType,
			OrgCreatedAt:   user.OrgCreatedAt,
			OrgDeviceCount: user.OrgDeviceCount,
			UserId:         user.UserId,
			UserName:       user.UserName,
			UserEmail:      user.UserEmail,
			Custom:         custom,
		}.GetLdUser()
	})

	return user.ldUser
}

func fallbackUser() interfaces.BackendUser {
	return &BackendUser{}
}

const FFKeyKinesisstatsDeltaLakeBackfill = "kinesisstats-delta-lake-backfill"

func KinesisstatsDeltaLakeBackfillOrErrorWithBridge(user interfaces.BackendUser, bridge *launchdarkly.SDKBridge) (bool, error) {
	return utils.BoolVariationOrErrorWithBridge(
		bridge,
		FFKeyKinesisstatsDeltaLakeBackfill,
		user,
		targeting.UserTypeBackend,
		fallbackUser,
		false,
		true)
}

// https://app.launchdarkly.com/samsara/production/features/kinesisstats-delta-lake-backfill/targeting
func KinesisstatsDeltaLakeBackfillWithBridge(user interfaces.BackendUser, bridge *launchdarkly.SDKBridge) bool {
	value, _ := KinesisstatsDeltaLakeBackfillOrErrorWithBridge(user, bridge)
	return value
}
